package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	"strconv"

	"github.com/MamangRust/pointofsale-graphql-grpc/internal/domain/requests"
	"github.com/MamangRust/pointofsale-graphql-grpc/internal/model"
	"github.com/MamangRust/pointofsale-graphql-grpc/internal/pb"
	mycontext "github.com/MamangRust/pointofsale-graphql-grpc/pkg/context"
	"github.com/MamangRust/pointofsale-graphql-grpc/pkg/errors"
)

// RegisterUser is the resolver for the registerUser field.
func (r *mutationResolver) RegisterUser(ctx context.Context, input model.RegisterInput) (*model.APIResponseRegister, error) {
	return ResolverHandle(r.ResolverHandle, "RegisterUser", ctx, func(ctx context.Context) (*model.APIResponseRegister, error) {
		request := &requests.CreateUserRequest{
			FirstName:       input.Firstname,
			LastName:        input.Lastname,
			Email:           input.Email,
			Password:        input.Password,
			ConfirmPassword: input.ConfirmPassword,
		}

		if err := request.Validate(); err != nil {
			validations := r.parseValidationErrors(err)
			return nil, errors.NewValidationError(validations)
		}

		req := &pb.RegisterRequest{
			Firstname:       request.FirstName,
			Lastname:        request.LastName,
			Email:           request.Email,
			Password:        request.Password,
			ConfirmPassword: request.ConfirmPassword,
		}

		res, err := r.AuthGraphql.AuthClient.RegisterUser(ctx, req)

		if err != nil {
			return nil, r.handleGraphQLError(err, "RegisterUser")
		}

		so := r.AuthGraphql.Mapping.ToGraphqlResponseRegister(res)

		return so, nil
	})
}

// LoginUser is the resolver for the loginUser field.
func (r *mutationResolver) LoginUser(ctx context.Context, input model.LoginInput) (*model.APIResponseLogin, error) {
	return ResolverHandle(r.ResolverHandle, "LoginUser", ctx, func(ctx context.Context) (*model.APIResponseLogin, error) {
		requests := &requests.AuthRequest{
			Email:    input.Email,
			Password: input.Password,
		}

		if err := requests.Validate(); err != nil {
			validations := r.parseValidationErrors(err)
			return nil, errors.NewValidationError(validations)
		}

		cachedResponse, found := r.AuthGraphql.Cache.GetCachedLogin(ctx, requests.Email)
		if found {
			return cachedResponse, nil
		}

		req := &pb.LoginRequest{
			Email:    requests.Email,
			Password: requests.Password,
		}

		res, err := r.AuthGraphql.AuthClient.LoginUser(ctx, req)

		if err != nil {
			return nil, r.handleGraphQLError(err, "LoginUser")
		}

		so := r.AuthGraphql.Mapping.ToGraphqlResponseLogin(res)

		r.AuthGraphql.Cache.SetCachedLogin(ctx, req.Email, so)

		return so, nil
	})
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, input model.RefreshTokenInput) (*model.APIResponseRefreshToken, error) {
	return ResolverHandle(r.ResolverHandle, "RefreshToken", ctx, func(ctx context.Context) (*model.APIResponseRefreshToken, error) {
		cachedResponse, found := r.AuthGraphql.Cache.GetRefreshToken(ctx, input.RefreshToken)
		if found {
			return cachedResponse, nil
		}

		res, err := r.AuthGraphql.AuthClient.RefreshToken(ctx, &pb.RefreshTokenRequest{
			RefreshToken: input.RefreshToken,
		})

		if err != nil {
			return nil, r.handleGraphQLError(err, "RefreshToken")
		}

		so := r.AuthGraphql.Mapping.ToGraphqlResponseRefreshToken(res)

		r.AuthGraphql.Cache.SetRefreshToken(ctx, input.RefreshToken, so)

		return so, nil
	})
}

// GetMe is the resolver for the getMe field.
func (r *queryResolver) GetMe(ctx context.Context) (*model.APIResponseGetMe, error) {
	return ResolverHandle(r.ResolverHandle, "RefreshToken", ctx, func(ctx context.Context) (*model.APIResponseGetMe, error) {
		uid, ok := mycontext.UserForContext(ctx)

		if !ok || uid == 0 {
			return nil, fmt.Errorf("unauthorized: user ID not found in request context")
		}

		userId := strconv.Itoa(uid)

		cachedResponse, found := r.AuthGraphql.Cache.GetCachedUserInfo(ctx, userId)
		if found {
			return cachedResponse, nil
		}

		res, err := r.AuthGraphql.AuthClient.GetMe(ctx, &pb.GetMeRequest{UserId: int32(uid)})

		if err != nil {
			return nil, r.handleGraphQLError(err, "GetMe")
		}

		so := r.AuthGraphql.Mapping.ToGraphqlResponseGetMe(res)

		r.AuthGraphql.Cache.SetCachedUserInfo(ctx, userId, so)

		return so, nil
	})
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
