package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/MamangRust/pointofsale-graphql-grpc/internal/model"
	"github.com/MamangRust/pointofsale-graphql-grpc/internal/pb"
	"github.com/MamangRust/pointofsale-graphql-grpc/pkg/errors"
)

// FindAllOrderItem is the resolver for the findAllOrderItem field.
func (r *queryResolver) FindAllOrderItem(ctx context.Context, input model.FindAllOrderItemInput) (*model.APIResponsePaginationOrderItem, error) {
	return ResolverHandle(r.ResolverHandle, "FindAllOrderItem", ctx, func(ctx context.Context) (*model.APIResponsePaginationOrderItem, error) {
		page := int32(*input.Page)
		pageSize := int32(*input.PageSize)
		if page <= 0 {
			page = 1
		}
		if pageSize <= 0 {
			pageSize = 10
		}

		normalizedInput := &model.FindAllOrderItemInput{
			Page:     &page,
			PageSize: &pageSize,
			Search:   input.Search,
		}

		if cached, found := r.OrderItemGraphql.Cache.GetCachedOrderItemsAll(ctx, normalizedInput); found {
			return cached, nil
		}

		req := &pb.FindAllOrderItemRequest{
			Page:     int32(page),
			PageSize: int32(pageSize),
			Search:   *input.Search,
		}
		orderItems, err := r.OrderItemGraphql.OrderItemClient.FindAll(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindAllOrderItem")
		}

		so := r.OrderItemGraphql.Mapping.ToGraphqlResponsePaginationOrderItem(orderItems)

		r.OrderItemGraphql.Cache.SetCachedOrderItemsAll(ctx, normalizedInput, so)

		return so, nil
	})
}

// FindByActiveOrderItem is the resolver for the findByActiveOrderItem field.
func (r *queryResolver) FindByActiveOrderItem(ctx context.Context, input model.FindAllOrderItemInput) (*model.APIResponsePaginationOrderItemDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "FindByActiveOrderItem", ctx, func(ctx context.Context) (*model.APIResponsePaginationOrderItemDeleteAt, error) {
		page := int32(*input.Page)
		pageSize := int32(*input.PageSize)
		if page <= 0 {
			page = 1
		}
		if pageSize <= 0 {
			pageSize = 10
		}

		normalizedInput := &model.FindAllOrderItemInput{
			Page:     &page,
			PageSize: &pageSize,
			Search:   input.Search,
		}

		if cached, found := r.OrderItemGraphql.Cache.GetCachedOrderItemActive(ctx, normalizedInput); found {
			return cached, nil
		}

		req := &pb.FindAllOrderItemRequest{
			Page:     int32(page),
			PageSize: int32(pageSize),
			Search:   *input.Search,
		}
		orderItems, err := r.OrderItemGraphql.OrderItemClient.FindByActive(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindByActiveOrderItem")
		}

		so := r.OrderItemGraphql.Mapping.ToGraphqlResponsePaginationOrderItemDeleteAt(orderItems)

		r.OrderItemGraphql.Cache.SetCachedOrderItemActive(ctx, normalizedInput, so)

		return so, nil
	})
}

// FindByTrashedOrderItem is the resolver for the findByTrashedOrderItem field.
func (r *queryResolver) FindByTrashedOrderItem(ctx context.Context, input model.FindAllOrderItemInput) (*model.APIResponsePaginationOrderItemDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "FindByTrashedOrderItem", ctx, func(ctx context.Context) (*model.APIResponsePaginationOrderItemDeleteAt, error) {
		page := int32(*input.Page)
		pageSize := int32(*input.PageSize)
		if page <= 0 {
			page = 1
		}
		if pageSize <= 0 {
			pageSize = 10
		}

		normalizedInput := &model.FindAllOrderItemInput{
			Page:     &page,
			PageSize: &pageSize,
			Search:   input.Search,
		}

		if cached, found := r.OrderItemGraphql.Cache.GetCachedOrderItemTrashed(ctx, normalizedInput); found {
			return cached, nil
		}

		req := &pb.FindAllOrderItemRequest{
			Page:     int32(page),
			PageSize: int32(pageSize),
			Search:   *input.Search,
		}
		orderItems, err := r.OrderItemGraphql.OrderItemClient.FindByTrashed(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindByTrashedOrderItem")
		}

		so := r.OrderItemGraphql.Mapping.ToGraphqlResponsePaginationOrderItemDeleteAt(orderItems)

		r.OrderItemGraphql.Cache.SetCachedOrderItemTrashed(ctx, normalizedInput, so)

		return so, nil
	})
}

// FindOrderItemByOrder is the resolver for the findOrderItemByOrder field.
func (r *queryResolver) FindOrderItemByOrder(ctx context.Context, input model.FindByIDOrderItemInput) (*model.APIResponsesOrderItem, error) {
	return ResolverHandle(r.ResolverHandle, "FindOrderItemByOrder", ctx, func(ctx context.Context) (*model.APIResponsesOrderItem, error) {
		id := int(input.ID)

		if id <= 0 {
			return nil, errors.NewBadRequestError("id is required")
		}

		if cached, found := r.OrderItemGraphql.Cache.GetCachedOrderItems(ctx, id); found {
			return cached, nil
		}

		res, err := r.OrderItemGraphql.OrderItemClient.FindOrderItemByOrder(ctx, &pb.FindByIdOrderItemRequest{
			Id: int32(id),
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindOrderItemByOrder")
		}

		so := r.OrderItemGraphql.Mapping.ToGraphqlResponsesOrderItem(res)

		r.OrderItemGraphql.Cache.SetCachedOrderItems(ctx, so)

		return so, nil
	})
}
