package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/MamangRust/pointofsale-graphql-grpc/internal/domain/response"
	"github.com/MamangRust/pointofsale-graphql-grpc/internal/model"
	"github.com/MamangRust/pointofsale-graphql-grpc/internal/pb"
	"github.com/MamangRust/pointofsale-graphql-grpc/pkg/errors/order_errors"
	"google.golang.org/protobuf/types/known/emptypb"
)

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input model.CreateOrderInput) (*model.APIResponseOrder, error) {
	req := &pb.CreateOrderRequest{
		MerchantId: int32(input.MerchantID),
		CashierId:  int32(input.CashierID),
	}

	for _, item := range input.Items {
		req.Items = append(req.Items, &pb.CreateOrderItemRequest{
			ProductId: int32(item.ProductID),
			Quantity:  int32(item.Quantity),
		})
	}

	order, err := r.OrderGraphql.OrderClient.Create(ctx, req)
	if err != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.OrderGraphql.Mapping.ToGraphqlResponseOrder(order)

	return so, nil
}

// UpdateOrder is the resolver for the updateOrder field.
func (r *mutationResolver) UpdateOrder(ctx context.Context, input model.UpdateOrderInput) (*model.APIResponseOrder, error) {
	id := int32(input.OrderID)
	if id == 0 {
		return nil, order_errors.ErrGraphqlFailedInvalidId
	}

	req := &pb.UpdateOrderRequest{
		OrderId: id,
	}

	for _, item := range input.Items {
		req.Items = append(req.Items, &pb.UpdateOrderItemRequest{
			OrderItemId: int32(item.OrderItemID),
			ProductId:   int32(item.ProductID),
			Quantity:    int32(item.Quantity),
		})
	}

	order, err := r.OrderGraphql.OrderClient.Update(ctx, req)
	if err != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.OrderGraphql.Mapping.ToGraphqlResponseOrder(order)

	return so, nil
}

// TrashedOrder is the resolver for the trashedOrder field.
func (r *mutationResolver) TrashedOrder(ctx context.Context, input model.FindByIDOrderInput) (*model.APIResponseOrderDeleteAt, error) {
	id := int32(input.ID)
	if id == 0 {
		return nil, order_errors.ErrGraphqlFailedInvalidId
	}

	order, err := r.OrderGraphql.OrderClient.TrashedOrder(ctx, &pb.FindByIdOrderRequest{
		Id: id,
	})
	if err != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.OrderGraphql.Mapping.ToGraphqlResponseOrderDeleteAt(order)

	return so, nil
}

// RestoreOrder is the resolver for the restoreOrder field.
func (r *mutationResolver) RestoreOrder(ctx context.Context, input model.FindByIDOrderInput) (*model.APIResponseOrderDeleteAt, error) {
	id := int32(input.ID)
	if id == 0 {
		return nil, order_errors.ErrGraphqlFailedInvalidId
	}

	order, err := r.OrderGraphql.OrderClient.RestoreOrder(ctx, &pb.FindByIdOrderRequest{
		Id: id,
	})
	if err != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.OrderGraphql.Mapping.ToGraphqlResponseOrderDeleteAt(order)

	return so, nil
}

// DeleteOrderPermanent is the resolver for the deleteOrderPermanent field.
func (r *mutationResolver) DeleteOrderPermanent(ctx context.Context, input model.FindByIDOrderInput) (*model.APIResponseOrderDelete, error) {
	id := int32(input.ID)
	if id == 0 {
		return nil, order_errors.ErrGraphqlFailedInvalidId
	}

	res, err := r.OrderGraphql.OrderClient.DeleteOrderPermanent(ctx, &pb.FindByIdOrderRequest{Id: id})

	if err != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.OrderGraphql.Mapping.ToGraphqlResponseOrderDelete(res)

	return so, nil
}

// RestoreAllOrder is the resolver for the restoreAllOrder field.
func (r *mutationResolver) RestoreAllOrder(ctx context.Context) (*model.APIResponseOrderAll, error) {
	res, err := r.OrderGraphql.OrderClient.RestoreAllOrder(ctx, &emptypb.Empty{})

	if err != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.OrderGraphql.Mapping.ToGraphqlResponseOrderAll(res)

	return so, nil
}

// DeleteAllOrderPermanent is the resolver for the deleteAllOrderPermanent field.
func (r *mutationResolver) DeleteAllOrderPermanent(ctx context.Context) (*model.APIResponseOrderAll, error) {
	res, err := r.OrderGraphql.OrderClient.DeleteAllOrderPermanent(ctx, &emptypb.Empty{})

	if err != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.OrderGraphql.Mapping.ToGraphqlResponseOrderAll(res)

	return so, nil
}

// FindMonthlyTotalRevenue is the resolver for the findMonthlyTotalRevenue field.
func (r *queryResolver) FindMonthlyTotalRevenue(ctx context.Context, input model.FindYearMonthTotalRevenueInput) (*model.APIResponseOrderMonthlyTotalRevenue, error) {
	req := &pb.FindYearMonthTotalRevenue{
		Year:  int32(input.Year),
		Month: int32(input.Month),
	}

	if req.Year <= 0 {
		return nil, order_errors.ErrGraphqlInvalidYear
	}
	if req.Month <= 0 || req.Month > 12 {
		return nil, order_errors.ErrGraphqlInvalidMonth
	}

	methods, err := r.OrderGraphql.OrderClient.FindMonthlyTotalRevenue(ctx, req)
	if err != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.OrderGraphql.Mapping.ToGraphqlResponseMonthlyTotalRevenue(methods)

	return so, nil
}

// FindYearlyTotalRevenue is the resolver for the findYearlyTotalRevenue field.
func (r *queryResolver) FindYearlyTotalRevenue(ctx context.Context, input model.FindYearTotalRevenueInput) (*model.APIResponseOrderYearlyTotalRevenue, error) {
	year := int32(input.Year)
	if year <= 0 {
		return nil, order_errors.ErrGraphqlInvalidYear
	}

	methods, err := r.OrderGraphql.OrderClient.FindYearlyTotalRevenue(ctx, &pb.FindYearTotalRevenue{Year: year})
	if err != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.OrderGraphql.Mapping.ToGraphqlResponseYearlyTotalRevenue(methods)

	return so, nil
}

// FindMonthlyTotalRevenueByID is the resolver for the findMonthlyTotalRevenueById field.
func (r *queryResolver) FindMonthlyTotalRevenueByID(ctx context.Context, input model.FindYearMonthTotalRevenueByIDInput) (*model.APIResponseOrderMonthlyTotalRevenue, error) {
	req := &pb.FindYearMonthTotalRevenueById{
		OrderId: int32(input.OrderID),
		Month:   int32(input.Month),
		Year:    int32(input.Year),
	}

	if req.Year <= 0 {
		return nil, order_errors.ErrGraphqlInvalidYear
	}
	if req.Month <= 0 || req.Month > 12 {
		return nil, order_errors.ErrGraphqlInvalidMonth
	}
	if req.OrderId <= 0 {
		return nil, order_errors.ErrGraphqlFailedInvalidId
	}

	methods, err := r.OrderGraphql.OrderClient.FindMonthlyTotalRevenueById(ctx, req)
	if err != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.OrderGraphql.Mapping.ToGraphqlResponseMonthlyTotalRevenue(methods)

	return so, nil
}

// FindYearlyTotalRevenueByID is the resolver for the findYearlyTotalRevenueById field.
func (r *queryResolver) FindYearlyTotalRevenueByID(ctx context.Context, input model.FindYearTotalRevenueByIDInput) (*model.APIResponseOrderYearlyTotalRevenue, error) {
	req := &pb.FindYearTotalRevenueById{
		OrderId: int32(input.OrderID),
		Year:    int32(input.Year),
	}

	if req.Year <= 0 {
		return nil, order_errors.ErrGraphqlInvalidYear
	}
	if req.OrderId <= 0 {
		return nil, order_errors.ErrGraphqlFailedInvalidId
	}

	methods, err := r.OrderGraphql.OrderClient.FindYearlyTotalRevenueById(ctx, req)
	if err != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.OrderGraphql.Mapping.ToGraphqlResponseYearlyTotalRevenue(methods)

	return so, nil
}

// FindMonthlyTotalRevenueByMerchant is the resolver for the findMonthlyTotalRevenueByMerchant field.
func (r *queryResolver) FindMonthlyTotalRevenueByMerchant(ctx context.Context, input model.FindYearMonthTotalRevenueByMerchantInput) (*model.APIResponseOrderMonthlyTotalRevenue, error) {
	req := &pb.FindYearMonthTotalRevenueByMerchant{
		Year:       int32(input.Year),
		Month:      int32(input.Month),
		MerchantId: int32(input.MerchantID),
	}

	if req.Year <= 0 {
		return nil, order_errors.ErrGraphqlInvalidYear
	}
	if req.Month <= 0 || req.Month > 12 {
		return nil, order_errors.ErrGraphqlInvalidMonth
	}
	if req.MerchantId <= 0 {
		return nil, order_errors.ErrGraphqlFailedInvalidId
	}

	methods, err := r.OrderGraphql.OrderClient.FindMonthlyTotalRevenueByMerchant(ctx, req)
	if err != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.OrderGraphql.Mapping.ToGraphqlResponseMonthlyTotalRevenue(methods)

	return so, nil
}

// FindYearlyTotalRevenueByMerchant is the resolver for the findYearlyTotalRevenueByMerchant field.
func (r *queryResolver) FindYearlyTotalRevenueByMerchant(ctx context.Context, input model.FindYearTotalRevenueByMerchantInput) (*model.APIResponseOrderYearlyTotalRevenue, error) {
	req := &pb.FindYearTotalRevenueByMerchant{
		Year:       int32(input.Year),
		MerchantId: int32(input.MerchantID),
	}

	if req.Year <= 0 {
		return nil, order_errors.ErrGraphqlInvalidYear
	}
	if req.MerchantId <= 0 {
		return nil, order_errors.ErrGraphqlFailedInvalidId
	}

	methods, err := r.OrderGraphql.OrderClient.FindYearlyTotalRevenueByMerchant(ctx, req)
	if err != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.OrderGraphql.Mapping.ToGraphqlResponseYearlyTotalRevenue(methods)

	return so, nil
}

// FindAllOrder is the resolver for the findAllOrder field.
func (r *queryResolver) FindAllOrder(ctx context.Context, input model.FindAllOrderInput) (*model.APIResponsePaginationOrder, error) {
	page := int32(*input.Page)
	pageSize := int32(*input.PageSize)
	search := input.Search

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	reqService := &pb.FindAllOrderRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   *search,
	}

	orders, err := r.OrderGraphql.OrderClient.FindAll(ctx, reqService)
	if err != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.OrderGraphql.Mapping.ToGraphqlResponsePaginationOrder(orders)

	return so, nil
}

// FindByMerchantOrder is the resolver for the findByMerchantOrder field.
func (r *queryResolver) FindByMerchantOrder(ctx context.Context, input model.FindAllOrderMerchantInput) (*model.APIResponsePaginationOrder, error) {
	page := int32(*input.Page)
	pageSize := int32(*input.PageSize)
	search := input.Search
	merchantId := input.MerchantID

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	reqService := &pb.FindAllOrderMerchantRequest{
		Page:       page,
		PageSize:   pageSize,
		Search:     *search,
		MerchantId: int32(merchantId),
	}

	orders, err := r.OrderGraphql.OrderClient.FindByMerchant(ctx, reqService)
	if err != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.OrderGraphql.Mapping.ToGraphqlResponsePaginationOrder(orders)

	return so, nil
}

// FindByIDOrder is the resolver for the findByIdOrder field.
func (r *queryResolver) FindByIDOrder(ctx context.Context, input model.FindByIDOrderInput) (*model.APIResponseOrder, error) {
	id := int32(input.ID)

	if id <= 0 {
		return nil, order_errors.ErrGraphqlFailedInvalidId
	}

	res, err := r.OrderGraphql.OrderClient.FindById(ctx, &pb.FindByIdOrderRequest{
		Id: id,
	})

	if err != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.OrderGraphql.Mapping.ToGraphqlResponseOrder(res)

	return so, nil
}

// FindByActiveOrder is the resolver for the findByActiveOrder field.
func (r *queryResolver) FindByActiveOrder(ctx context.Context, input model.FindAllOrderInput) (*model.APIResponsePaginationOrderDeleteAt, error) {
	page := int32(*input.Page)
	pageSize := int32(*input.PageSize)
	search := input.Search

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	reqService := &pb.FindAllOrderRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   *search,
	}

	orders, err := r.OrderGraphql.OrderClient.FindByActive(ctx, reqService)
	if err != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.OrderGraphql.Mapping.ToGraphqlResponsePaginationOrderDeleteAt(orders)

	return so, nil
}

// FindByTrashedOrder is the resolver for the findByTrashedOrder field.
func (r *queryResolver) FindByTrashedOrder(ctx context.Context, input model.FindAllOrderInput) (*model.APIResponsePaginationOrderDeleteAt, error) {
	page := int32(*input.Page)
	pageSize := int32(*input.PageSize)
	search := input.Search

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	reqService := &pb.FindAllOrderRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   *search,
	}

	orders, err := r.OrderGraphql.OrderClient.FindByTrashed(ctx, reqService)
	if err != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.OrderGraphql.Mapping.ToGraphqlResponsePaginationOrderDeleteAt(orders)

	return so, nil
}

// FindMonthlyRevenue is the resolver for the findMonthlyRevenue field.
func (r *queryResolver) FindMonthlyRevenue(ctx context.Context, input model.FindYearOrderInput) (*model.APIResponseOrderMonthly, error) {
	year := int32(input.Year)
	if year <= 0 {
		return nil, order_errors.ErrGraphqlInvalidYear
	}

	res, err := r.OrderGraphql.OrderClient.FindMonthlyRevenue(ctx, &pb.FindYearOrder{
		Year: year,
	})
	if err != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.OrderGraphql.Mapping.ToGraphqlResponseMonthlyRevenue(res)

	return so, nil
}

// FindYearlyRevenue is the resolver for the findYearlyRevenue field.
func (r *queryResolver) FindYearlyRevenue(ctx context.Context, input model.FindYearOrderInput) (*model.APIResponseOrderYearly, error) {
	year := int32(input.Year)
	if year <= 0 {
		return nil, order_errors.ErrGraphqlInvalidYear
	}

	res, err := r.OrderGraphql.OrderClient.FindYearlyRevenue(ctx, &pb.FindYearOrder{Year: year})
	if err != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(err)
	}
	so := r.OrderGraphql.Mapping.ToGraphqlResponseYearlyRevenue(res)

	return so, nil
}

// FindMonthlyRevenueByMerchant is the resolver for the findMonthlyRevenueByMerchant field.
func (r *queryResolver) FindMonthlyRevenueByMerchant(ctx context.Context, input model.FindYearOrderByMerchantInput) (*model.APIResponseOrderMonthly, error) {
	req := &pb.FindYearOrderByMerchant{
		Year:       int32(input.Year),
		MerchantId: int32(input.MerchantID),
	}

	if req.Year <= 0 {
		return nil, order_errors.ErrGraphqlInvalidYear
	}
	if req.MerchantId <= 0 {
		return nil, order_errors.ErrGraphqlFailedInvalidMerchantId
	}

	res, err := r.OrderGraphql.OrderClient.FindMonthlyRevenueByMerchant(ctx, req)
	if err != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.OrderGraphql.Mapping.ToGraphqlResponseMonthlyRevenue(res)

	return so, nil
}

// FindYearlyRevenueByMerchant is the resolver for the findYearlyRevenueByMerchant field.
func (r *queryResolver) FindYearlyRevenueByMerchant(ctx context.Context, input model.FindYearOrderByMerchantInput) (*model.APIResponseOrderYearly, error) {
	req := &pb.FindYearOrderByMerchant{
		Year:       int32(input.Year),
		MerchantId: int32(input.MerchantID),
	}

	if req.Year <= 0 {
		return nil, order_errors.ErrGraphqlInvalidYear
	}
	if req.MerchantId <= 0 {
		return nil, order_errors.ErrGraphqlFailedInvalidId
	}

	res, err := r.OrderGraphql.OrderClient.FindYearlyRevenueByMerchant(ctx, req)
	if err != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.OrderGraphql.Mapping.ToGraphqlResponseYearlyRevenue(res)

	return so, nil

}
