package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"time"

	"github.com/MamangRust/pointofsale-graphql-grpc/internal/domain/response"
	"github.com/MamangRust/pointofsale-graphql-grpc/internal/model"
	"github.com/MamangRust/pointofsale-graphql-grpc/internal/pb"
	"github.com/MamangRust/pointofsale-graphql-grpc/pkg/errors/product_errors"
	"google.golang.org/protobuf/types/known/emptypb"
)

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.CreateProductInput) (*model.APIResponseProduct, error) {
	var imagePath string

	if input.Image.Filename != "" && input.Image.ContentType != "" {
		upload := input.Image.File
		ext := filepath.Ext(input.Image.Filename)
		filename := fmt.Sprintf("%d%s", time.Now().UnixNano(), ext)
		imagePath = filepath.Join("uploads/products", filename)

		if err := r.ProductGraphql.ImageUpload.EnsureUploadDirectory("uploads/products"); err != nil {
			return nil, fmt.Errorf("failed to create upload directory: %w", err)
		}

		out, err := os.Create(imagePath)
		if err != nil {
			return nil, fmt.Errorf("failed to create image file: %w", err)
		}
		defer out.Close()

		if _, err := io.Copy(out, upload); err != nil {
			r.ProductGraphql.ImageUpload.CleanupImageOnFailure(imagePath)
			return nil, fmt.Errorf("failed to save uploaded image: %w", err)
		}
	}

	req := &pb.CreateProductRequest{
		MerchantId:   int32(input.MerchantID),
		CategoryId:   int32(input.CategoryID),
		Name:         input.Name,
		Description:  *input.Description,
		Price:        int32(input.Price),
		CountInStock: int32(input.CountInStock),
		Brand:        *input.Brand,
		Weight:       int32(*input.Weight),
		ImageProduct: imagePath,
	}

	product, err := r.ProductGraphql.ProductClient.Create(ctx, req)
	if err != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.ProductGraphql.Mapping.ToGraphqlResponseProduct(product)

	return so, nil
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, input model.UpdateProductInput) (*model.APIResponseProduct, error) {
	var imagePath string

	if input.Image != nil && input.Image.Filename != "" {
		upload := input.Image.File
		ext := filepath.Ext(input.Image.Filename)
		filename := fmt.Sprintf("%d%s", time.Now().UnixNano(), ext)
		imagePath = filepath.Join("uploads/products", filename)

		if err := r.ProductGraphql.ImageUpload.EnsureUploadDirectory("uploads/products"); err != nil {
			return nil, fmt.Errorf("failed to create upload directory: %w", err)
		}

		out, err := os.Create(imagePath)
		if err != nil {
			return nil, fmt.Errorf("failed to create image file: %w", err)
		}
		defer out.Close()

		if _, err := io.Copy(out, upload); err != nil {
			r.ProductGraphql.ImageUpload.CleanupImageOnFailure(imagePath)
			return nil, fmt.Errorf("failed to save uploaded image: %w", err)
		}
	}

	id := int32(input.ProductID)
	if id <= 0 {
		return nil, fmt.Errorf("invalid product ID")
	}

	req := &pb.UpdateProductRequest{
		ProductId:    id,
		MerchantId:   int32(input.MerchantID),
		CategoryId:   int32(input.CategoryID),
		Name:         *input.Name,
		Description:  *input.Description,
		Price:        int32(*input.Price),
		CountInStock: int32(*input.CountInStock),
		Brand:        *input.Brand,
		Weight:       int32(*input.Weight),
	}

	if imagePath != "" {
		req.ImageProduct = imagePath
	}

	product, err := r.ProductGraphql.ProductClient.Update(ctx, req)
	if err != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.ProductGraphql.Mapping.ToGraphqlResponseProduct(product)
	return so, nil
}

// TrashedProduct is the resolver for the trashedProduct field.
func (r *mutationResolver) TrashedProduct(ctx context.Context, input model.FindByIDProductInput) (*model.APIResponseProductDeleteAt, error) {
	id := int32(input.ID)

	if id == 0 {
		return nil, product_errors.ErrGraphqlInvalidID
	}

	product, err := r.ProductGraphql.ProductClient.TrashedProduct(ctx, &pb.FindByIdProductRequest{
		Id: id,
	})
	if err != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.ProductGraphql.Mapping.ToGraphqlResponseProductDeleteAt(
		product,
	)

	return so, nil
}

// RestoreProduct is the resolver for the restoreProduct field.
func (r *mutationResolver) RestoreProduct(ctx context.Context, input model.FindByIDProductInput) (*model.APIResponseProductDeleteAt, error) {
	id := int32(input.ID)

	if id == 0 {
		return nil, product_errors.ErrGraphqlInvalidID
	}

	product, err := r.ProductGraphql.ProductClient.RestoreProduct(ctx, &pb.FindByIdProductRequest{
		Id: id,
	})
	if err != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.ProductGraphql.Mapping.ToGraphqlResponseProductDeleteAt(
		product,
	)

	return so, nil
}

// DeleteProductPermanent is the resolver for the deleteProductPermanent field.
func (r *mutationResolver) DeleteProductPermanent(ctx context.Context, input model.FindByIDProductInput) (*model.APIResponseProductDelete, error) {
	id := int32(input.ID)

	if id == 0 {
		return nil, product_errors.ErrGraphqlInvalidID
	}

	res, err := r.ProductGraphql.ProductClient.DeleteProductPermanent(ctx, &pb.FindByIdProductRequest{
		Id: id,
	})

	if err != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.ProductGraphql.Mapping.ToGraphqlResponseProductDelete(res)

	return so, nil
}

// RestoreAllProduct is the resolver for the restoreAllProduct field.
func (r *mutationResolver) RestoreAllProduct(ctx context.Context) (*model.APIResponseProductAll, error) {
	res, err := r.ProductGraphql.ProductClient.RestoreAllProduct(ctx, &emptypb.Empty{})

	if err != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.ProductGraphql.Mapping.ToGraphqlResponseProductAll(res)

	return so, nil
}

// DeleteAllProductPermanent is the resolver for the deleteAllProductPermanent field.
func (r *mutationResolver) DeleteAllProductPermanent(ctx context.Context) (*model.APIResponseProductAll, error) {
	res, err := r.ProductGraphql.ProductClient.DeleteAllProductPermanent(ctx, &emptypb.Empty{})

	if err != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.ProductGraphql.Mapping.ToGraphqlResponseProductAll(res)

	return so, nil
}

// FindAllProduct is the resolver for the findAllProduct field.
func (r *queryResolver) FindAllProduct(ctx context.Context, input *model.FindAllProductInput) (*model.APIResponsePaginationProduct, error) {
	page := int32(*input.Page)
	pageSize := int32(*input.PageSize)
	search := input.Search

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	req := &pb.FindAllProductRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   *search,
	}

	products, err := r.ProductGraphql.ProductClient.FindAll(ctx, req)
	if err != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.ProductGraphql.Mapping.ToGraphqlResponsePaginationProduct(products)

	return so, nil
}

// FindByMerchantProduct is the resolver for the findByMerchantProduct field.
func (r *queryResolver) FindByMerchantProduct(ctx context.Context, input model.FindAllProductMerchantInput) (*model.APIResponsePaginationProduct, error) {
	page := int32(*input.Page)
	pageSize := int32(*input.PageSize)
	search := input.Search
	merchantId := int32(input.MerchantID)
	min_price := int32(*input.MinPrice)
	max_price := int32(*input.MaxPrice)

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	if min_price <= 0 {
		min_price = 0
	}

	if max_price <= 0 {
		max_price = 0
	}

	req := &pb.FindAllProductMerchantRequest{
		Page:       page,
		PageSize:   pageSize,
		Search:     *search,
		MinPrice:   min_price,
		MaxPrice:   max_price,
		MerchantId: merchantId,
	}

	products, err := r.ProductGraphql.ProductClient.FindByMerchant(ctx, req)
	if err != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.ProductGraphql.Mapping.ToGraphqlResponsePaginationProduct(products)

	return so, nil
}

// FindByCategoryProduct is the resolver for the findByCategoryProduct field.
func (r *queryResolver) FindByCategoryProduct(ctx context.Context, input model.FindAllProductCategoryInput) (*model.APIResponsePaginationProduct, error) {
	page := int32(*input.Page)
	pageSize := int32(*input.PageSize)
	search := input.Search
	categoryName := input.CategoryName
	min_price := int32(*input.MinPrice)
	max_price := int32(*input.MaxPrice)

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	if min_price <= 0 {
		min_price = 0
	}

	if max_price <= 0 {
		max_price = 0
	}

	req := &pb.FindAllProductCategoryRequest{
		Page:         page,
		PageSize:     pageSize,
		Search:       *search,
		Minprice:     min_price,
		Maxprice:     max_price,
		CategoryName: *categoryName,
	}

	products, err := r.ProductGraphql.ProductClient.FindByCategory(ctx, req)
	if err != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.ProductGraphql.Mapping.ToGraphqlResponsePaginationProduct(products)

	return so, nil
}

// FindByIDProduct is the resolver for the findByIdProduct field.
func (r *queryResolver) FindByIDProduct(ctx context.Context, input model.FindByIDProductInput) (*model.APIResponseProduct, error) {
	id := int32(input.ID)

	if id <= 0 {
		return nil, product_errors.ErrGraphqlInvalidID
	}

	res, err := r.ProductGraphql.ProductClient.FindById(ctx, &pb.FindByIdProductRequest{Id: id})

	if err != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.ProductGraphql.Mapping.ToGraphqlResponseProduct(res)

	return so, nil
}

// FindByActiveProduct is the resolver for the findByActiveProduct field.
func (r *queryResolver) FindByActiveProduct(ctx context.Context, input *model.FindAllProductInput) (*model.APIResponsePaginationProductDeleteAt, error) {
	page := int32(*input.Page)
	pageSize := int32(*input.PageSize)
	search := input.Search

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	req := &pb.FindAllProductRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   *search,
	}

	products, err := r.ProductGraphql.ProductClient.FindByActive(ctx, req)
	if err != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.ProductGraphql.Mapping.ToGraphqlResponsePaginationProductDeleteAt(products)

	return so, nil
}

// FindByTrashedProduct is the resolver for the findByTrashedProduct field.
func (r *queryResolver) FindByTrashedProduct(ctx context.Context, input *model.FindAllProductInput) (*model.APIResponsePaginationProductDeleteAt, error) {
	page := int32(*input.Page)
	pageSize := int32(*input.PageSize)
	search := input.Search

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	req := &pb.FindAllProductRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   *search,
	}

	products, err := r.ProductGraphql.ProductClient.FindByTrashed(ctx, req)
	if err != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(err)
	}

	so := r.ProductGraphql.Mapping.ToGraphqlResponsePaginationProductDeleteAt(products)

	return so, nil
}
