package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"time"

	"github.com/MamangRust/pointofsale-graphql-grpc/internal/domain/requests"
	"github.com/MamangRust/pointofsale-graphql-grpc/internal/model"
	"github.com/MamangRust/pointofsale-graphql-grpc/internal/pb"
	"github.com/MamangRust/pointofsale-graphql-grpc/pkg/errors"
	"google.golang.org/protobuf/types/known/emptypb"
)

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.CreateProductInput) (*model.APIResponseProduct, error) {
	return ResolverHandle(r.ResolverHandle, "CreateProduct", ctx, func(ctx context.Context) (*model.APIResponseProduct, error) {
		var imagePath string

		if input.Image.Filename != "" && input.Image.ContentType != "" {
			upload := input.Image.File
			ext := filepath.Ext(input.Image.Filename)
			filename := fmt.Sprintf("%d%s", time.Now().UnixNano(), ext)
			imagePath = filepath.Join("uploads/products", filename)

			if err := r.ProductGraphql.ImageUpload.EnsureUploadDirectory("uploads/products"); err != nil {
				return nil, r.handleGraphQLError(err, "CreateProduct")
			}

			out, err := os.Create(imagePath)
			if err != nil {
				return nil, r.handleGraphQLError(err, "CreateProduct")
			}
			defer out.Close()

			if _, err := io.Copy(out, upload); err != nil {
				r.ProductGraphql.ImageUpload.CleanupImageOnFailure(imagePath)
				return nil, r.handleGraphQLError(err, "CreateProduct")
			}
		}

		req := &requests.CreateProductRequest{
			MerchantID:   int(input.MerchantID),
			CategoryID:   int(input.CategoryID),
			Name:         input.Name,
			Description:  *input.Description,
			Price:        int(input.Price),
			CountInStock: int(input.CountInStock),
			Brand:        *input.Brand,
			Weight:       int(*input.Weight),
			ImageProduct: imagePath,
		}

		if err := req.Validate(); err != nil {
			validations := r.parseValidationErrors(err)
			return nil, errors.NewValidationError(validations)
		}

		reqPb := &pb.CreateProductRequest{
			MerchantId:   int32(req.MerchantID),
			CategoryId:   int32(req.CategoryID),
			Name:         req.Name,
			Description:  req.Description,
			Price:        int32(req.Price),
			CountInStock: int32(req.CountInStock),
			Brand:        req.Brand,
			Weight:       int32(req.Weight),
			ImageProduct: req.ImageProduct,
		}

		product, err := r.ProductGraphql.ProductClient.Create(ctx, reqPb)
		if err != nil {
			return nil, r.handleGraphQLError(err, "CreateProduct")
		}

		so := r.ProductGraphql.Mapping.ToGraphqlResponseProduct(product)

		r.ProductGraphql.Cache.DeleteCachedProduct(ctx, int(so.Data.ID))

		return so, nil
	})
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, input model.UpdateProductInput) (*model.APIResponseProduct, error) {
	return ResolverHandle(r.ResolverHandle, "UpdateProduct", ctx, func(ctx context.Context) (*model.APIResponseProduct, error) {
		id := int(input.ProductID)

		if id <= 0 {
			return nil, errors.NewBadRequestError("id is required")
		}

		var imagePath string

		if input.Image != nil && input.Image.Filename != "" {
			upload := input.Image.File
			ext := filepath.Ext(input.Image.Filename)
			filename := fmt.Sprintf("%d%s", time.Now().UnixNano(), ext)
			imagePath = filepath.Join("uploads/products", filename)

			if err := r.ProductGraphql.ImageUpload.EnsureUploadDirectory("uploads/products"); err != nil {
				return nil, r.handleGraphQLError(err, "UpdateProduct")
			}

			out, err := os.Create(imagePath)
			if err != nil {
				return nil, r.handleGraphQLError(err, "UpdateProduct")
			}
			defer out.Close()

			if _, err := io.Copy(out, upload); err != nil {
				r.ProductGraphql.ImageUpload.CleanupImageOnFailure(imagePath)
				return nil, r.handleGraphQLError(err, "UpdateProduct")
			}
		}

		// 1. Mapping Input ke Internal Request
		req := &requests.UpdateProductRequest{
			ProductID:    &id,
			MerchantID:   int(input.MerchantID),
			CategoryID:   int(input.CategoryID),
			Name:         *input.Name,
			Description:  *input.Description,
			Price:        int(*input.Price),
			CountInStock: int(*input.CountInStock),
			Brand:        *input.Brand,
			Weight:       int(*input.Weight),
		}
		if imagePath != "" {
			req.ImageProduct = imagePath
		}

		if err := req.Validate(); err != nil {
			validations := r.parseValidationErrors(err)
			return nil, errors.NewValidationError(validations)
		}

		reqPb := &pb.UpdateProductRequest{
			ProductId:    int32(id),
			MerchantId:   int32(req.MerchantID),
			CategoryId:   int32(req.CategoryID),
			Name:         req.Name,
			Description:  req.Description,
			Price:        int32(req.Price),
			CountInStock: int32(req.CountInStock),
			Brand:        req.Brand,
			Weight:       int32(req.Weight),
			ImageProduct: req.ImageProduct,
		}

		product, err := r.ProductGraphql.ProductClient.Update(ctx, reqPb)
		if err != nil {
			return nil, r.handleGraphQLError(err, "UpdateProduct")
		}

		so := r.ProductGraphql.Mapping.ToGraphqlResponseProduct(product)

		r.ProductGraphql.Cache.DeleteCachedProduct(ctx, id)

		return so, nil
	})
}

// TrashedProduct is the resolver for the trashedProduct field.
func (r *mutationResolver) TrashedProduct(ctx context.Context, input model.FindByIDProductInput) (*model.APIResponseProductDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "TrashedProduct", ctx, func(ctx context.Context) (*model.APIResponseProductDeleteAt, error) {
		id := int(input.ID)

		if id <= 0 {
			return nil, errors.NewBadRequestError("id is required")
		}

		reqPb := &pb.FindByIdProductRequest{
			Id: int32(id),
		}

		product, err := r.ProductGraphql.ProductClient.TrashedProduct(ctx, reqPb)
		if err != nil {
			return nil, r.handleGraphQLError(err, "TrashedProduct")
		}

		so := r.ProductGraphql.Mapping.ToGraphqlResponseProductDeleteAt(product)

		r.ProductGraphql.Cache.DeleteCachedProduct(ctx, id)

		return so, nil
	})
}

// RestoreProduct is the resolver for the restoreProduct field.
func (r *mutationResolver) RestoreProduct(ctx context.Context, input model.FindByIDProductInput) (*model.APIResponseProductDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "RestoreProduct", ctx, func(ctx context.Context) (*model.APIResponseProductDeleteAt, error) {
		id := int(input.ID)

		if id <= 0 {
			return nil, errors.NewBadRequestError("id is required")
		}

		reqPb := &pb.FindByIdProductRequest{
			Id: int32(id),
		}

		product, err := r.ProductGraphql.ProductClient.RestoreProduct(ctx, reqPb)
		if err != nil {
			return nil, r.handleGraphQLError(err, "RestoreProduct")
		}

		so := r.ProductGraphql.Mapping.ToGraphqlResponseProductDeleteAt(product)

		r.ProductGraphql.Cache.DeleteCachedProduct(ctx, id)

		return so, nil
	})
}

// DeleteProductPermanent is the resolver for the deleteProductPermanent field.
func (r *mutationResolver) DeleteProductPermanent(ctx context.Context, input model.FindByIDProductInput) (*model.APIResponseProductDelete, error) {
	return ResolverHandle(r.ResolverHandle, "DeleteProductPermanent", ctx, func(ctx context.Context) (*model.APIResponseProductDelete, error) {
		id := int(input.ID)

		if id <= 0 {
			return nil, errors.NewBadRequestError("id is required")
		}

		reqPb := &pb.FindByIdProductRequest{
			Id: int32(id),
		}

		res, err := r.ProductGraphql.ProductClient.DeleteProductPermanent(ctx, reqPb)
		if err != nil {
			return nil, r.handleGraphQLError(err, "DeleteProductPermanent")
		}

		so := r.ProductGraphql.Mapping.ToGraphqlResponseProductDelete(res)

		r.ProductGraphql.Cache.DeleteCachedProduct(ctx, id)

		return so, nil
	})
}

// RestoreAllProduct is the resolver for the restoreAllProduct field.
func (r *mutationResolver) RestoreAllProduct(ctx context.Context) (*model.APIResponseProductAll, error) {
	return ResolverHandle(r.ResolverHandle, "RestoreAllProduct", ctx, func(ctx context.Context) (*model.APIResponseProductAll, error) {
		res, err := r.ProductGraphql.ProductClient.RestoreAllProduct(ctx, &emptypb.Empty{})
		if err != nil {
			return nil, r.handleGraphQLError(err, "RestoreAllProduct")
		}

		so := r.ProductGraphql.Mapping.ToGraphqlResponseProductAll(res)

		return so, nil
	})
}

// DeleteAllProductPermanent is the resolver for the deleteAllProductPermanent field.
func (r *mutationResolver) DeleteAllProductPermanent(ctx context.Context) (*model.APIResponseProductAll, error) {
	return ResolverHandle(r.ResolverHandle, "DeleteAllProductPermanent", ctx, func(ctx context.Context) (*model.APIResponseProductAll, error) {
		res, err := r.ProductGraphql.ProductClient.DeleteAllProductPermanent(ctx, &emptypb.Empty{})
		if err != nil {
			return nil, r.handleGraphQLError(err, "DeleteAllProductPermanent")
		}

		so := r.ProductGraphql.Mapping.ToGraphqlResponseProductAll(res)

		return so, nil
	})
}

// FindAllProduct is the resolver for the findAllProduct field.
func (r *queryResolver) FindAllProduct(ctx context.Context, input *model.FindAllProductInput) (*model.APIResponsePaginationProduct, error) {
	return ResolverHandle(r.ResolverHandle, "FindAllProduct", ctx, func(ctx context.Context) (*model.APIResponsePaginationProduct, error) {
		page := int32(*input.Page)
		pageSize := int32(*input.PageSize)
		if page <= 0 {
			page = 1
		}
		if pageSize <= 0 {
			pageSize = 10
		}

		normalizedInput := &model.FindAllProductInput{
			Page:     &page,
			PageSize: &pageSize,
			Search:   input.Search,
		}

		if cached, found := r.ProductGraphql.Cache.GetCachedProducts(ctx, normalizedInput); found {
			return cached, nil
		}

		req := &pb.FindAllProductRequest{
			Page:     int32(page),
			PageSize: int32(pageSize),
			Search:   *input.Search,
		}
		products, err := r.ProductGraphql.ProductClient.FindAll(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindAllProduct")
		}

		so := r.ProductGraphql.Mapping.ToGraphqlResponsePaginationProduct(products)

		r.ProductGraphql.Cache.SetCachedProducts(ctx, normalizedInput, so)

		return so, nil
	})
}

// FindByMerchantProduct is the resolver for the findByMerchantProduct field.
func (r *queryResolver) FindByMerchantProduct(ctx context.Context, input model.FindAllProductMerchantInput) (*model.APIResponsePaginationProduct, error) {
	return ResolverHandle(r.ResolverHandle, "FindByMerchantProduct", ctx, func(ctx context.Context) (*model.APIResponsePaginationProduct, error) {
		page := int32(*input.Page)
		pageSize := int32(*input.PageSize)
		min_price := int32(*input.MinPrice)
		max_price := int32(*input.MaxPrice)

		if page <= 0 {
			page = 1
		}
		if pageSize <= 0 {
			pageSize = 10
		}

		if min_price <= 0 {
			min_price = 0
		}
		if max_price <= 0 {
			max_price = 0
		}

		normalizedInput := &model.FindAllProductMerchantInput{
			Page:       &page,
			PageSize:   &pageSize,
			Search:     input.Search,
			MinPrice:   &min_price,
			MaxPrice:   &max_price,
			MerchantID: input.MerchantID,
		}

		if cached, found := r.ProductGraphql.Cache.GetCachedProductsByMerchant(ctx, normalizedInput); found {
			return cached, nil
		}

		req := &pb.FindAllProductMerchantRequest{
			Page:       int32(page),
			PageSize:   int32(pageSize),
			Search:     *input.Search,
			MinPrice:   int32(min_price),
			MaxPrice:   int32(max_price),
			MerchantId: int32(input.MerchantID),
		}
		products, err := r.ProductGraphql.ProductClient.FindByMerchant(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindByMerchantProduct")
		}

		so := r.ProductGraphql.Mapping.ToGraphqlResponsePaginationProduct(products)

		r.ProductGraphql.Cache.SetCachedProductsByMerchant(ctx, normalizedInput, so)

		return so, nil
	})
}

// FindByCategoryProduct is the resolver for the findByCategoryProduct field.
func (r *queryResolver) FindByCategoryProduct(ctx context.Context, input model.FindAllProductCategoryInput) (*model.APIResponsePaginationProduct, error) {
	return ResolverHandle(r.ResolverHandle, "FindByCategoryProduct", ctx, func(ctx context.Context) (*model.APIResponsePaginationProduct, error) {
		page := int32(*input.Page)
		pageSize := int32(*input.PageSize)
		min_price := int32(*input.MinPrice)
		max_price := int32(*input.MaxPrice)

		if page <= 0 {
			page = 1
		}
		if pageSize <= 0 {
			pageSize = 10
		}

		if min_price <= 0 {
			min_price = 0
		}
		if max_price <= 0 {
			max_price = 0
		}

		normalizedInput := &model.FindAllProductCategoryInput{
			Page:         &page,
			PageSize:     &pageSize,
			Search:       input.Search,
			MinPrice:     &min_price,
			MaxPrice:     &max_price,
			CategoryName: input.CategoryName,
		}

		if cached, found := r.ProductGraphql.Cache.GetCachedProductsByCategory(ctx, normalizedInput); found {
			return cached, nil
		}

		req := &pb.FindAllProductCategoryRequest{
			Page:         int32(page),
			PageSize:     int32(pageSize),
			Search:       *input.Search,
			Minprice:     int32(min_price),
			Maxprice:     int32(max_price),
			CategoryName: *input.CategoryName,
		}
		products, err := r.ProductGraphql.ProductClient.FindByCategory(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindByCategoryProduct")
		}

		so := r.ProductGraphql.Mapping.ToGraphqlResponsePaginationProduct(products)

		r.ProductGraphql.Cache.SetCachedProductsByCategory(ctx, normalizedInput, so)

		return so, nil
	})
}

// FindByIDProduct is the resolver for the findByIdProduct field.
func (r *queryResolver) FindByIDProduct(ctx context.Context, input model.FindByIDProductInput) (*model.APIResponseProduct, error) {
	return ResolverHandle(r.ResolverHandle, "FindByIDProduct", ctx, func(ctx context.Context) (*model.APIResponseProduct, error) {
		id := int(input.ID)

		if id <= 0 {
			return nil, errors.NewBadRequestError("id is required")
		}

		if cached, found := r.ProductGraphql.Cache.GetCachedProduct(ctx, id); found {
			return cached, nil
		}

		res, err := r.ProductGraphql.ProductClient.FindById(ctx, &pb.FindByIdProductRequest{Id: int32(id)})
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindByIDProduct")
		}

		so := r.ProductGraphql.Mapping.ToGraphqlResponseProduct(res)

		r.ProductGraphql.Cache.SetCachedProduct(ctx, so)

		return so, nil
	})
}

// FindByActiveProduct is the resolver for the findByActiveProduct field.
func (r *queryResolver) FindByActiveProduct(ctx context.Context, input *model.FindAllProductInput) (*model.APIResponsePaginationProductDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "FindByActiveProduct", ctx, func(ctx context.Context) (*model.APIResponsePaginationProductDeleteAt, error) {
		page := int32(*input.Page)
		pageSize := int32(*input.PageSize)
		if page <= 0 {
			page = 1
		}
		if pageSize <= 0 {
			pageSize = 10
		}

		normalizedInput := &model.FindAllProductInput{
			Page:     &page,
			PageSize: &pageSize,
			Search:   input.Search,
		}

		if cached, found := r.ProductGraphql.Cache.GetCachedProductActive(ctx, normalizedInput); found {
			return cached, nil
		}

		req := &pb.FindAllProductRequest{
			Page:     int32(page),
			PageSize: int32(pageSize),
			Search:   *input.Search,
		}
		products, err := r.ProductGraphql.ProductClient.FindByActive(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindByActiveProduct")
		}

		so := r.ProductGraphql.Mapping.ToGraphqlResponsePaginationProductDeleteAt(products)

		r.ProductGraphql.Cache.SetCachedProductActive(ctx, normalizedInput, so)

		return so, nil
	})
}

// FindByTrashedProduct is the resolver for the findByTrashedProduct field.
func (r *queryResolver) FindByTrashedProduct(ctx context.Context, input *model.FindAllProductInput) (*model.APIResponsePaginationProductDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "FindByTrashedProduct", ctx, func(ctx context.Context) (*model.APIResponsePaginationProductDeleteAt, error) {
		page := int32(*input.Page)
		pageSize := int32(*input.PageSize)
		if page <= 0 {
			page = 1
		}
		if pageSize <= 0 {
			pageSize = 10
		}

		normalizedInput := &model.FindAllProductInput{
			Page:     &page,
			PageSize: &pageSize,
			Search:   input.Search,
		}

		if cached, found := r.ProductGraphql.Cache.GetCachedProductTrashed(ctx, normalizedInput); found {
			return cached, nil
		}

		req := &pb.FindAllProductRequest{
			Page:     int32(page),
			PageSize: int32(pageSize),
			Search:   *input.Search,
		}
		products, err := r.ProductGraphql.ProductClient.FindByTrashed(ctx, req)
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindByTrashedProduct")
		}

		so := r.ProductGraphql.Mapping.ToGraphqlResponsePaginationProductDeleteAt(products)

		r.ProductGraphql.Cache.SetCachedProductTrashed(ctx, normalizedInput, so)

		return so, nil
	})
}
