package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	"github.com/MamangRust/pointofsale-graphql-grpc/internal/domain/response"
	"github.com/MamangRust/pointofsale-graphql-grpc/internal/model"
	"github.com/MamangRust/pointofsale-graphql-grpc/internal/pb"
	"github.com/MamangRust/pointofsale-graphql-grpc/pkg/errors/user_errors"
	"google.golang.org/protobuf/types/known/emptypb"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.APIResponseUserResponse, error) {
	req := &pb.CreateUserRequest{
		Firstname:       input.Firstname,
		Lastname:        input.Lastname,
		Email:           input.Email,
		Password:        input.Password,
		ConfirmPassword: input.ConfirmPassword,
	}

	user, errResp := r.UserGraphql.UserClient.Create(ctx, req)
	if errResp != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.UserGraphql.Mapping.ToGraphqlResponseUser(user)

	return so, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input model.UpdateUserInput) (*model.APIResponseUserResponse, error) {
	id := int32(input.ID)
	if id == 0 {
		return nil, fmt.Errorf("invalid user ID")
	}

	req := &pb.UpdateUserRequest{
		Id:              id,
		Firstname:       *input.Firstname,
		Lastname:        *input.Lastname,
		Email:           *input.Email,
		Password:        *input.Password,
		ConfirmPassword: *input.ConfirmPassword,
	}

	user, errResp := r.UserGraphql.UserClient.Update(ctx, req)
	if errResp != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.UserGraphql.Mapping.ToGraphqlResponseUser(user)

	return so, nil
}

// TrashedUser is the resolver for the trashedUser field.
func (r *mutationResolver) TrashedUser(ctx context.Context, input model.FindByIDUserInput) (*model.APIResponseUserResponseDeleteAt, error) {
	id := int32(input.ID)
	if id == 0 {
		return nil, user_errors.ErrGraphqlUserInvalidId
	}

	user, errResp := r.UserGraphql.UserClient.TrashedUser(ctx, &pb.FindByIdUserRequest{Id: id})
	if errResp != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.UserGraphql.Mapping.ToGraphqlResponseUserDeleteAt(user)

	return so, nil
}

// RestoreUser is the resolver for the restoreUser field.
func (r *mutationResolver) RestoreUser(ctx context.Context, input model.FindByIDUserInput) (*model.APIResponseUserResponseDeleteAt, error) {
	id := int32(input.ID)
	if id == 0 {
		return nil, user_errors.ErrGraphqlUserInvalidId
	}

	user, errResp := r.UserGraphql.UserClient.RestoreUser(ctx, &pb.FindByIdUserRequest{Id: id})
	if errResp != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.UserGraphql.Mapping.ToGraphqlResponseUserDeleteAt(user)

	return so, nil
}

// DeleteUserPermanent is the resolver for the deleteUserPermanent field.
func (r *mutationResolver) DeleteUserPermanent(ctx context.Context, input model.FindByIDUserInput) (*model.APIResponseUserDelete, error) {
	id := int32(input.ID)
	if id == 0 {
		return nil, user_errors.ErrGraphqlUserInvalidId
	}

	res, errResp := r.UserGraphql.UserClient.DeleteUserPermanent(ctx, &pb.FindByIdUserRequest{Id: id})
	if errResp != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.UserGraphql.Mapping.ToGraphqlResponseUserDelete(res)

	return so, nil
}

// RestoreAllUser is the resolver for the restoreAllUser field.
func (r *mutationResolver) RestoreAllUser(ctx context.Context) (*model.APIResponseUserAll, error) {
	res, errResp := r.UserGraphql.UserClient.RestoreAllUser(ctx, &emptypb.Empty{})
	if errResp != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.UserGraphql.Mapping.ToGraphqlResponseUserAll(res)

	return so, nil
}

// DeleteAllUserPermanent is the resolver for the deleteAllUserPermanent field.
func (r *mutationResolver) DeleteAllUserPermanent(ctx context.Context) (*model.APIResponseUserAll, error) {
	res, errResp := r.UserGraphql.UserClient.RestoreAllUser(ctx, &emptypb.Empty{})
	if errResp != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.UserGraphql.Mapping.ToGraphqlResponseUserAll(res)

	return so, nil
}

// FindAllUsers is the resolver for the findAllUsers field.
func (r *queryResolver) FindAllUsers(ctx context.Context, input *model.FindAllUserInput) (*model.APIResponsePaginationUser, error) {
	page := int32(*input.Page)
	pageSize := int32(*input.PageSize)
	search := input.Search

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	reqService := &pb.FindAllUserRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   *search,
	}

	users, errResp := r.UserGraphql.UserClient.FindAll(ctx, reqService)
	if errResp != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.UserGraphql.Mapping.ToGraphqlResponsePaginationUser(users)

	return so, nil
}

// FindByIDUser is the resolver for the findByIdUser field.
func (r *queryResolver) FindByIDUser(ctx context.Context, input model.FindByIDUserInput) (*model.APIResponseUserResponse, error) {
	id := int32(input.ID)
	if id == 0 {
		return nil, fmt.Errorf("invalid user ID")
	}

	user, errResp := r.UserGraphql.UserClient.FindById(ctx, &pb.FindByIdUserRequest{
		Id: id,
	})
	if errResp != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.UserGraphql.Mapping.ToGraphqlResponseUser(user)

	return so, nil
}

// FindByActiveUsers is the resolver for the findByActiveUsers field.
func (r *queryResolver) FindByActiveUsers(ctx context.Context, input *model.FindAllUserInput) (*model.APIResponsePaginationUserDeleteAt, error) {
	page := int32(*input.Page)
	pageSize := int32(*input.PageSize)
	search := input.Search

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	reqService := &pb.FindAllUserRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   *search,
	}

	users, errResp := r.UserGraphql.UserClient.FindByActive(ctx, reqService)
	if errResp != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.UserGraphql.Mapping.ToGraphqlResponsePaginationUserDeleteAt(users)

	return so, nil
}

// FindByTrashedUsers is the resolver for the findByTrashedUsers field.
func (r *queryResolver) FindByTrashedUsers(ctx context.Context, input *model.FindAllUserInput) (*model.APIResponsePaginationUserDeleteAt, error) {
	page := int32(*input.Page)
	pageSize := int32(*input.PageSize)
	search := input.Search

	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 10
	}

	reqService := &pb.FindAllUserRequest{
		Page:     page,
		PageSize: pageSize,
		Search:   *search,
	}

	users, errResp := r.UserGraphql.UserClient.FindByTrashed(ctx, reqService)
	if errResp != nil {
		return nil, response.ToGraphqlErrorFromErrorResponse(errResp)
	}

	so := r.UserGraphql.Mapping.ToGraphqlResponsePaginationUserDeleteAt(users)

	return so, nil
}
