// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: cashier.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAllCashierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllCashierRequest) Reset() {
	*x = FindAllCashierRequest{}
	mi := &file_cashier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllCashierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllCashierRequest) ProtoMessage() {}

func (x *FindAllCashierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllCashierRequest.ProtoReflect.Descriptor instead.
func (*FindAllCashierRequest) Descriptor() ([]byte, []int) {
	return file_cashier_proto_rawDescGZIP(), []int{0}
}

func (x *FindAllCashierRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllCashierRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllCashierRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type FindByMerchantCashierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    int32                  `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByMerchantCashierRequest) Reset() {
	*x = FindByMerchantCashierRequest{}
	mi := &file_cashier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByMerchantCashierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByMerchantCashierRequest) ProtoMessage() {}

func (x *FindByMerchantCashierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByMerchantCashierRequest.ProtoReflect.Descriptor instead.
func (*FindByMerchantCashierRequest) Descriptor() ([]byte, []int) {
	return file_cashier_proto_rawDescGZIP(), []int{1}
}

func (x *FindByMerchantCashierRequest) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *FindByMerchantCashierRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindByMerchantCashierRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindByMerchantCashierRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type FindByIdCashierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdCashierRequest) Reset() {
	*x = FindByIdCashierRequest{}
	mi := &file_cashier_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdCashierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdCashierRequest) ProtoMessage() {}

func (x *FindByIdCashierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdCashierRequest.ProtoReflect.Descriptor instead.
func (*FindByIdCashierRequest) Descriptor() ([]byte, []int) {
	return file_cashier_proto_rawDescGZIP(), []int{2}
}

func (x *FindByIdCashierRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FindYearCashier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearCashier) Reset() {
	*x = FindYearCashier{}
	mi := &file_cashier_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearCashier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearCashier) ProtoMessage() {}

func (x *FindYearCashier) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearCashier.ProtoReflect.Descriptor instead.
func (*FindYearCashier) Descriptor() ([]byte, []int) {
	return file_cashier_proto_rawDescGZIP(), []int{3}
}

func (x *FindYearCashier) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type FindYearCashierByMerchant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    int32                  `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearCashierByMerchant) Reset() {
	*x = FindYearCashierByMerchant{}
	mi := &file_cashier_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearCashierByMerchant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearCashierByMerchant) ProtoMessage() {}

func (x *FindYearCashierByMerchant) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearCashierByMerchant.ProtoReflect.Descriptor instead.
func (*FindYearCashierByMerchant) Descriptor() ([]byte, []int) {
	return file_cashier_proto_rawDescGZIP(), []int{4}
}

func (x *FindYearCashierByMerchant) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *FindYearCashierByMerchant) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type FindYearCashierById struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CashierId     int32                  `protobuf:"varint,1,opt,name=cashier_id,json=cashierId,proto3" json:"cashier_id,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearCashierById) Reset() {
	*x = FindYearCashierById{}
	mi := &file_cashier_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearCashierById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearCashierById) ProtoMessage() {}

func (x *FindYearCashierById) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearCashierById.ProtoReflect.Descriptor instead.
func (*FindYearCashierById) Descriptor() ([]byte, []int) {
	return file_cashier_proto_rawDescGZIP(), []int{5}
}

func (x *FindYearCashierById) GetCashierId() int32 {
	if x != nil {
		return x.CashierId
	}
	return 0
}

func (x *FindYearCashierById) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type FindYearMonthTotalSales struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearMonthTotalSales) Reset() {
	*x = FindYearMonthTotalSales{}
	mi := &file_cashier_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearMonthTotalSales) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearMonthTotalSales) ProtoMessage() {}

func (x *FindYearMonthTotalSales) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearMonthTotalSales.ProtoReflect.Descriptor instead.
func (*FindYearMonthTotalSales) Descriptor() ([]byte, []int) {
	return file_cashier_proto_rawDescGZIP(), []int{6}
}

func (x *FindYearMonthTotalSales) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *FindYearMonthTotalSales) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

type FindYearTotalSales struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearTotalSales) Reset() {
	*x = FindYearTotalSales{}
	mi := &file_cashier_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearTotalSales) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearTotalSales) ProtoMessage() {}

func (x *FindYearTotalSales) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearTotalSales.ProtoReflect.Descriptor instead.
func (*FindYearTotalSales) Descriptor() ([]byte, []int) {
	return file_cashier_proto_rawDescGZIP(), []int{7}
}

func (x *FindYearTotalSales) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type FindYearMonthTotalSalesById struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	CashierId     int32                  `protobuf:"varint,3,opt,name=cashier_id,json=cashierId,proto3" json:"cashier_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearMonthTotalSalesById) Reset() {
	*x = FindYearMonthTotalSalesById{}
	mi := &file_cashier_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearMonthTotalSalesById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearMonthTotalSalesById) ProtoMessage() {}

func (x *FindYearMonthTotalSalesById) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearMonthTotalSalesById.ProtoReflect.Descriptor instead.
func (*FindYearMonthTotalSalesById) Descriptor() ([]byte, []int) {
	return file_cashier_proto_rawDescGZIP(), []int{8}
}

func (x *FindYearMonthTotalSalesById) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *FindYearMonthTotalSalesById) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *FindYearMonthTotalSalesById) GetCashierId() int32 {
	if x != nil {
		return x.CashierId
	}
	return 0
}

type FindYearTotalSalesById struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	CashierId     int32                  `protobuf:"varint,2,opt,name=cashier_id,json=cashierId,proto3" json:"cashier_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearTotalSalesById) Reset() {
	*x = FindYearTotalSalesById{}
	mi := &file_cashier_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearTotalSalesById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearTotalSalesById) ProtoMessage() {}

func (x *FindYearTotalSalesById) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearTotalSalesById.ProtoReflect.Descriptor instead.
func (*FindYearTotalSalesById) Descriptor() ([]byte, []int) {
	return file_cashier_proto_rawDescGZIP(), []int{9}
}

func (x *FindYearTotalSalesById) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *FindYearTotalSalesById) GetCashierId() int32 {
	if x != nil {
		return x.CashierId
	}
	return 0
}

type FindYearMonthTotalSalesByMerchant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	MerchantId    int32                  `protobuf:"varint,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearMonthTotalSalesByMerchant) Reset() {
	*x = FindYearMonthTotalSalesByMerchant{}
	mi := &file_cashier_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearMonthTotalSalesByMerchant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearMonthTotalSalesByMerchant) ProtoMessage() {}

func (x *FindYearMonthTotalSalesByMerchant) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearMonthTotalSalesByMerchant.ProtoReflect.Descriptor instead.
func (*FindYearMonthTotalSalesByMerchant) Descriptor() ([]byte, []int) {
	return file_cashier_proto_rawDescGZIP(), []int{10}
}

func (x *FindYearMonthTotalSalesByMerchant) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *FindYearMonthTotalSalesByMerchant) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *FindYearMonthTotalSalesByMerchant) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

type FindYearTotalSalesByMerchant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	MerchantId    int32                  `protobuf:"varint,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearTotalSalesByMerchant) Reset() {
	*x = FindYearTotalSalesByMerchant{}
	mi := &file_cashier_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearTotalSalesByMerchant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearTotalSalesByMerchant) ProtoMessage() {}

func (x *FindYearTotalSalesByMerchant) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearTotalSalesByMerchant.ProtoReflect.Descriptor instead.
func (*FindYearTotalSalesByMerchant) Descriptor() ([]byte, []int) {
	return file_cashier_proto_rawDescGZIP(), []int{11}
}

func (x *FindYearTotalSalesByMerchant) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *FindYearTotalSalesByMerchant) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

type CreateCashierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    int32                  `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCashierRequest) Reset() {
	*x = CreateCashierRequest{}
	mi := &file_cashier_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCashierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCashierRequest) ProtoMessage() {}

func (x *CreateCashierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCashierRequest.ProtoReflect.Descriptor instead.
func (*CreateCashierRequest) Descriptor() ([]byte, []int) {
	return file_cashier_proto_rawDescGZIP(), []int{12}
}

func (x *CreateCashierRequest) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *CreateCashierRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateCashierRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateCashierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CashierId     int32                  `protobuf:"varint,1,opt,name=cashier_id,json=cashierId,proto3" json:"cashier_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCashierRequest) Reset() {
	*x = UpdateCashierRequest{}
	mi := &file_cashier_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCashierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCashierRequest) ProtoMessage() {}

func (x *UpdateCashierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCashierRequest.ProtoReflect.Descriptor instead.
func (*UpdateCashierRequest) Descriptor() ([]byte, []int) {
	return file_cashier_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateCashierRequest) GetCashierId() int32 {
	if x != nil {
		return x.CashierId
	}
	return 0
}

func (x *UpdateCashierRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CashierResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MerchantId    int32                  `protobuf:"varint,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CashierResponse) Reset() {
	*x = CashierResponse{}
	mi := &file_cashier_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CashierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashierResponse) ProtoMessage() {}

func (x *CashierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashierResponse.ProtoReflect.Descriptor instead.
func (*CashierResponse) Descriptor() ([]byte, []int) {
	return file_cashier_proto_rawDescGZIP(), []int{14}
}

func (x *CashierResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CashierResponse) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *CashierResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CashierResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CashierResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CashierResponseDeleteAt struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            int32                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MerchantId    int32                   `protobuf:"varint,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Name          string                  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     string                  `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                  `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CashierResponseDeleteAt) Reset() {
	*x = CashierResponseDeleteAt{}
	mi := &file_cashier_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CashierResponseDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashierResponseDeleteAt) ProtoMessage() {}

func (x *CashierResponseDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashierResponseDeleteAt.ProtoReflect.Descriptor instead.
func (*CashierResponseDeleteAt) Descriptor() ([]byte, []int) {
	return file_cashier_proto_rawDescGZIP(), []int{15}
}

func (x *CashierResponseDeleteAt) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CashierResponseDeleteAt) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *CashierResponseDeleteAt) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CashierResponseDeleteAt) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CashierResponseDeleteAt) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *CashierResponseDeleteAt) GetDeletedAt() *wrapperspb.StringValue {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type CashierResponseMonthSales struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Month         string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
	CashierId     int32                  `protobuf:"varint,2,opt,name=cashier_id,json=cashierId,proto3" json:"cashier_id,omitempty"`
	CashierName   string                 `protobuf:"bytes,3,opt,name=cashier_name,json=cashierName,proto3" json:"cashier_name,omitempty"`
	OrderCount    int32                  `protobuf:"varint,4,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	TotalSales    int32                  `protobuf:"varint,5,opt,name=total_sales,json=totalSales,proto3" json:"total_sales,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CashierResponseMonthSales) Reset() {
	*x = CashierResponseMonthSales{}
	mi := &file_cashier_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CashierResponseMonthSales) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashierResponseMonthSales) ProtoMessage() {}

func (x *CashierResponseMonthSales) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashierResponseMonthSales.ProtoReflect.Descriptor instead.
func (*CashierResponseMonthSales) Descriptor() ([]byte, []int) {
	return file_cashier_proto_rawDescGZIP(), []int{16}
}

func (x *CashierResponseMonthSales) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *CashierResponseMonthSales) GetCashierId() int32 {
	if x != nil {
		return x.CashierId
	}
	return 0
}

func (x *CashierResponseMonthSales) GetCashierName() string {
	if x != nil {
		return x.CashierName
	}
	return ""
}

func (x *CashierResponseMonthSales) GetOrderCount() int32 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

func (x *CashierResponseMonthSales) GetTotalSales() int32 {
	if x != nil {
		return x.TotalSales
	}
	return 0
}

type CashierResponseYearSales struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          string                 `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	CashierId     int32                  `protobuf:"varint,2,opt,name=cashier_id,json=cashierId,proto3" json:"cashier_id,omitempty"`
	CashierName   string                 `protobuf:"bytes,3,opt,name=cashier_name,json=cashierName,proto3" json:"cashier_name,omitempty"`
	OrderCount    int32                  `protobuf:"varint,4,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	TotalSales    int32                  `protobuf:"varint,5,opt,name=total_sales,json=totalSales,proto3" json:"total_sales,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CashierResponseYearSales) Reset() {
	*x = CashierResponseYearSales{}
	mi := &file_cashier_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CashierResponseYearSales) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashierResponseYearSales) ProtoMessage() {}

func (x *CashierResponseYearSales) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashierResponseYearSales.ProtoReflect.Descriptor instead.
func (*CashierResponseYearSales) Descriptor() ([]byte, []int) {
	return file_cashier_proto_rawDescGZIP(), []int{17}
}

func (x *CashierResponseYearSales) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *CashierResponseYearSales) GetCashierId() int32 {
	if x != nil {
		return x.CashierId
	}
	return 0
}

func (x *CashierResponseYearSales) GetCashierName() string {
	if x != nil {
		return x.CashierName
	}
	return ""
}

func (x *CashierResponseYearSales) GetOrderCount() int32 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

func (x *CashierResponseYearSales) GetTotalSales() int32 {
	if x != nil {
		return x.TotalSales
	}
	return 0
}

type CashierResponseMonthTotalSales struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          string                 `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         string                 `protobuf:"bytes,2,opt,name=month,proto3" json:"month,omitempty"`
	TotalSales    int32                  `protobuf:"varint,6,opt,name=total_sales,json=totalSales,proto3" json:"total_sales,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CashierResponseMonthTotalSales) Reset() {
	*x = CashierResponseMonthTotalSales{}
	mi := &file_cashier_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CashierResponseMonthTotalSales) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashierResponseMonthTotalSales) ProtoMessage() {}

func (x *CashierResponseMonthTotalSales) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashierResponseMonthTotalSales.ProtoReflect.Descriptor instead.
func (*CashierResponseMonthTotalSales) Descriptor() ([]byte, []int) {
	return file_cashier_proto_rawDescGZIP(), []int{18}
}

func (x *CashierResponseMonthTotalSales) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *CashierResponseMonthTotalSales) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *CashierResponseMonthTotalSales) GetTotalSales() int32 {
	if x != nil {
		return x.TotalSales
	}
	return 0
}

type CashierResponseYearTotalSales struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          string                 `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	TotalSales    int32                  `protobuf:"varint,2,opt,name=total_sales,json=totalSales,proto3" json:"total_sales,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CashierResponseYearTotalSales) Reset() {
	*x = CashierResponseYearTotalSales{}
	mi := &file_cashier_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CashierResponseYearTotalSales) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashierResponseYearTotalSales) ProtoMessage() {}

func (x *CashierResponseYearTotalSales) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashierResponseYearTotalSales.ProtoReflect.Descriptor instead.
func (*CashierResponseYearTotalSales) Descriptor() ([]byte, []int) {
	return file_cashier_proto_rawDescGZIP(), []int{19}
}

func (x *CashierResponseYearTotalSales) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *CashierResponseYearTotalSales) GetTotalSales() int32 {
	if x != nil {
		return x.TotalSales
	}
	return 0
}

type ApiResponseCashierMonthSales struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Status        string                       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*CashierResponseMonthSales `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseCashierMonthSales) Reset() {
	*x = ApiResponseCashierMonthSales{}
	mi := &file_cashier_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseCashierMonthSales) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseCashierMonthSales) ProtoMessage() {}

func (x *ApiResponseCashierMonthSales) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseCashierMonthSales.ProtoReflect.Descriptor instead.
func (*ApiResponseCashierMonthSales) Descriptor() ([]byte, []int) {
	return file_cashier_proto_rawDescGZIP(), []int{20}
}

func (x *ApiResponseCashierMonthSales) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseCashierMonthSales) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseCashierMonthSales) GetData() []*CashierResponseMonthSales {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseCashierYearSales struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Status        string                      `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*CashierResponseYearSales `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseCashierYearSales) Reset() {
	*x = ApiResponseCashierYearSales{}
	mi := &file_cashier_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseCashierYearSales) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseCashierYearSales) ProtoMessage() {}

func (x *ApiResponseCashierYearSales) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseCashierYearSales.ProtoReflect.Descriptor instead.
func (*ApiResponseCashierYearSales) Descriptor() ([]byte, []int) {
	return file_cashier_proto_rawDescGZIP(), []int{21}
}

func (x *ApiResponseCashierYearSales) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseCashierYearSales) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseCashierYearSales) GetData() []*CashierResponseYearSales {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseCashier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *CashierResponse       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseCashier) Reset() {
	*x = ApiResponseCashier{}
	mi := &file_cashier_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseCashier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseCashier) ProtoMessage() {}

func (x *ApiResponseCashier) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseCashier.ProtoReflect.Descriptor instead.
func (*ApiResponseCashier) Descriptor() ([]byte, []int) {
	return file_cashier_proto_rawDescGZIP(), []int{22}
}

func (x *ApiResponseCashier) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseCashier) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseCashier) GetData() *CashierResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseCashierDeleteAt struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Status        string                   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *CashierResponseDeleteAt `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseCashierDeleteAt) Reset() {
	*x = ApiResponseCashierDeleteAt{}
	mi := &file_cashier_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseCashierDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseCashierDeleteAt) ProtoMessage() {}

func (x *ApiResponseCashierDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseCashierDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponseCashierDeleteAt) Descriptor() ([]byte, []int) {
	return file_cashier_proto_rawDescGZIP(), []int{23}
}

func (x *ApiResponseCashierDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseCashierDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseCashierDeleteAt) GetData() *CashierResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponsesCashier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*CashierResponse     `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsesCashier) Reset() {
	*x = ApiResponsesCashier{}
	mi := &file_cashier_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsesCashier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsesCashier) ProtoMessage() {}

func (x *ApiResponsesCashier) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsesCashier.ProtoReflect.Descriptor instead.
func (*ApiResponsesCashier) Descriptor() ([]byte, []int) {
	return file_cashier_proto_rawDescGZIP(), []int{24}
}

func (x *ApiResponsesCashier) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsesCashier) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsesCashier) GetData() []*CashierResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseCashierDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseCashierDelete) Reset() {
	*x = ApiResponseCashierDelete{}
	mi := &file_cashier_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseCashierDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseCashierDelete) ProtoMessage() {}

func (x *ApiResponseCashierDelete) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseCashierDelete.ProtoReflect.Descriptor instead.
func (*ApiResponseCashierDelete) Descriptor() ([]byte, []int) {
	return file_cashier_proto_rawDescGZIP(), []int{25}
}

func (x *ApiResponseCashierDelete) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseCashierDelete) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponseCashierAll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseCashierAll) Reset() {
	*x = ApiResponseCashierAll{}
	mi := &file_cashier_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseCashierAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseCashierAll) ProtoMessage() {}

func (x *ApiResponseCashierAll) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseCashierAll.ProtoReflect.Descriptor instead.
func (*ApiResponseCashierAll) Descriptor() ([]byte, []int) {
	return file_cashier_proto_rawDescGZIP(), []int{26}
}

func (x *ApiResponseCashierAll) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseCashierAll) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponsePaginationCashierDeleteAt struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Status        string                     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*CashierResponseDeleteAt `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *PaginationMeta            `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationCashierDeleteAt) Reset() {
	*x = ApiResponsePaginationCashierDeleteAt{}
	mi := &file_cashier_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationCashierDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationCashierDeleteAt) ProtoMessage() {}

func (x *ApiResponsePaginationCashierDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationCashierDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationCashierDeleteAt) Descriptor() ([]byte, []int) {
	return file_cashier_proto_rawDescGZIP(), []int{27}
}

func (x *ApiResponsePaginationCashierDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationCashierDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationCashierDeleteAt) GetData() []*CashierResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationCashierDeleteAt) GetPagination() *PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ApiResponsePaginationCashier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*CashierResponse     `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *PaginationMeta        `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationCashier) Reset() {
	*x = ApiResponsePaginationCashier{}
	mi := &file_cashier_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationCashier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationCashier) ProtoMessage() {}

func (x *ApiResponsePaginationCashier) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationCashier.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationCashier) Descriptor() ([]byte, []int) {
	return file_cashier_proto_rawDescGZIP(), []int{28}
}

func (x *ApiResponsePaginationCashier) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationCashier) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationCashier) GetData() []*CashierResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationCashier) GetPagination() *PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ApiResponseCashierMonthlyTotalSales struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        string                            `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*CashierResponseMonthTotalSales `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseCashierMonthlyTotalSales) Reset() {
	*x = ApiResponseCashierMonthlyTotalSales{}
	mi := &file_cashier_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseCashierMonthlyTotalSales) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseCashierMonthlyTotalSales) ProtoMessage() {}

func (x *ApiResponseCashierMonthlyTotalSales) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseCashierMonthlyTotalSales.ProtoReflect.Descriptor instead.
func (*ApiResponseCashierMonthlyTotalSales) Descriptor() ([]byte, []int) {
	return file_cashier_proto_rawDescGZIP(), []int{29}
}

func (x *ApiResponseCashierMonthlyTotalSales) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseCashierMonthlyTotalSales) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseCashierMonthlyTotalSales) GetData() []*CashierResponseMonthTotalSales {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseCashierYearlyTotalSales struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Status        string                           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*CashierResponseYearTotalSales `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseCashierYearlyTotalSales) Reset() {
	*x = ApiResponseCashierYearlyTotalSales{}
	mi := &file_cashier_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseCashierYearlyTotalSales) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseCashierYearlyTotalSales) ProtoMessage() {}

func (x *ApiResponseCashierYearlyTotalSales) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseCashierYearlyTotalSales.ProtoReflect.Descriptor instead.
func (*ApiResponseCashierYearlyTotalSales) Descriptor() ([]byte, []int) {
	return file_cashier_proto_rawDescGZIP(), []int{30}
}

func (x *ApiResponseCashierYearlyTotalSales) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseCashierYearlyTotalSales) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseCashierYearlyTotalSales) GetData() []*CashierResponseYearTotalSales {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_cashier_proto protoreflect.FileDescriptor

const file_cashier_proto_rawDesc = "" +
	"\n" +
	"\rcashier.proto\x12\x02pb\x1a\tapi.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\"`\n" +
	"\x15FindAllCashierRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"\x88\x01\n" +
	"\x1cFindByMerchantCashierRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\x05R\n" +
	"merchantId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\"(\n" +
	"\x16FindByIdCashierRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"%\n" +
	"\x0fFindYearCashier\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\"P\n" +
	"\x19FindYearCashierByMerchant\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\x05R\n" +
	"merchantId\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\"H\n" +
	"\x13FindYearCashierById\x12\x1d\n" +
	"\n" +
	"cashier_id\x18\x01 \x01(\x05R\tcashierId\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\"C\n" +
	"\x17FindYearMonthTotalSales\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\"(\n" +
	"\x12FindYearTotalSales\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\"f\n" +
	"\x1bFindYearMonthTotalSalesById\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\x12\x1d\n" +
	"\n" +
	"cashier_id\x18\x03 \x01(\x05R\tcashierId\"K\n" +
	"\x16FindYearTotalSalesById\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x1d\n" +
	"\n" +
	"cashier_id\x18\x02 \x01(\x05R\tcashierId\"n\n" +
	"!FindYearMonthTotalSalesByMerchant\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\x05R\n" +
	"merchantId\"S\n" +
	"\x1cFindYearTotalSalesByMerchant\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\x05R\n" +
	"merchantId\"d\n" +
	"\x14CreateCashierRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\x05R\n" +
	"merchantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"I\n" +
	"\x14UpdateCashierRequest\x12\x1d\n" +
	"\n" +
	"cashier_id\x18\x01 \x01(\x05R\tcashierId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x94\x01\n" +
	"\x0fCashierResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\x05R\n" +
	"merchantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\"\xd9\x01\n" +
	"\x17CashierResponseDeleteAt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\x05R\n" +
	"merchantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\x12;\n" +
	"\n" +
	"deleted_at\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\tdeletedAt\"\xb5\x01\n" +
	"\x19CashierResponseMonthSales\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12\x1d\n" +
	"\n" +
	"cashier_id\x18\x02 \x01(\x05R\tcashierId\x12!\n" +
	"\fcashier_name\x18\x03 \x01(\tR\vcashierName\x12\x1f\n" +
	"\vorder_count\x18\x04 \x01(\x05R\n" +
	"orderCount\x12\x1f\n" +
	"\vtotal_sales\x18\x05 \x01(\x05R\n" +
	"totalSales\"\xb2\x01\n" +
	"\x18CashierResponseYearSales\x12\x12\n" +
	"\x04year\x18\x01 \x01(\tR\x04year\x12\x1d\n" +
	"\n" +
	"cashier_id\x18\x02 \x01(\x05R\tcashierId\x12!\n" +
	"\fcashier_name\x18\x03 \x01(\tR\vcashierName\x12\x1f\n" +
	"\vorder_count\x18\x04 \x01(\x05R\n" +
	"orderCount\x12\x1f\n" +
	"\vtotal_sales\x18\x05 \x01(\x05R\n" +
	"totalSales\"k\n" +
	"\x1eCashierResponseMonthTotalSales\x12\x12\n" +
	"\x04year\x18\x01 \x01(\tR\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\tR\x05month\x12\x1f\n" +
	"\vtotal_sales\x18\x06 \x01(\x05R\n" +
	"totalSales\"T\n" +
	"\x1dCashierResponseYearTotalSales\x12\x12\n" +
	"\x04year\x18\x01 \x01(\tR\x04year\x12\x1f\n" +
	"\vtotal_sales\x18\x02 \x01(\x05R\n" +
	"totalSales\"\x83\x01\n" +
	"\x1cApiResponseCashierMonthSales\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\x04data\x18\x03 \x03(\v2\x1d.pb.CashierResponseMonthSalesR\x04data\"\x81\x01\n" +
	"\x1bApiResponseCashierYearSales\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\x04data\x18\x03 \x03(\v2\x1c.pb.CashierResponseYearSalesR\x04data\"o\n" +
	"\x12ApiResponseCashier\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x04data\x18\x03 \x01(\v2\x13.pb.CashierResponseR\x04data\"\x7f\n" +
	"\x1aApiResponseCashierDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\x04data\x18\x03 \x01(\v2\x1b.pb.CashierResponseDeleteAtR\x04data\"p\n" +
	"\x13ApiResponsesCashier\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x04data\x18\x03 \x03(\v2\x13.pb.CashierResponseR\x04data\"L\n" +
	"\x18ApiResponseCashierDelete\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"I\n" +
	"\x15ApiResponseCashierAll\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xbd\x01\n" +
	"$ApiResponsePaginationCashierDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\x04data\x18\x03 \x03(\v2\x1b.pb.CashierResponseDeleteAtR\x04data\x122\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x12.pb.PaginationMetaR\n" +
	"pagination\"\xad\x01\n" +
	"\x1cApiResponsePaginationCashier\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x04data\x18\x03 \x03(\v2\x13.pb.CashierResponseR\x04data\x122\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x12.pb.PaginationMetaR\n" +
	"pagination\"\x8f\x01\n" +
	"#ApiResponseCashierMonthlyTotalSales\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x126\n" +
	"\x04data\x18\x03 \x03(\v2\".pb.CashierResponseMonthTotalSalesR\x04data\"\x8d\x01\n" +
	"\"ApiResponseCashierYearlyTotalSales\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x125\n" +
	"\x04data\x18\x03 \x03(\v2!.pb.CashierResponseYearTotalSalesR\x04data2\x9a\x10\n" +
	"\x0eCashierService\x12_\n" +
	"\x15FindMonthlyTotalSales\x12\x1b.pb.FindYearMonthTotalSales\x1a'.pb.ApiResponseCashierMonthlyTotalSales\"\x00\x12X\n" +
	"\x14FindYearlyTotalSales\x12\x16.pb.FindYearTotalSales\x1a&.pb.ApiResponseCashierYearlyTotalSales\"\x00\x12g\n" +
	"\x19FindMonthlyTotalSalesById\x12\x1f.pb.FindYearMonthTotalSalesById\x1a'.pb.ApiResponseCashierMonthlyTotalSales\"\x00\x12`\n" +
	"\x18FindYearlyTotalSalesById\x12\x1a.pb.FindYearTotalSalesById\x1a&.pb.ApiResponseCashierYearlyTotalSales\"\x00\x12s\n" +
	"\x1fFindMonthlyTotalSalesByMerchant\x12%.pb.FindYearMonthTotalSalesByMerchant\x1a'.pb.ApiResponseCashierMonthlyTotalSales\"\x00\x12l\n" +
	"\x1eFindYearlyTotalSalesByMerchant\x12 .pb.FindYearTotalSalesByMerchant\x1a&.pb.ApiResponseCashierYearlyTotalSales\"\x00\x12H\n" +
	"\aFindAll\x12\x19.pb.FindAllCashierRequest\x1a .pb.ApiResponsePaginationCashier\"\x00\x12@\n" +
	"\bFindById\x12\x1a.pb.FindByIdCashierRequest\x1a\x16.pb.ApiResponseCashier\"\x00\x12I\n" +
	"\x0eFindMonthSales\x12\x13.pb.FindYearCashier\x1a .pb.ApiResponseCashierMonthSales\"\x00\x12G\n" +
	"\rFindYearSales\x12\x13.pb.FindYearCashier\x1a\x1f.pb.ApiResponseCashierYearSales\"\x00\x12]\n" +
	"\x18FindMonthSalesByMerchant\x12\x1d.pb.FindYearCashierByMerchant\x1a .pb.ApiResponseCashierMonthSales\"\x00\x12[\n" +
	"\x17FindYearSalesByMerchant\x12\x1d.pb.FindYearCashierByMerchant\x1a\x1f.pb.ApiResponseCashierYearSales\"\x00\x12Q\n" +
	"\x12FindMonthSalesById\x12\x17.pb.FindYearCashierById\x1a .pb.ApiResponseCashierMonthSales\"\x00\x12O\n" +
	"\x11FindYearSalesById\x12\x17.pb.FindYearCashierById\x1a\x1f.pb.ApiResponseCashierYearSales\"\x00\x12U\n" +
	"\fFindByActive\x12\x19.pb.FindAllCashierRequest\x1a(.pb.ApiResponsePaginationCashierDeleteAt\"\x00\x12V\n" +
	"\rFindByTrashed\x12\x19.pb.FindAllCashierRequest\x1a(.pb.ApiResponsePaginationCashierDeleteAt\"\x00\x12V\n" +
	"\x0eFindByMerchant\x12 .pb.FindByMerchantCashierRequest\x1a .pb.ApiResponsePaginationCashier\"\x00\x12C\n" +
	"\rCreateCashier\x12\x18.pb.CreateCashierRequest\x1a\x16.pb.ApiResponseCashier\"\x00\x12C\n" +
	"\rUpdateCashier\x12\x18.pb.UpdateCashierRequest\x1a\x16.pb.ApiResponseCashier\"\x00\x12N\n" +
	"\x0eTrashedCashier\x12\x1a.pb.FindByIdCashierRequest\x1a\x1e.pb.ApiResponseCashierDeleteAt\"\x00\x12N\n" +
	"\x0eRestoreCashier\x12\x1a.pb.FindByIdCashierRequest\x1a\x1e.pb.ApiResponseCashierDeleteAt\"\x00\x12R\n" +
	"\x16DeleteCashierPermanent\x12\x1a.pb.FindByIdCashierRequest\x1a\x1c.pb.ApiResponseCashierDelete\x12H\n" +
	"\x11RestoreAllCashier\x12\x16.google.protobuf.Empty\x1a\x19.pb.ApiResponseCashierAll\"\x00\x12P\n" +
	"\x19DeleteAllCashierPermanent\x12\x16.google.protobuf.Empty\x1a\x19.pb.ApiResponseCashierAll\"\x00B<Z:github.com/MamangRust/pointofsale-graphql-grpc/internal/pbb\x06proto3"

var (
	file_cashier_proto_rawDescOnce sync.Once
	file_cashier_proto_rawDescData []byte
)

func file_cashier_proto_rawDescGZIP() []byte {
	file_cashier_proto_rawDescOnce.Do(func() {
		file_cashier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cashier_proto_rawDesc), len(file_cashier_proto_rawDesc)))
	})
	return file_cashier_proto_rawDescData
}

var file_cashier_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_cashier_proto_goTypes = []any{
	(*FindAllCashierRequest)(nil),                // 0: pb.FindAllCashierRequest
	(*FindByMerchantCashierRequest)(nil),         // 1: pb.FindByMerchantCashierRequest
	(*FindByIdCashierRequest)(nil),               // 2: pb.FindByIdCashierRequest
	(*FindYearCashier)(nil),                      // 3: pb.FindYearCashier
	(*FindYearCashierByMerchant)(nil),            // 4: pb.FindYearCashierByMerchant
	(*FindYearCashierById)(nil),                  // 5: pb.FindYearCashierById
	(*FindYearMonthTotalSales)(nil),              // 6: pb.FindYearMonthTotalSales
	(*FindYearTotalSales)(nil),                   // 7: pb.FindYearTotalSales
	(*FindYearMonthTotalSalesById)(nil),          // 8: pb.FindYearMonthTotalSalesById
	(*FindYearTotalSalesById)(nil),               // 9: pb.FindYearTotalSalesById
	(*FindYearMonthTotalSalesByMerchant)(nil),    // 10: pb.FindYearMonthTotalSalesByMerchant
	(*FindYearTotalSalesByMerchant)(nil),         // 11: pb.FindYearTotalSalesByMerchant
	(*CreateCashierRequest)(nil),                 // 12: pb.CreateCashierRequest
	(*UpdateCashierRequest)(nil),                 // 13: pb.UpdateCashierRequest
	(*CashierResponse)(nil),                      // 14: pb.CashierResponse
	(*CashierResponseDeleteAt)(nil),              // 15: pb.CashierResponseDeleteAt
	(*CashierResponseMonthSales)(nil),            // 16: pb.CashierResponseMonthSales
	(*CashierResponseYearSales)(nil),             // 17: pb.CashierResponseYearSales
	(*CashierResponseMonthTotalSales)(nil),       // 18: pb.CashierResponseMonthTotalSales
	(*CashierResponseYearTotalSales)(nil),        // 19: pb.CashierResponseYearTotalSales
	(*ApiResponseCashierMonthSales)(nil),         // 20: pb.ApiResponseCashierMonthSales
	(*ApiResponseCashierYearSales)(nil),          // 21: pb.ApiResponseCashierYearSales
	(*ApiResponseCashier)(nil),                   // 22: pb.ApiResponseCashier
	(*ApiResponseCashierDeleteAt)(nil),           // 23: pb.ApiResponseCashierDeleteAt
	(*ApiResponsesCashier)(nil),                  // 24: pb.ApiResponsesCashier
	(*ApiResponseCashierDelete)(nil),             // 25: pb.ApiResponseCashierDelete
	(*ApiResponseCashierAll)(nil),                // 26: pb.ApiResponseCashierAll
	(*ApiResponsePaginationCashierDeleteAt)(nil), // 27: pb.ApiResponsePaginationCashierDeleteAt
	(*ApiResponsePaginationCashier)(nil),         // 28: pb.ApiResponsePaginationCashier
	(*ApiResponseCashierMonthlyTotalSales)(nil),  // 29: pb.ApiResponseCashierMonthlyTotalSales
	(*ApiResponseCashierYearlyTotalSales)(nil),   // 30: pb.ApiResponseCashierYearlyTotalSales
	(*wrapperspb.StringValue)(nil),               // 31: google.protobuf.StringValue
	(*PaginationMeta)(nil),                       // 32: pb.PaginationMeta
	(*emptypb.Empty)(nil),                        // 33: google.protobuf.Empty
}
var file_cashier_proto_depIdxs = []int32{
	31, // 0: pb.CashierResponseDeleteAt.deleted_at:type_name -> google.protobuf.StringValue
	16, // 1: pb.ApiResponseCashierMonthSales.data:type_name -> pb.CashierResponseMonthSales
	17, // 2: pb.ApiResponseCashierYearSales.data:type_name -> pb.CashierResponseYearSales
	14, // 3: pb.ApiResponseCashier.data:type_name -> pb.CashierResponse
	15, // 4: pb.ApiResponseCashierDeleteAt.data:type_name -> pb.CashierResponseDeleteAt
	14, // 5: pb.ApiResponsesCashier.data:type_name -> pb.CashierResponse
	15, // 6: pb.ApiResponsePaginationCashierDeleteAt.data:type_name -> pb.CashierResponseDeleteAt
	32, // 7: pb.ApiResponsePaginationCashierDeleteAt.pagination:type_name -> pb.PaginationMeta
	14, // 8: pb.ApiResponsePaginationCashier.data:type_name -> pb.CashierResponse
	32, // 9: pb.ApiResponsePaginationCashier.pagination:type_name -> pb.PaginationMeta
	18, // 10: pb.ApiResponseCashierMonthlyTotalSales.data:type_name -> pb.CashierResponseMonthTotalSales
	19, // 11: pb.ApiResponseCashierYearlyTotalSales.data:type_name -> pb.CashierResponseYearTotalSales
	6,  // 12: pb.CashierService.FindMonthlyTotalSales:input_type -> pb.FindYearMonthTotalSales
	7,  // 13: pb.CashierService.FindYearlyTotalSales:input_type -> pb.FindYearTotalSales
	8,  // 14: pb.CashierService.FindMonthlyTotalSalesById:input_type -> pb.FindYearMonthTotalSalesById
	9,  // 15: pb.CashierService.FindYearlyTotalSalesById:input_type -> pb.FindYearTotalSalesById
	10, // 16: pb.CashierService.FindMonthlyTotalSalesByMerchant:input_type -> pb.FindYearMonthTotalSalesByMerchant
	11, // 17: pb.CashierService.FindYearlyTotalSalesByMerchant:input_type -> pb.FindYearTotalSalesByMerchant
	0,  // 18: pb.CashierService.FindAll:input_type -> pb.FindAllCashierRequest
	2,  // 19: pb.CashierService.FindById:input_type -> pb.FindByIdCashierRequest
	3,  // 20: pb.CashierService.FindMonthSales:input_type -> pb.FindYearCashier
	3,  // 21: pb.CashierService.FindYearSales:input_type -> pb.FindYearCashier
	4,  // 22: pb.CashierService.FindMonthSalesByMerchant:input_type -> pb.FindYearCashierByMerchant
	4,  // 23: pb.CashierService.FindYearSalesByMerchant:input_type -> pb.FindYearCashierByMerchant
	5,  // 24: pb.CashierService.FindMonthSalesById:input_type -> pb.FindYearCashierById
	5,  // 25: pb.CashierService.FindYearSalesById:input_type -> pb.FindYearCashierById
	0,  // 26: pb.CashierService.FindByActive:input_type -> pb.FindAllCashierRequest
	0,  // 27: pb.CashierService.FindByTrashed:input_type -> pb.FindAllCashierRequest
	1,  // 28: pb.CashierService.FindByMerchant:input_type -> pb.FindByMerchantCashierRequest
	12, // 29: pb.CashierService.CreateCashier:input_type -> pb.CreateCashierRequest
	13, // 30: pb.CashierService.UpdateCashier:input_type -> pb.UpdateCashierRequest
	2,  // 31: pb.CashierService.TrashedCashier:input_type -> pb.FindByIdCashierRequest
	2,  // 32: pb.CashierService.RestoreCashier:input_type -> pb.FindByIdCashierRequest
	2,  // 33: pb.CashierService.DeleteCashierPermanent:input_type -> pb.FindByIdCashierRequest
	33, // 34: pb.CashierService.RestoreAllCashier:input_type -> google.protobuf.Empty
	33, // 35: pb.CashierService.DeleteAllCashierPermanent:input_type -> google.protobuf.Empty
	29, // 36: pb.CashierService.FindMonthlyTotalSales:output_type -> pb.ApiResponseCashierMonthlyTotalSales
	30, // 37: pb.CashierService.FindYearlyTotalSales:output_type -> pb.ApiResponseCashierYearlyTotalSales
	29, // 38: pb.CashierService.FindMonthlyTotalSalesById:output_type -> pb.ApiResponseCashierMonthlyTotalSales
	30, // 39: pb.CashierService.FindYearlyTotalSalesById:output_type -> pb.ApiResponseCashierYearlyTotalSales
	29, // 40: pb.CashierService.FindMonthlyTotalSalesByMerchant:output_type -> pb.ApiResponseCashierMonthlyTotalSales
	30, // 41: pb.CashierService.FindYearlyTotalSalesByMerchant:output_type -> pb.ApiResponseCashierYearlyTotalSales
	28, // 42: pb.CashierService.FindAll:output_type -> pb.ApiResponsePaginationCashier
	22, // 43: pb.CashierService.FindById:output_type -> pb.ApiResponseCashier
	20, // 44: pb.CashierService.FindMonthSales:output_type -> pb.ApiResponseCashierMonthSales
	21, // 45: pb.CashierService.FindYearSales:output_type -> pb.ApiResponseCashierYearSales
	20, // 46: pb.CashierService.FindMonthSalesByMerchant:output_type -> pb.ApiResponseCashierMonthSales
	21, // 47: pb.CashierService.FindYearSalesByMerchant:output_type -> pb.ApiResponseCashierYearSales
	20, // 48: pb.CashierService.FindMonthSalesById:output_type -> pb.ApiResponseCashierMonthSales
	21, // 49: pb.CashierService.FindYearSalesById:output_type -> pb.ApiResponseCashierYearSales
	27, // 50: pb.CashierService.FindByActive:output_type -> pb.ApiResponsePaginationCashierDeleteAt
	27, // 51: pb.CashierService.FindByTrashed:output_type -> pb.ApiResponsePaginationCashierDeleteAt
	28, // 52: pb.CashierService.FindByMerchant:output_type -> pb.ApiResponsePaginationCashier
	22, // 53: pb.CashierService.CreateCashier:output_type -> pb.ApiResponseCashier
	22, // 54: pb.CashierService.UpdateCashier:output_type -> pb.ApiResponseCashier
	23, // 55: pb.CashierService.TrashedCashier:output_type -> pb.ApiResponseCashierDeleteAt
	23, // 56: pb.CashierService.RestoreCashier:output_type -> pb.ApiResponseCashierDeleteAt
	25, // 57: pb.CashierService.DeleteCashierPermanent:output_type -> pb.ApiResponseCashierDelete
	26, // 58: pb.CashierService.RestoreAllCashier:output_type -> pb.ApiResponseCashierAll
	26, // 59: pb.CashierService.DeleteAllCashierPermanent:output_type -> pb.ApiResponseCashierAll
	36, // [36:60] is the sub-list for method output_type
	12, // [12:36] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_cashier_proto_init() }
func file_cashier_proto_init() {
	if File_cashier_proto != nil {
		return
	}
	file_api_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cashier_proto_rawDesc), len(file_cashier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cashier_proto_goTypes,
		DependencyIndexes: file_cashier_proto_depIdxs,
		MessageInfos:      file_cashier_proto_msgTypes,
	}.Build()
	File_cashier_proto = out.File
	file_cashier_proto_goTypes = nil
	file_cashier_proto_depIdxs = nil
}
