// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: transaction.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TransactionService_FindAll_FullMethodName                          = "/pb.TransactionService/FindAll"
	TransactionService_FindByMerchant_FullMethodName                   = "/pb.TransactionService/FindByMerchant"
	TransactionService_FindById_FullMethodName                         = "/pb.TransactionService/FindById"
	TransactionService_FindMonthStatusSuccess_FullMethodName           = "/pb.TransactionService/FindMonthStatusSuccess"
	TransactionService_FindYearStatusSuccess_FullMethodName            = "/pb.TransactionService/FindYearStatusSuccess"
	TransactionService_FindMonthStatusFailed_FullMethodName            = "/pb.TransactionService/FindMonthStatusFailed"
	TransactionService_FindYearStatusFailed_FullMethodName             = "/pb.TransactionService/FindYearStatusFailed"
	TransactionService_FindMonthStatusSuccessByMerchant_FullMethodName = "/pb.TransactionService/FindMonthStatusSuccessByMerchant"
	TransactionService_FindYearStatusSuccessByMerchant_FullMethodName  = "/pb.TransactionService/FindYearStatusSuccessByMerchant"
	TransactionService_FindMonthStatusFailedByMerchant_FullMethodName  = "/pb.TransactionService/FindMonthStatusFailedByMerchant"
	TransactionService_FindYearStatusFailedByMerchant_FullMethodName   = "/pb.TransactionService/FindYearStatusFailedByMerchant"
	TransactionService_FindMonthMethodSuccess_FullMethodName           = "/pb.TransactionService/FindMonthMethodSuccess"
	TransactionService_FindYearMethodSuccess_FullMethodName            = "/pb.TransactionService/FindYearMethodSuccess"
	TransactionService_FindMonthMethodByMerchantSuccess_FullMethodName = "/pb.TransactionService/FindMonthMethodByMerchantSuccess"
	TransactionService_FindYearMethodByMerchantSuccess_FullMethodName  = "/pb.TransactionService/FindYearMethodByMerchantSuccess"
	TransactionService_FindMonthMethodFailed_FullMethodName            = "/pb.TransactionService/FindMonthMethodFailed"
	TransactionService_FindYearMethodFailed_FullMethodName             = "/pb.TransactionService/FindYearMethodFailed"
	TransactionService_FindMonthMethodByMerchantFailed_FullMethodName  = "/pb.TransactionService/FindMonthMethodByMerchantFailed"
	TransactionService_FindYearMethodByMerchantFailed_FullMethodName   = "/pb.TransactionService/FindYearMethodByMerchantFailed"
	TransactionService_FindByActive_FullMethodName                     = "/pb.TransactionService/FindByActive"
	TransactionService_FindByTrashed_FullMethodName                    = "/pb.TransactionService/FindByTrashed"
	TransactionService_Create_FullMethodName                           = "/pb.TransactionService/Create"
	TransactionService_Update_FullMethodName                           = "/pb.TransactionService/Update"
	TransactionService_TrashedTransaction_FullMethodName               = "/pb.TransactionService/TrashedTransaction"
	TransactionService_RestoreTransaction_FullMethodName               = "/pb.TransactionService/RestoreTransaction"
	TransactionService_DeleteTransactionPermanent_FullMethodName       = "/pb.TransactionService/DeleteTransactionPermanent"
	TransactionService_RestoreAllTransaction_FullMethodName            = "/pb.TransactionService/RestoreAllTransaction"
	TransactionService_DeleteAllTransactionPermanent_FullMethodName    = "/pb.TransactionService/DeleteAllTransactionPermanent"
)

// TransactionServiceClient is the client API for TransactionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionServiceClient interface {
	FindAll(ctx context.Context, in *FindAllTransactionRequest, opts ...grpc.CallOption) (*ApiResponsePaginationTransaction, error)
	FindByMerchant(ctx context.Context, in *FindAllTransactionMerchantRequest, opts ...grpc.CallOption) (*ApiResponsePaginationTransaction, error)
	FindById(ctx context.Context, in *FindByIdTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransaction, error)
	FindMonthStatusSuccess(ctx context.Context, in *FindMonthlyTransactionStatus, opts ...grpc.CallOption) (*ApiResponseTransactionMonthAmountSuccess, error)
	FindYearStatusSuccess(ctx context.Context, in *FindYearlyTransactionStatus, opts ...grpc.CallOption) (*ApiResponseTransactionYearAmountSuccess, error)
	FindMonthStatusFailed(ctx context.Context, in *FindMonthlyTransactionStatus, opts ...grpc.CallOption) (*ApiResponseTransactionMonthAmountFailed, error)
	FindYearStatusFailed(ctx context.Context, in *FindYearlyTransactionStatus, opts ...grpc.CallOption) (*ApiResponseTransactionYearAmountFailed, error)
	FindMonthStatusSuccessByMerchant(ctx context.Context, in *FindMonthlyTransactionStatusByMerchant, opts ...grpc.CallOption) (*ApiResponseTransactionMonthAmountSuccess, error)
	FindYearStatusSuccessByMerchant(ctx context.Context, in *FindYearlyTransactionStatusByMerchant, opts ...grpc.CallOption) (*ApiResponseTransactionYearAmountSuccess, error)
	FindMonthStatusFailedByMerchant(ctx context.Context, in *FindMonthlyTransactionStatusByMerchant, opts ...grpc.CallOption) (*ApiResponseTransactionMonthAmountFailed, error)
	FindYearStatusFailedByMerchant(ctx context.Context, in *FindYearlyTransactionStatusByMerchant, opts ...grpc.CallOption) (*ApiResponseTransactionYearAmountFailed, error)
	FindMonthMethodSuccess(ctx context.Context, in *MonthTransactionMethod, opts ...grpc.CallOption) (*ApiResponseTransactionMonthPaymentMethod, error)
	FindYearMethodSuccess(ctx context.Context, in *YearTransactionMethod, opts ...grpc.CallOption) (*ApiResponseTransactionYearPaymentmethod, error)
	FindMonthMethodByMerchantSuccess(ctx context.Context, in *MonthTransactionMethodByMerchant, opts ...grpc.CallOption) (*ApiResponseTransactionMonthPaymentMethod, error)
	FindYearMethodByMerchantSuccess(ctx context.Context, in *YearTransactionMethodByMerchant, opts ...grpc.CallOption) (*ApiResponseTransactionYearPaymentmethod, error)
	FindMonthMethodFailed(ctx context.Context, in *MonthTransactionMethod, opts ...grpc.CallOption) (*ApiResponseTransactionMonthPaymentMethod, error)
	FindYearMethodFailed(ctx context.Context, in *YearTransactionMethod, opts ...grpc.CallOption) (*ApiResponseTransactionYearPaymentmethod, error)
	FindMonthMethodByMerchantFailed(ctx context.Context, in *MonthTransactionMethodByMerchant, opts ...grpc.CallOption) (*ApiResponseTransactionMonthPaymentMethod, error)
	FindYearMethodByMerchantFailed(ctx context.Context, in *YearTransactionMethodByMerchant, opts ...grpc.CallOption) (*ApiResponseTransactionYearPaymentmethod, error)
	FindByActive(ctx context.Context, in *FindAllTransactionRequest, opts ...grpc.CallOption) (*ApiResponsePaginationTransactionDeleteAt, error)
	FindByTrashed(ctx context.Context, in *FindAllTransactionRequest, opts ...grpc.CallOption) (*ApiResponsePaginationTransactionDeleteAt, error)
	Create(ctx context.Context, in *CreateTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransaction, error)
	Update(ctx context.Context, in *UpdateTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransaction, error)
	TrashedTransaction(ctx context.Context, in *FindByIdTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransactionDeleteAt, error)
	RestoreTransaction(ctx context.Context, in *FindByIdTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransactionDeleteAt, error)
	DeleteTransactionPermanent(ctx context.Context, in *FindByIdTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransactionDelete, error)
	RestoreAllTransaction(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ApiResponseTransactionAll, error)
	DeleteAllTransactionPermanent(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ApiResponseTransactionAll, error)
}

type transactionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionServiceClient(cc grpc.ClientConnInterface) TransactionServiceClient {
	return &transactionServiceClient{cc}
}

func (c *transactionServiceClient) FindAll(ctx context.Context, in *FindAllTransactionRequest, opts ...grpc.CallOption) (*ApiResponsePaginationTransaction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponsePaginationTransaction)
	err := c.cc.Invoke(ctx, TransactionService_FindAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) FindByMerchant(ctx context.Context, in *FindAllTransactionMerchantRequest, opts ...grpc.CallOption) (*ApiResponsePaginationTransaction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponsePaginationTransaction)
	err := c.cc.Invoke(ctx, TransactionService_FindByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) FindById(ctx context.Context, in *FindByIdTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransaction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransaction)
	err := c.cc.Invoke(ctx, TransactionService_FindById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) FindMonthStatusSuccess(ctx context.Context, in *FindMonthlyTransactionStatus, opts ...grpc.CallOption) (*ApiResponseTransactionMonthAmountSuccess, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionMonthAmountSuccess)
	err := c.cc.Invoke(ctx, TransactionService_FindMonthStatusSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) FindYearStatusSuccess(ctx context.Context, in *FindYearlyTransactionStatus, opts ...grpc.CallOption) (*ApiResponseTransactionYearAmountSuccess, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionYearAmountSuccess)
	err := c.cc.Invoke(ctx, TransactionService_FindYearStatusSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) FindMonthStatusFailed(ctx context.Context, in *FindMonthlyTransactionStatus, opts ...grpc.CallOption) (*ApiResponseTransactionMonthAmountFailed, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionMonthAmountFailed)
	err := c.cc.Invoke(ctx, TransactionService_FindMonthStatusFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) FindYearStatusFailed(ctx context.Context, in *FindYearlyTransactionStatus, opts ...grpc.CallOption) (*ApiResponseTransactionYearAmountFailed, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionYearAmountFailed)
	err := c.cc.Invoke(ctx, TransactionService_FindYearStatusFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) FindMonthStatusSuccessByMerchant(ctx context.Context, in *FindMonthlyTransactionStatusByMerchant, opts ...grpc.CallOption) (*ApiResponseTransactionMonthAmountSuccess, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionMonthAmountSuccess)
	err := c.cc.Invoke(ctx, TransactionService_FindMonthStatusSuccessByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) FindYearStatusSuccessByMerchant(ctx context.Context, in *FindYearlyTransactionStatusByMerchant, opts ...grpc.CallOption) (*ApiResponseTransactionYearAmountSuccess, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionYearAmountSuccess)
	err := c.cc.Invoke(ctx, TransactionService_FindYearStatusSuccessByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) FindMonthStatusFailedByMerchant(ctx context.Context, in *FindMonthlyTransactionStatusByMerchant, opts ...grpc.CallOption) (*ApiResponseTransactionMonthAmountFailed, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionMonthAmountFailed)
	err := c.cc.Invoke(ctx, TransactionService_FindMonthStatusFailedByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) FindYearStatusFailedByMerchant(ctx context.Context, in *FindYearlyTransactionStatusByMerchant, opts ...grpc.CallOption) (*ApiResponseTransactionYearAmountFailed, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionYearAmountFailed)
	err := c.cc.Invoke(ctx, TransactionService_FindYearStatusFailedByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) FindMonthMethodSuccess(ctx context.Context, in *MonthTransactionMethod, opts ...grpc.CallOption) (*ApiResponseTransactionMonthPaymentMethod, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionMonthPaymentMethod)
	err := c.cc.Invoke(ctx, TransactionService_FindMonthMethodSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) FindYearMethodSuccess(ctx context.Context, in *YearTransactionMethod, opts ...grpc.CallOption) (*ApiResponseTransactionYearPaymentmethod, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionYearPaymentmethod)
	err := c.cc.Invoke(ctx, TransactionService_FindYearMethodSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) FindMonthMethodByMerchantSuccess(ctx context.Context, in *MonthTransactionMethodByMerchant, opts ...grpc.CallOption) (*ApiResponseTransactionMonthPaymentMethod, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionMonthPaymentMethod)
	err := c.cc.Invoke(ctx, TransactionService_FindMonthMethodByMerchantSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) FindYearMethodByMerchantSuccess(ctx context.Context, in *YearTransactionMethodByMerchant, opts ...grpc.CallOption) (*ApiResponseTransactionYearPaymentmethod, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionYearPaymentmethod)
	err := c.cc.Invoke(ctx, TransactionService_FindYearMethodByMerchantSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) FindMonthMethodFailed(ctx context.Context, in *MonthTransactionMethod, opts ...grpc.CallOption) (*ApiResponseTransactionMonthPaymentMethod, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionMonthPaymentMethod)
	err := c.cc.Invoke(ctx, TransactionService_FindMonthMethodFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) FindYearMethodFailed(ctx context.Context, in *YearTransactionMethod, opts ...grpc.CallOption) (*ApiResponseTransactionYearPaymentmethod, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionYearPaymentmethod)
	err := c.cc.Invoke(ctx, TransactionService_FindYearMethodFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) FindMonthMethodByMerchantFailed(ctx context.Context, in *MonthTransactionMethodByMerchant, opts ...grpc.CallOption) (*ApiResponseTransactionMonthPaymentMethod, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionMonthPaymentMethod)
	err := c.cc.Invoke(ctx, TransactionService_FindMonthMethodByMerchantFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) FindYearMethodByMerchantFailed(ctx context.Context, in *YearTransactionMethodByMerchant, opts ...grpc.CallOption) (*ApiResponseTransactionYearPaymentmethod, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionYearPaymentmethod)
	err := c.cc.Invoke(ctx, TransactionService_FindYearMethodByMerchantFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) FindByActive(ctx context.Context, in *FindAllTransactionRequest, opts ...grpc.CallOption) (*ApiResponsePaginationTransactionDeleteAt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponsePaginationTransactionDeleteAt)
	err := c.cc.Invoke(ctx, TransactionService_FindByActive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) FindByTrashed(ctx context.Context, in *FindAllTransactionRequest, opts ...grpc.CallOption) (*ApiResponsePaginationTransactionDeleteAt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponsePaginationTransactionDeleteAt)
	err := c.cc.Invoke(ctx, TransactionService_FindByTrashed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) Create(ctx context.Context, in *CreateTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransaction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransaction)
	err := c.cc.Invoke(ctx, TransactionService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) Update(ctx context.Context, in *UpdateTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransaction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransaction)
	err := c.cc.Invoke(ctx, TransactionService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) TrashedTransaction(ctx context.Context, in *FindByIdTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransactionDeleteAt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionDeleteAt)
	err := c.cc.Invoke(ctx, TransactionService_TrashedTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) RestoreTransaction(ctx context.Context, in *FindByIdTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransactionDeleteAt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionDeleteAt)
	err := c.cc.Invoke(ctx, TransactionService_RestoreTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) DeleteTransactionPermanent(ctx context.Context, in *FindByIdTransactionRequest, opts ...grpc.CallOption) (*ApiResponseTransactionDelete, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionDelete)
	err := c.cc.Invoke(ctx, TransactionService_DeleteTransactionPermanent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) RestoreAllTransaction(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ApiResponseTransactionAll, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionAll)
	err := c.cc.Invoke(ctx, TransactionService_RestoreAllTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) DeleteAllTransactionPermanent(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ApiResponseTransactionAll, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseTransactionAll)
	err := c.cc.Invoke(ctx, TransactionService_DeleteAllTransactionPermanent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionServiceServer is the server API for TransactionService service.
// All implementations must embed UnimplementedTransactionServiceServer
// for forward compatibility.
type TransactionServiceServer interface {
	FindAll(context.Context, *FindAllTransactionRequest) (*ApiResponsePaginationTransaction, error)
	FindByMerchant(context.Context, *FindAllTransactionMerchantRequest) (*ApiResponsePaginationTransaction, error)
	FindById(context.Context, *FindByIdTransactionRequest) (*ApiResponseTransaction, error)
	FindMonthStatusSuccess(context.Context, *FindMonthlyTransactionStatus) (*ApiResponseTransactionMonthAmountSuccess, error)
	FindYearStatusSuccess(context.Context, *FindYearlyTransactionStatus) (*ApiResponseTransactionYearAmountSuccess, error)
	FindMonthStatusFailed(context.Context, *FindMonthlyTransactionStatus) (*ApiResponseTransactionMonthAmountFailed, error)
	FindYearStatusFailed(context.Context, *FindYearlyTransactionStatus) (*ApiResponseTransactionYearAmountFailed, error)
	FindMonthStatusSuccessByMerchant(context.Context, *FindMonthlyTransactionStatusByMerchant) (*ApiResponseTransactionMonthAmountSuccess, error)
	FindYearStatusSuccessByMerchant(context.Context, *FindYearlyTransactionStatusByMerchant) (*ApiResponseTransactionYearAmountSuccess, error)
	FindMonthStatusFailedByMerchant(context.Context, *FindMonthlyTransactionStatusByMerchant) (*ApiResponseTransactionMonthAmountFailed, error)
	FindYearStatusFailedByMerchant(context.Context, *FindYearlyTransactionStatusByMerchant) (*ApiResponseTransactionYearAmountFailed, error)
	FindMonthMethodSuccess(context.Context, *MonthTransactionMethod) (*ApiResponseTransactionMonthPaymentMethod, error)
	FindYearMethodSuccess(context.Context, *YearTransactionMethod) (*ApiResponseTransactionYearPaymentmethod, error)
	FindMonthMethodByMerchantSuccess(context.Context, *MonthTransactionMethodByMerchant) (*ApiResponseTransactionMonthPaymentMethod, error)
	FindYearMethodByMerchantSuccess(context.Context, *YearTransactionMethodByMerchant) (*ApiResponseTransactionYearPaymentmethod, error)
	FindMonthMethodFailed(context.Context, *MonthTransactionMethod) (*ApiResponseTransactionMonthPaymentMethod, error)
	FindYearMethodFailed(context.Context, *YearTransactionMethod) (*ApiResponseTransactionYearPaymentmethod, error)
	FindMonthMethodByMerchantFailed(context.Context, *MonthTransactionMethodByMerchant) (*ApiResponseTransactionMonthPaymentMethod, error)
	FindYearMethodByMerchantFailed(context.Context, *YearTransactionMethodByMerchant) (*ApiResponseTransactionYearPaymentmethod, error)
	FindByActive(context.Context, *FindAllTransactionRequest) (*ApiResponsePaginationTransactionDeleteAt, error)
	FindByTrashed(context.Context, *FindAllTransactionRequest) (*ApiResponsePaginationTransactionDeleteAt, error)
	Create(context.Context, *CreateTransactionRequest) (*ApiResponseTransaction, error)
	Update(context.Context, *UpdateTransactionRequest) (*ApiResponseTransaction, error)
	TrashedTransaction(context.Context, *FindByIdTransactionRequest) (*ApiResponseTransactionDeleteAt, error)
	RestoreTransaction(context.Context, *FindByIdTransactionRequest) (*ApiResponseTransactionDeleteAt, error)
	DeleteTransactionPermanent(context.Context, *FindByIdTransactionRequest) (*ApiResponseTransactionDelete, error)
	RestoreAllTransaction(context.Context, *emptypb.Empty) (*ApiResponseTransactionAll, error)
	DeleteAllTransactionPermanent(context.Context, *emptypb.Empty) (*ApiResponseTransactionAll, error)
	mustEmbedUnimplementedTransactionServiceServer()
}

// UnimplementedTransactionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransactionServiceServer struct{}

func (UnimplementedTransactionServiceServer) FindAll(context.Context, *FindAllTransactionRequest) (*ApiResponsePaginationTransaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAll not implemented")
}
func (UnimplementedTransactionServiceServer) FindByMerchant(context.Context, *FindAllTransactionMerchantRequest) (*ApiResponsePaginationTransaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByMerchant not implemented")
}
func (UnimplementedTransactionServiceServer) FindById(context.Context, *FindByIdTransactionRequest) (*ApiResponseTransaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindById not implemented")
}
func (UnimplementedTransactionServiceServer) FindMonthStatusSuccess(context.Context, *FindMonthlyTransactionStatus) (*ApiResponseTransactionMonthAmountSuccess, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindMonthStatusSuccess not implemented")
}
func (UnimplementedTransactionServiceServer) FindYearStatusSuccess(context.Context, *FindYearlyTransactionStatus) (*ApiResponseTransactionYearAmountSuccess, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindYearStatusSuccess not implemented")
}
func (UnimplementedTransactionServiceServer) FindMonthStatusFailed(context.Context, *FindMonthlyTransactionStatus) (*ApiResponseTransactionMonthAmountFailed, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindMonthStatusFailed not implemented")
}
func (UnimplementedTransactionServiceServer) FindYearStatusFailed(context.Context, *FindYearlyTransactionStatus) (*ApiResponseTransactionYearAmountFailed, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindYearStatusFailed not implemented")
}
func (UnimplementedTransactionServiceServer) FindMonthStatusSuccessByMerchant(context.Context, *FindMonthlyTransactionStatusByMerchant) (*ApiResponseTransactionMonthAmountSuccess, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindMonthStatusSuccessByMerchant not implemented")
}
func (UnimplementedTransactionServiceServer) FindYearStatusSuccessByMerchant(context.Context, *FindYearlyTransactionStatusByMerchant) (*ApiResponseTransactionYearAmountSuccess, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindYearStatusSuccessByMerchant not implemented")
}
func (UnimplementedTransactionServiceServer) FindMonthStatusFailedByMerchant(context.Context, *FindMonthlyTransactionStatusByMerchant) (*ApiResponseTransactionMonthAmountFailed, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindMonthStatusFailedByMerchant not implemented")
}
func (UnimplementedTransactionServiceServer) FindYearStatusFailedByMerchant(context.Context, *FindYearlyTransactionStatusByMerchant) (*ApiResponseTransactionYearAmountFailed, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindYearStatusFailedByMerchant not implemented")
}
func (UnimplementedTransactionServiceServer) FindMonthMethodSuccess(context.Context, *MonthTransactionMethod) (*ApiResponseTransactionMonthPaymentMethod, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindMonthMethodSuccess not implemented")
}
func (UnimplementedTransactionServiceServer) FindYearMethodSuccess(context.Context, *YearTransactionMethod) (*ApiResponseTransactionYearPaymentmethod, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindYearMethodSuccess not implemented")
}
func (UnimplementedTransactionServiceServer) FindMonthMethodByMerchantSuccess(context.Context, *MonthTransactionMethodByMerchant) (*ApiResponseTransactionMonthPaymentMethod, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindMonthMethodByMerchantSuccess not implemented")
}
func (UnimplementedTransactionServiceServer) FindYearMethodByMerchantSuccess(context.Context, *YearTransactionMethodByMerchant) (*ApiResponseTransactionYearPaymentmethod, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindYearMethodByMerchantSuccess not implemented")
}
func (UnimplementedTransactionServiceServer) FindMonthMethodFailed(context.Context, *MonthTransactionMethod) (*ApiResponseTransactionMonthPaymentMethod, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindMonthMethodFailed not implemented")
}
func (UnimplementedTransactionServiceServer) FindYearMethodFailed(context.Context, *YearTransactionMethod) (*ApiResponseTransactionYearPaymentmethod, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindYearMethodFailed not implemented")
}
func (UnimplementedTransactionServiceServer) FindMonthMethodByMerchantFailed(context.Context, *MonthTransactionMethodByMerchant) (*ApiResponseTransactionMonthPaymentMethod, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindMonthMethodByMerchantFailed not implemented")
}
func (UnimplementedTransactionServiceServer) FindYearMethodByMerchantFailed(context.Context, *YearTransactionMethodByMerchant) (*ApiResponseTransactionYearPaymentmethod, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindYearMethodByMerchantFailed not implemented")
}
func (UnimplementedTransactionServiceServer) FindByActive(context.Context, *FindAllTransactionRequest) (*ApiResponsePaginationTransactionDeleteAt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByActive not implemented")
}
func (UnimplementedTransactionServiceServer) FindByTrashed(context.Context, *FindAllTransactionRequest) (*ApiResponsePaginationTransactionDeleteAt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByTrashed not implemented")
}
func (UnimplementedTransactionServiceServer) Create(context.Context, *CreateTransactionRequest) (*ApiResponseTransaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedTransactionServiceServer) Update(context.Context, *UpdateTransactionRequest) (*ApiResponseTransaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedTransactionServiceServer) TrashedTransaction(context.Context, *FindByIdTransactionRequest) (*ApiResponseTransactionDeleteAt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrashedTransaction not implemented")
}
func (UnimplementedTransactionServiceServer) RestoreTransaction(context.Context, *FindByIdTransactionRequest) (*ApiResponseTransactionDeleteAt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestoreTransaction not implemented")
}
func (UnimplementedTransactionServiceServer) DeleteTransactionPermanent(context.Context, *FindByIdTransactionRequest) (*ApiResponseTransactionDelete, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTransactionPermanent not implemented")
}
func (UnimplementedTransactionServiceServer) RestoreAllTransaction(context.Context, *emptypb.Empty) (*ApiResponseTransactionAll, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestoreAllTransaction not implemented")
}
func (UnimplementedTransactionServiceServer) DeleteAllTransactionPermanent(context.Context, *emptypb.Empty) (*ApiResponseTransactionAll, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAllTransactionPermanent not implemented")
}
func (UnimplementedTransactionServiceServer) mustEmbedUnimplementedTransactionServiceServer() {}
func (UnimplementedTransactionServiceServer) testEmbeddedByValue()                            {}

// UnsafeTransactionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionServiceServer will
// result in compilation errors.
type UnsafeTransactionServiceServer interface {
	mustEmbedUnimplementedTransactionServiceServer()
}

func RegisterTransactionServiceServer(s grpc.ServiceRegistrar, srv TransactionServiceServer) {
	// If the following call pancis, it indicates UnimplementedTransactionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransactionService_ServiceDesc, srv)
}

func _TransactionService_FindAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).FindAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_FindAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).FindAll(ctx, req.(*FindAllTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_FindByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllTransactionMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).FindByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_FindByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).FindByMerchant(ctx, req.(*FindAllTransactionMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_FindById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIdTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).FindById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_FindById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).FindById(ctx, req.(*FindByIdTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_FindMonthStatusSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindMonthlyTransactionStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).FindMonthStatusSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_FindMonthStatusSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).FindMonthStatusSuccess(ctx, req.(*FindMonthlyTransactionStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_FindYearStatusSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearlyTransactionStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).FindYearStatusSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_FindYearStatusSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).FindYearStatusSuccess(ctx, req.(*FindYearlyTransactionStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_FindMonthStatusFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindMonthlyTransactionStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).FindMonthStatusFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_FindMonthStatusFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).FindMonthStatusFailed(ctx, req.(*FindMonthlyTransactionStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_FindYearStatusFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearlyTransactionStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).FindYearStatusFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_FindYearStatusFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).FindYearStatusFailed(ctx, req.(*FindYearlyTransactionStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_FindMonthStatusSuccessByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindMonthlyTransactionStatusByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).FindMonthStatusSuccessByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_FindMonthStatusSuccessByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).FindMonthStatusSuccessByMerchant(ctx, req.(*FindMonthlyTransactionStatusByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_FindYearStatusSuccessByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearlyTransactionStatusByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).FindYearStatusSuccessByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_FindYearStatusSuccessByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).FindYearStatusSuccessByMerchant(ctx, req.(*FindYearlyTransactionStatusByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_FindMonthStatusFailedByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindMonthlyTransactionStatusByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).FindMonthStatusFailedByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_FindMonthStatusFailedByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).FindMonthStatusFailedByMerchant(ctx, req.(*FindMonthlyTransactionStatusByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_FindYearStatusFailedByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearlyTransactionStatusByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).FindYearStatusFailedByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_FindYearStatusFailedByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).FindYearStatusFailedByMerchant(ctx, req.(*FindYearlyTransactionStatusByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_FindMonthMethodSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonthTransactionMethod)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).FindMonthMethodSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_FindMonthMethodSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).FindMonthMethodSuccess(ctx, req.(*MonthTransactionMethod))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_FindYearMethodSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(YearTransactionMethod)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).FindYearMethodSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_FindYearMethodSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).FindYearMethodSuccess(ctx, req.(*YearTransactionMethod))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_FindMonthMethodByMerchantSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonthTransactionMethodByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).FindMonthMethodByMerchantSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_FindMonthMethodByMerchantSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).FindMonthMethodByMerchantSuccess(ctx, req.(*MonthTransactionMethodByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_FindYearMethodByMerchantSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(YearTransactionMethodByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).FindYearMethodByMerchantSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_FindYearMethodByMerchantSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).FindYearMethodByMerchantSuccess(ctx, req.(*YearTransactionMethodByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_FindMonthMethodFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonthTransactionMethod)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).FindMonthMethodFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_FindMonthMethodFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).FindMonthMethodFailed(ctx, req.(*MonthTransactionMethod))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_FindYearMethodFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(YearTransactionMethod)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).FindYearMethodFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_FindYearMethodFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).FindYearMethodFailed(ctx, req.(*YearTransactionMethod))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_FindMonthMethodByMerchantFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonthTransactionMethodByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).FindMonthMethodByMerchantFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_FindMonthMethodByMerchantFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).FindMonthMethodByMerchantFailed(ctx, req.(*MonthTransactionMethodByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_FindYearMethodByMerchantFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(YearTransactionMethodByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).FindYearMethodByMerchantFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_FindYearMethodByMerchantFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).FindYearMethodByMerchantFailed(ctx, req.(*YearTransactionMethodByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_FindByActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).FindByActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_FindByActive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).FindByActive(ctx, req.(*FindAllTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_FindByTrashed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).FindByTrashed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_FindByTrashed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).FindByTrashed(ctx, req.(*FindAllTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).Create(ctx, req.(*CreateTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).Update(ctx, req.(*UpdateTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_TrashedTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIdTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).TrashedTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_TrashedTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).TrashedTransaction(ctx, req.(*FindByIdTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_RestoreTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIdTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).RestoreTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_RestoreTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).RestoreTransaction(ctx, req.(*FindByIdTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_DeleteTransactionPermanent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIdTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).DeleteTransactionPermanent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_DeleteTransactionPermanent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).DeleteTransactionPermanent(ctx, req.(*FindByIdTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_RestoreAllTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).RestoreAllTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_RestoreAllTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).RestoreAllTransaction(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_DeleteAllTransactionPermanent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).DeleteAllTransactionPermanent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_DeleteAllTransactionPermanent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).DeleteAllTransactionPermanent(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// TransactionService_ServiceDesc is the grpc.ServiceDesc for TransactionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.TransactionService",
	HandlerType: (*TransactionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindAll",
			Handler:    _TransactionService_FindAll_Handler,
		},
		{
			MethodName: "FindByMerchant",
			Handler:    _TransactionService_FindByMerchant_Handler,
		},
		{
			MethodName: "FindById",
			Handler:    _TransactionService_FindById_Handler,
		},
		{
			MethodName: "FindMonthStatusSuccess",
			Handler:    _TransactionService_FindMonthStatusSuccess_Handler,
		},
		{
			MethodName: "FindYearStatusSuccess",
			Handler:    _TransactionService_FindYearStatusSuccess_Handler,
		},
		{
			MethodName: "FindMonthStatusFailed",
			Handler:    _TransactionService_FindMonthStatusFailed_Handler,
		},
		{
			MethodName: "FindYearStatusFailed",
			Handler:    _TransactionService_FindYearStatusFailed_Handler,
		},
		{
			MethodName: "FindMonthStatusSuccessByMerchant",
			Handler:    _TransactionService_FindMonthStatusSuccessByMerchant_Handler,
		},
		{
			MethodName: "FindYearStatusSuccessByMerchant",
			Handler:    _TransactionService_FindYearStatusSuccessByMerchant_Handler,
		},
		{
			MethodName: "FindMonthStatusFailedByMerchant",
			Handler:    _TransactionService_FindMonthStatusFailedByMerchant_Handler,
		},
		{
			MethodName: "FindYearStatusFailedByMerchant",
			Handler:    _TransactionService_FindYearStatusFailedByMerchant_Handler,
		},
		{
			MethodName: "FindMonthMethodSuccess",
			Handler:    _TransactionService_FindMonthMethodSuccess_Handler,
		},
		{
			MethodName: "FindYearMethodSuccess",
			Handler:    _TransactionService_FindYearMethodSuccess_Handler,
		},
		{
			MethodName: "FindMonthMethodByMerchantSuccess",
			Handler:    _TransactionService_FindMonthMethodByMerchantSuccess_Handler,
		},
		{
			MethodName: "FindYearMethodByMerchantSuccess",
			Handler:    _TransactionService_FindYearMethodByMerchantSuccess_Handler,
		},
		{
			MethodName: "FindMonthMethodFailed",
			Handler:    _TransactionService_FindMonthMethodFailed_Handler,
		},
		{
			MethodName: "FindYearMethodFailed",
			Handler:    _TransactionService_FindYearMethodFailed_Handler,
		},
		{
			MethodName: "FindMonthMethodByMerchantFailed",
			Handler:    _TransactionService_FindMonthMethodByMerchantFailed_Handler,
		},
		{
			MethodName: "FindYearMethodByMerchantFailed",
			Handler:    _TransactionService_FindYearMethodByMerchantFailed_Handler,
		},
		{
			MethodName: "FindByActive",
			Handler:    _TransactionService_FindByActive_Handler,
		},
		{
			MethodName: "FindByTrashed",
			Handler:    _TransactionService_FindByTrashed_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _TransactionService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _TransactionService_Update_Handler,
		},
		{
			MethodName: "TrashedTransaction",
			Handler:    _TransactionService_TrashedTransaction_Handler,
		},
		{
			MethodName: "RestoreTransaction",
			Handler:    _TransactionService_RestoreTransaction_Handler,
		},
		{
			MethodName: "DeleteTransactionPermanent",
			Handler:    _TransactionService_DeleteTransactionPermanent_Handler,
		},
		{
			MethodName: "RestoreAllTransaction",
			Handler:    _TransactionService_RestoreAllTransaction_Handler,
		},
		{
			MethodName: "DeleteAllTransactionPermanent",
			Handler:    _TransactionService_DeleteAllTransactionPermanent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transaction.proto",
}
