// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: transaction.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAllTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllTransactionRequest) Reset() {
	*x = FindAllTransactionRequest{}
	mi := &file_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllTransactionRequest) ProtoMessage() {}

func (x *FindAllTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllTransactionRequest.ProtoReflect.Descriptor instead.
func (*FindAllTransactionRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *FindAllTransactionRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllTransactionRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllTransactionRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type FindAllTransactionMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    int32                  `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllTransactionMerchantRequest) Reset() {
	*x = FindAllTransactionMerchantRequest{}
	mi := &file_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllTransactionMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllTransactionMerchantRequest) ProtoMessage() {}

func (x *FindAllTransactionMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllTransactionMerchantRequest.ProtoReflect.Descriptor instead.
func (*FindAllTransactionMerchantRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *FindAllTransactionMerchantRequest) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *FindAllTransactionMerchantRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllTransactionMerchantRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllTransactionMerchantRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type FindMonthlyTransactionStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMonthlyTransactionStatus) Reset() {
	*x = FindMonthlyTransactionStatus{}
	mi := &file_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMonthlyTransactionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMonthlyTransactionStatus) ProtoMessage() {}

func (x *FindMonthlyTransactionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMonthlyTransactionStatus.ProtoReflect.Descriptor instead.
func (*FindMonthlyTransactionStatus) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *FindMonthlyTransactionStatus) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *FindMonthlyTransactionStatus) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

type FindYearlyTransactionStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearlyTransactionStatus) Reset() {
	*x = FindYearlyTransactionStatus{}
	mi := &file_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearlyTransactionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearlyTransactionStatus) ProtoMessage() {}

func (x *FindYearlyTransactionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearlyTransactionStatus.ProtoReflect.Descriptor instead.
func (*FindYearlyTransactionStatus) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *FindYearlyTransactionStatus) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *FindYearlyTransactionStatus) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

type FindMonthlyTransactionStatusByMerchant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	MerchantId    int32                  `protobuf:"varint,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMonthlyTransactionStatusByMerchant) Reset() {
	*x = FindMonthlyTransactionStatusByMerchant{}
	mi := &file_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMonthlyTransactionStatusByMerchant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMonthlyTransactionStatusByMerchant) ProtoMessage() {}

func (x *FindMonthlyTransactionStatusByMerchant) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMonthlyTransactionStatusByMerchant.ProtoReflect.Descriptor instead.
func (*FindMonthlyTransactionStatusByMerchant) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *FindMonthlyTransactionStatusByMerchant) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *FindMonthlyTransactionStatusByMerchant) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *FindMonthlyTransactionStatusByMerchant) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

type FindYearlyTransactionStatusByMerchant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	MerchantId    int32                  `protobuf:"varint,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearlyTransactionStatusByMerchant) Reset() {
	*x = FindYearlyTransactionStatusByMerchant{}
	mi := &file_transaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearlyTransactionStatusByMerchant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearlyTransactionStatusByMerchant) ProtoMessage() {}

func (x *FindYearlyTransactionStatusByMerchant) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearlyTransactionStatusByMerchant.ProtoReflect.Descriptor instead.
func (*FindYearlyTransactionStatusByMerchant) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{5}
}

func (x *FindYearlyTransactionStatusByMerchant) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *FindYearlyTransactionStatusByMerchant) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

type YearTransactionMethod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YearTransactionMethod) Reset() {
	*x = YearTransactionMethod{}
	mi := &file_transaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YearTransactionMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YearTransactionMethod) ProtoMessage() {}

func (x *YearTransactionMethod) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YearTransactionMethod.ProtoReflect.Descriptor instead.
func (*YearTransactionMethod) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{6}
}

func (x *YearTransactionMethod) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type MonthTransactionMethod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonthTransactionMethod) Reset() {
	*x = MonthTransactionMethod{}
	mi := &file_transaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthTransactionMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthTransactionMethod) ProtoMessage() {}

func (x *MonthTransactionMethod) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthTransactionMethod.ProtoReflect.Descriptor instead.
func (*MonthTransactionMethod) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{7}
}

func (x *MonthTransactionMethod) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *MonthTransactionMethod) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

type MonthTransactionMethodByMerchant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    int32                  `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,3,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonthTransactionMethodByMerchant) Reset() {
	*x = MonthTransactionMethodByMerchant{}
	mi := &file_transaction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthTransactionMethodByMerchant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthTransactionMethodByMerchant) ProtoMessage() {}

func (x *MonthTransactionMethodByMerchant) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthTransactionMethodByMerchant.ProtoReflect.Descriptor instead.
func (*MonthTransactionMethodByMerchant) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{8}
}

func (x *MonthTransactionMethodByMerchant) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *MonthTransactionMethodByMerchant) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *MonthTransactionMethodByMerchant) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

type YearTransactionMethodByMerchant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    int32                  `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YearTransactionMethodByMerchant) Reset() {
	*x = YearTransactionMethodByMerchant{}
	mi := &file_transaction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YearTransactionMethodByMerchant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YearTransactionMethodByMerchant) ProtoMessage() {}

func (x *YearTransactionMethodByMerchant) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YearTransactionMethodByMerchant.ProtoReflect.Descriptor instead.
func (*YearTransactionMethodByMerchant) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{9}
}

func (x *YearTransactionMethodByMerchant) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *YearTransactionMethodByMerchant) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type FindByIdTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdTransactionRequest) Reset() {
	*x = FindByIdTransactionRequest{}
	mi := &file_transaction_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdTransactionRequest) ProtoMessage() {}

func (x *FindByIdTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdTransactionRequest.ProtoReflect.Descriptor instead.
func (*FindByIdTransactionRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{10}
}

func (x *FindByIdTransactionRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CashierId     int32                  `protobuf:"varint,2,opt,name=cashier_id,json=cashierId,proto3" json:"cashier_id,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,3,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	Amount        int32                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentStatus string                 `protobuf:"bytes,5,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_transaction_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{11}
}

func (x *CreateTransactionRequest) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CreateTransactionRequest) GetCashierId() int32 {
	if x != nil {
		return x.CashierId
	}
	return 0
}

func (x *CreateTransactionRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *CreateTransactionRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateTransactionRequest) GetPaymentStatus() string {
	if x != nil {
		return x.PaymentStatus
	}
	return ""
}

type UpdateTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId int32                  `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	OrderId       int32                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CashierId     int32                  `protobuf:"varint,3,opt,name=cashier_id,json=cashierId,proto3" json:"cashier_id,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,4,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	Amount        int32                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentStatus string                 `protobuf:"bytes,6,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTransactionRequest) Reset() {
	*x = UpdateTransactionRequest{}
	mi := &file_transaction_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTransactionRequest) ProtoMessage() {}

func (x *UpdateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTransactionRequest.ProtoReflect.Descriptor instead.
func (*UpdateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateTransactionRequest) GetTransactionId() int32 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *UpdateTransactionRequest) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *UpdateTransactionRequest) GetCashierId() int32 {
	if x != nil {
		return x.CashierId
	}
	return 0
}

func (x *UpdateTransactionRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *UpdateTransactionRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UpdateTransactionRequest) GetPaymentStatus() string {
	if x != nil {
		return x.PaymentStatus
	}
	return ""
}

type TransactionMonthlyAmountSuccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          string                 `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         string                 `protobuf:"bytes,2,opt,name=month,proto3" json:"month,omitempty"`
	TotalSuccess  int32                  `protobuf:"varint,3,opt,name=total_success,json=totalSuccess,proto3" json:"total_success,omitempty"`
	TotalAmount   int32                  `protobuf:"varint,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionMonthlyAmountSuccess) Reset() {
	*x = TransactionMonthlyAmountSuccess{}
	mi := &file_transaction_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionMonthlyAmountSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionMonthlyAmountSuccess) ProtoMessage() {}

func (x *TransactionMonthlyAmountSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionMonthlyAmountSuccess.ProtoReflect.Descriptor instead.
func (*TransactionMonthlyAmountSuccess) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{13}
}

func (x *TransactionMonthlyAmountSuccess) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *TransactionMonthlyAmountSuccess) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *TransactionMonthlyAmountSuccess) GetTotalSuccess() int32 {
	if x != nil {
		return x.TotalSuccess
	}
	return 0
}

func (x *TransactionMonthlyAmountSuccess) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type TransactionMonthlyAmountFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          string                 `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         string                 `protobuf:"bytes,2,opt,name=month,proto3" json:"month,omitempty"`
	TotalFailed   int32                  `protobuf:"varint,3,opt,name=total_failed,json=totalFailed,proto3" json:"total_failed,omitempty"`
	TotalAmount   int32                  `protobuf:"varint,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionMonthlyAmountFailed) Reset() {
	*x = TransactionMonthlyAmountFailed{}
	mi := &file_transaction_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionMonthlyAmountFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionMonthlyAmountFailed) ProtoMessage() {}

func (x *TransactionMonthlyAmountFailed) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionMonthlyAmountFailed.ProtoReflect.Descriptor instead.
func (*TransactionMonthlyAmountFailed) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{14}
}

func (x *TransactionMonthlyAmountFailed) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *TransactionMonthlyAmountFailed) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *TransactionMonthlyAmountFailed) GetTotalFailed() int32 {
	if x != nil {
		return x.TotalFailed
	}
	return 0
}

func (x *TransactionMonthlyAmountFailed) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type TransactionYearlyAmountSuccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          string                 `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	TotalSuccess  int32                  `protobuf:"varint,2,opt,name=total_success,json=totalSuccess,proto3" json:"total_success,omitempty"`
	TotalAmount   int32                  `protobuf:"varint,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionYearlyAmountSuccess) Reset() {
	*x = TransactionYearlyAmountSuccess{}
	mi := &file_transaction_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionYearlyAmountSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionYearlyAmountSuccess) ProtoMessage() {}

func (x *TransactionYearlyAmountSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionYearlyAmountSuccess.ProtoReflect.Descriptor instead.
func (*TransactionYearlyAmountSuccess) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{15}
}

func (x *TransactionYearlyAmountSuccess) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *TransactionYearlyAmountSuccess) GetTotalSuccess() int32 {
	if x != nil {
		return x.TotalSuccess
	}
	return 0
}

func (x *TransactionYearlyAmountSuccess) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type TransactionYearlyAmountFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          string                 `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	TotalFailed   int32                  `protobuf:"varint,2,opt,name=total_failed,json=totalFailed,proto3" json:"total_failed,omitempty"`
	TotalAmount   int32                  `protobuf:"varint,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionYearlyAmountFailed) Reset() {
	*x = TransactionYearlyAmountFailed{}
	mi := &file_transaction_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionYearlyAmountFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionYearlyAmountFailed) ProtoMessage() {}

func (x *TransactionYearlyAmountFailed) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionYearlyAmountFailed.ProtoReflect.Descriptor instead.
func (*TransactionYearlyAmountFailed) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{16}
}

func (x *TransactionYearlyAmountFailed) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *TransactionYearlyAmountFailed) GetTotalFailed() int32 {
	if x != nil {
		return x.TotalFailed
	}
	return 0
}

func (x *TransactionYearlyAmountFailed) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type TransactionMonthlyMethod struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Month             string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
	PaymentMethod     string                 `protobuf:"bytes,2,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	TotalTransactions int32                  `protobuf:"varint,3,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"`
	TotalAmount       int32                  `protobuf:"varint,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TransactionMonthlyMethod) Reset() {
	*x = TransactionMonthlyMethod{}
	mi := &file_transaction_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionMonthlyMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionMonthlyMethod) ProtoMessage() {}

func (x *TransactionMonthlyMethod) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionMonthlyMethod.ProtoReflect.Descriptor instead.
func (*TransactionMonthlyMethod) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{17}
}

func (x *TransactionMonthlyMethod) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *TransactionMonthlyMethod) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *TransactionMonthlyMethod) GetTotalTransactions() int32 {
	if x != nil {
		return x.TotalTransactions
	}
	return 0
}

func (x *TransactionMonthlyMethod) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type TransactionYearlyMethod struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Year              string                 `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	PaymentMethod     string                 `protobuf:"bytes,2,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	TotalTransactions int32                  `protobuf:"varint,3,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"`
	TotalAmount       int32                  `protobuf:"varint,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TransactionYearlyMethod) Reset() {
	*x = TransactionYearlyMethod{}
	mi := &file_transaction_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionYearlyMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionYearlyMethod) ProtoMessage() {}

func (x *TransactionYearlyMethod) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionYearlyMethod.ProtoReflect.Descriptor instead.
func (*TransactionYearlyMethod) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{18}
}

func (x *TransactionYearlyMethod) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *TransactionYearlyMethod) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *TransactionYearlyMethod) GetTotalTransactions() int32 {
	if x != nil {
		return x.TotalTransactions
	}
	return 0
}

func (x *TransactionYearlyMethod) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type TransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       int32                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	MerchantId    int32                  `protobuf:"varint,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,4,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	Amount        int32                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	ChangeAmount  int32                  `protobuf:"varint,6,opt,name=change_amount,json=changeAmount,proto3" json:"change_amount,omitempty"`
	PaymentStatus string                 `protobuf:"bytes,7,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_transaction_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{19}
}

func (x *TransactionResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TransactionResponse) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *TransactionResponse) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *TransactionResponse) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *TransactionResponse) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionResponse) GetChangeAmount() int32 {
	if x != nil {
		return x.ChangeAmount
	}
	return 0
}

func (x *TransactionResponse) GetPaymentStatus() string {
	if x != nil {
		return x.PaymentStatus
	}
	return ""
}

func (x *TransactionResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TransactionResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type TransactionResponseDeleteAt struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            int32                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       int32                   `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	MerchantId    int32                   `protobuf:"varint,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	PaymentMethod string                  `protobuf:"bytes,4,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	Amount        int32                   `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	ChangeAmount  int32                   `protobuf:"varint,6,opt,name=change_amount,json=changeAmount,proto3" json:"change_amount,omitempty"`
	PaymentStatus string                  `protobuf:"bytes,7,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
	CreatedAt     string                  `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                  `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *wrapperspb.StringValue `protobuf:"bytes,10,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionResponseDeleteAt) Reset() {
	*x = TransactionResponseDeleteAt{}
	mi := &file_transaction_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponseDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponseDeleteAt) ProtoMessage() {}

func (x *TransactionResponseDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponseDeleteAt.ProtoReflect.Descriptor instead.
func (*TransactionResponseDeleteAt) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{20}
}

func (x *TransactionResponseDeleteAt) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TransactionResponseDeleteAt) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *TransactionResponseDeleteAt) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *TransactionResponseDeleteAt) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *TransactionResponseDeleteAt) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionResponseDeleteAt) GetChangeAmount() int32 {
	if x != nil {
		return x.ChangeAmount
	}
	return 0
}

func (x *TransactionResponseDeleteAt) GetPaymentStatus() string {
	if x != nil {
		return x.PaymentStatus
	}
	return ""
}

func (x *TransactionResponseDeleteAt) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TransactionResponseDeleteAt) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *TransactionResponseDeleteAt) GetDeletedAt() *wrapperspb.StringValue {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type ApiResponseTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *TransactionResponse   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTransaction) Reset() {
	*x = ApiResponseTransaction{}
	mi := &file_transaction_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTransaction) ProtoMessage() {}

func (x *ApiResponseTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTransaction.ProtoReflect.Descriptor instead.
func (*ApiResponseTransaction) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{21}
}

func (x *ApiResponseTransaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTransaction) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseTransaction) GetData() *TransactionResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseTransactionDeleteAt struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Status        string                       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *TransactionResponseDeleteAt `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTransactionDeleteAt) Reset() {
	*x = ApiResponseTransactionDeleteAt{}
	mi := &file_transaction_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTransactionDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTransactionDeleteAt) ProtoMessage() {}

func (x *ApiResponseTransactionDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTransactionDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponseTransactionDeleteAt) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{22}
}

func (x *ApiResponseTransactionDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTransactionDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseTransactionDeleteAt) GetData() *TransactionResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseTransactionMonthAmountSuccess struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Status        string                             `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                             `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*TransactionMonthlyAmountSuccess `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTransactionMonthAmountSuccess) Reset() {
	*x = ApiResponseTransactionMonthAmountSuccess{}
	mi := &file_transaction_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTransactionMonthAmountSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTransactionMonthAmountSuccess) ProtoMessage() {}

func (x *ApiResponseTransactionMonthAmountSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTransactionMonthAmountSuccess.ProtoReflect.Descriptor instead.
func (*ApiResponseTransactionMonthAmountSuccess) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{23}
}

func (x *ApiResponseTransactionMonthAmountSuccess) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTransactionMonthAmountSuccess) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseTransactionMonthAmountSuccess) GetData() []*TransactionMonthlyAmountSuccess {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseTransactionYearAmountSuccess struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        string                            `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*TransactionYearlyAmountSuccess `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTransactionYearAmountSuccess) Reset() {
	*x = ApiResponseTransactionYearAmountSuccess{}
	mi := &file_transaction_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTransactionYearAmountSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTransactionYearAmountSuccess) ProtoMessage() {}

func (x *ApiResponseTransactionYearAmountSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTransactionYearAmountSuccess.ProtoReflect.Descriptor instead.
func (*ApiResponseTransactionYearAmountSuccess) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{24}
}

func (x *ApiResponseTransactionYearAmountSuccess) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTransactionYearAmountSuccess) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseTransactionYearAmountSuccess) GetData() []*TransactionYearlyAmountSuccess {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseTransactionMonthAmountFailed struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        string                            `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*TransactionMonthlyAmountFailed `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTransactionMonthAmountFailed) Reset() {
	*x = ApiResponseTransactionMonthAmountFailed{}
	mi := &file_transaction_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTransactionMonthAmountFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTransactionMonthAmountFailed) ProtoMessage() {}

func (x *ApiResponseTransactionMonthAmountFailed) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTransactionMonthAmountFailed.ProtoReflect.Descriptor instead.
func (*ApiResponseTransactionMonthAmountFailed) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{25}
}

func (x *ApiResponseTransactionMonthAmountFailed) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTransactionMonthAmountFailed) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseTransactionMonthAmountFailed) GetData() []*TransactionMonthlyAmountFailed {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseTransactionYearAmountFailed struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Status        string                           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*TransactionYearlyAmountFailed `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTransactionYearAmountFailed) Reset() {
	*x = ApiResponseTransactionYearAmountFailed{}
	mi := &file_transaction_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTransactionYearAmountFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTransactionYearAmountFailed) ProtoMessage() {}

func (x *ApiResponseTransactionYearAmountFailed) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTransactionYearAmountFailed.ProtoReflect.Descriptor instead.
func (*ApiResponseTransactionYearAmountFailed) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{26}
}

func (x *ApiResponseTransactionYearAmountFailed) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTransactionYearAmountFailed) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseTransactionYearAmountFailed) GetData() []*TransactionYearlyAmountFailed {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseTransactionMonthPaymentMethod struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Status        string                      `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*TransactionMonthlyMethod `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTransactionMonthPaymentMethod) Reset() {
	*x = ApiResponseTransactionMonthPaymentMethod{}
	mi := &file_transaction_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTransactionMonthPaymentMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTransactionMonthPaymentMethod) ProtoMessage() {}

func (x *ApiResponseTransactionMonthPaymentMethod) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTransactionMonthPaymentMethod.ProtoReflect.Descriptor instead.
func (*ApiResponseTransactionMonthPaymentMethod) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{27}
}

func (x *ApiResponseTransactionMonthPaymentMethod) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTransactionMonthPaymentMethod) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseTransactionMonthPaymentMethod) GetData() []*TransactionMonthlyMethod {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseTransactionYearPaymentmethod struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Status        string                     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*TransactionYearlyMethod `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTransactionYearPaymentmethod) Reset() {
	*x = ApiResponseTransactionYearPaymentmethod{}
	mi := &file_transaction_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTransactionYearPaymentmethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTransactionYearPaymentmethod) ProtoMessage() {}

func (x *ApiResponseTransactionYearPaymentmethod) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTransactionYearPaymentmethod.ProtoReflect.Descriptor instead.
func (*ApiResponseTransactionYearPaymentmethod) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{28}
}

func (x *ApiResponseTransactionYearPaymentmethod) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTransactionYearPaymentmethod) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseTransactionYearPaymentmethod) GetData() []*TransactionYearlyMethod {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponsesTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*TransactionResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsesTransaction) Reset() {
	*x = ApiResponsesTransaction{}
	mi := &file_transaction_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsesTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsesTransaction) ProtoMessage() {}

func (x *ApiResponsesTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsesTransaction.ProtoReflect.Descriptor instead.
func (*ApiResponsesTransaction) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{29}
}

func (x *ApiResponsesTransaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsesTransaction) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsesTransaction) GetData() []*TransactionResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseTransactionDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTransactionDelete) Reset() {
	*x = ApiResponseTransactionDelete{}
	mi := &file_transaction_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTransactionDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTransactionDelete) ProtoMessage() {}

func (x *ApiResponseTransactionDelete) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTransactionDelete.ProtoReflect.Descriptor instead.
func (*ApiResponseTransactionDelete) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{30}
}

func (x *ApiResponseTransactionDelete) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTransactionDelete) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponseTransactionAll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTransactionAll) Reset() {
	*x = ApiResponseTransactionAll{}
	mi := &file_transaction_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTransactionAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTransactionAll) ProtoMessage() {}

func (x *ApiResponseTransactionAll) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTransactionAll.ProtoReflect.Descriptor instead.
func (*ApiResponseTransactionAll) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{31}
}

func (x *ApiResponseTransactionAll) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTransactionAll) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponsePaginationTransactionDeleteAt struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Status        string                         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*TransactionResponseDeleteAt `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *PaginationMeta                `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationTransactionDeleteAt) Reset() {
	*x = ApiResponsePaginationTransactionDeleteAt{}
	mi := &file_transaction_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationTransactionDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationTransactionDeleteAt) ProtoMessage() {}

func (x *ApiResponsePaginationTransactionDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationTransactionDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationTransactionDeleteAt) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{32}
}

func (x *ApiResponsePaginationTransactionDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationTransactionDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationTransactionDeleteAt) GetData() []*TransactionResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationTransactionDeleteAt) GetPagination() *PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ApiResponsePaginationTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*TransactionResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *PaginationMeta        `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationTransaction) Reset() {
	*x = ApiResponsePaginationTransaction{}
	mi := &file_transaction_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationTransaction) ProtoMessage() {}

func (x *ApiResponsePaginationTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationTransaction.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationTransaction) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{33}
}

func (x *ApiResponsePaginationTransaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationTransaction) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationTransaction) GetData() []*TransactionResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationTransaction) GetPagination() *PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_transaction_proto protoreflect.FileDescriptor

const file_transaction_proto_rawDesc = "" +
	"\n" +
	"\x11transaction.proto\x12\x02pb\x1a\tapi.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\"d\n" +
	"\x19FindAllTransactionRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"\x8d\x01\n" +
	"!FindAllTransactionMerchantRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\x05R\n" +
	"merchantId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\"H\n" +
	"\x1cFindMonthlyTransactionStatus\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\"G\n" +
	"\x1bFindYearlyTransactionStatus\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\"s\n" +
	"&FindMonthlyTransactionStatusByMerchant\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\x05R\n" +
	"merchantId\"\\\n" +
	"%FindYearlyTransactionStatusByMerchant\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\x05R\n" +
	"merchantId\"+\n" +
	"\x15YearTransactionMethod\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\"B\n" +
	"\x16MonthTransactionMethod\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\"m\n" +
	" MonthTransactionMethodByMerchant\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\x05R\n" +
	"merchantId\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x03 \x01(\x05R\x05month\"V\n" +
	"\x1fYearTransactionMethodByMerchant\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\x05R\n" +
	"merchantId\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\",\n" +
	"\x1aFindByIdTransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xba\x01\n" +
	"\x18CreateTransactionRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x05R\aorderId\x12\x1d\n" +
	"\n" +
	"cashier_id\x18\x02 \x01(\x05R\tcashierId\x12%\n" +
	"\x0epayment_method\x18\x03 \x01(\tR\rpaymentMethod\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x05R\x06amount\x12%\n" +
	"\x0epayment_status\x18\x05 \x01(\tR\rpaymentStatus\"\xe1\x01\n" +
	"\x18UpdateTransactionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\x05R\rtransactionId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x05R\aorderId\x12\x1d\n" +
	"\n" +
	"cashier_id\x18\x03 \x01(\x05R\tcashierId\x12%\n" +
	"\x0epayment_method\x18\x04 \x01(\tR\rpaymentMethod\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x05R\x06amount\x12%\n" +
	"\x0epayment_status\x18\x06 \x01(\tR\rpaymentStatus\"\x93\x01\n" +
	"\x1fTransactionMonthlyAmountSuccess\x12\x12\n" +
	"\x04year\x18\x01 \x01(\tR\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\tR\x05month\x12#\n" +
	"\rtotal_success\x18\x03 \x01(\x05R\ftotalSuccess\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x05R\vtotalAmount\"\x90\x01\n" +
	"\x1eTransactionMonthlyAmountFailed\x12\x12\n" +
	"\x04year\x18\x01 \x01(\tR\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\tR\x05month\x12!\n" +
	"\ftotal_failed\x18\x03 \x01(\x05R\vtotalFailed\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x05R\vtotalAmount\"|\n" +
	"\x1eTransactionYearlyAmountSuccess\x12\x12\n" +
	"\x04year\x18\x01 \x01(\tR\x04year\x12#\n" +
	"\rtotal_success\x18\x02 \x01(\x05R\ftotalSuccess\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x05R\vtotalAmount\"y\n" +
	"\x1dTransactionYearlyAmountFailed\x12\x12\n" +
	"\x04year\x18\x01 \x01(\tR\x04year\x12!\n" +
	"\ftotal_failed\x18\x02 \x01(\x05R\vtotalFailed\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x05R\vtotalAmount\"\xa9\x01\n" +
	"\x18TransactionMonthlyMethod\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12%\n" +
	"\x0epayment_method\x18\x02 \x01(\tR\rpaymentMethod\x12-\n" +
	"\x12total_transactions\x18\x03 \x01(\x05R\x11totalTransactions\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x05R\vtotalAmount\"\xa6\x01\n" +
	"\x17TransactionYearlyMethod\x12\x12\n" +
	"\x04year\x18\x01 \x01(\tR\x04year\x12%\n" +
	"\x0epayment_method\x18\x02 \x01(\tR\rpaymentMethod\x12-\n" +
	"\x12total_transactions\x18\x03 \x01(\x05R\x11totalTransactions\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x05R\vtotalAmount\"\xaa\x02\n" +
	"\x13TransactionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x05R\aorderId\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\x05R\n" +
	"merchantId\x12%\n" +
	"\x0epayment_method\x18\x04 \x01(\tR\rpaymentMethod\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x05R\x06amount\x12#\n" +
	"\rchange_amount\x18\x06 \x01(\x05R\fchangeAmount\x12%\n" +
	"\x0epayment_status\x18\a \x01(\tR\rpaymentStatus\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"\xef\x02\n" +
	"\x1bTransactionResponseDeleteAt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x05R\aorderId\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\x05R\n" +
	"merchantId\x12%\n" +
	"\x0epayment_method\x18\x04 \x01(\tR\rpaymentMethod\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x05R\x06amount\x12#\n" +
	"\rchange_amount\x18\x06 \x01(\x05R\fchangeAmount\x12%\n" +
	"\x0epayment_status\x18\a \x01(\tR\rpaymentStatus\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\x12;\n" +
	"\n" +
	"deleted_at\x18\n" +
	" \x01(\v2\x1c.google.protobuf.StringValueR\tdeletedAt\"w\n" +
	"\x16ApiResponseTransaction\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.pb.TransactionResponseR\x04data\"\x87\x01\n" +
	"\x1eApiResponseTransactionDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x123\n" +
	"\x04data\x18\x03 \x01(\v2\x1f.pb.TransactionResponseDeleteAtR\x04data\"\x95\x01\n" +
	"(ApiResponseTransactionMonthAmountSuccess\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x127\n" +
	"\x04data\x18\x03 \x03(\v2#.pb.TransactionMonthlyAmountSuccessR\x04data\"\x93\x01\n" +
	"'ApiResponseTransactionYearAmountSuccess\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x126\n" +
	"\x04data\x18\x03 \x03(\v2\".pb.TransactionYearlyAmountSuccessR\x04data\"\x93\x01\n" +
	"'ApiResponseTransactionMonthAmountFailed\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x126\n" +
	"\x04data\x18\x03 \x03(\v2\".pb.TransactionMonthlyAmountFailedR\x04data\"\x91\x01\n" +
	"&ApiResponseTransactionYearAmountFailed\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x125\n" +
	"\x04data\x18\x03 \x03(\v2!.pb.TransactionYearlyAmountFailedR\x04data\"\x8e\x01\n" +
	"(ApiResponseTransactionMonthPaymentMethod\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\x04data\x18\x03 \x03(\v2\x1c.pb.TransactionMonthlyMethodR\x04data\"\x8c\x01\n" +
	"'ApiResponseTransactionYearPaymentmethod\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\x04data\x18\x03 \x03(\v2\x1b.pb.TransactionYearlyMethodR\x04data\"x\n" +
	"\x17ApiResponsesTransaction\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x04data\x18\x03 \x03(\v2\x17.pb.TransactionResponseR\x04data\"P\n" +
	"\x1cApiResponseTransactionDelete\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"M\n" +
	"\x19ApiResponseTransactionAll\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc5\x01\n" +
	"(ApiResponsePaginationTransactionDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x123\n" +
	"\x04data\x18\x03 \x03(\v2\x1f.pb.TransactionResponseDeleteAtR\x04data\x122\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x12.pb.PaginationMetaR\n" +
	"pagination\"\xb5\x01\n" +
	" ApiResponsePaginationTransaction\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x04data\x18\x03 \x03(\v2\x17.pb.TransactionResponseR\x04data\x122\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x12.pb.PaginationMetaR\n" +
	"pagination2\xfe\x15\n" +
	"\x12TransactionService\x12N\n" +
	"\aFindAll\x12\x1d.pb.FindAllTransactionRequest\x1a$.pb.ApiResponsePaginationTransaction\x12]\n" +
	"\x0eFindByMerchant\x12%.pb.FindAllTransactionMerchantRequest\x1a$.pb.ApiResponsePaginationTransaction\x12F\n" +
	"\bFindById\x12\x1e.pb.FindByIdTransactionRequest\x1a\x1a.pb.ApiResponseTransaction\x12h\n" +
	"\x16FindMonthStatusSuccess\x12 .pb.FindMonthlyTransactionStatus\x1a,.pb.ApiResponseTransactionMonthAmountSuccess\x12e\n" +
	"\x15FindYearStatusSuccess\x12\x1f.pb.FindYearlyTransactionStatus\x1a+.pb.ApiResponseTransactionYearAmountSuccess\x12f\n" +
	"\x15FindMonthStatusFailed\x12 .pb.FindMonthlyTransactionStatus\x1a+.pb.ApiResponseTransactionMonthAmountFailed\x12c\n" +
	"\x14FindYearStatusFailed\x12\x1f.pb.FindYearlyTransactionStatus\x1a*.pb.ApiResponseTransactionYearAmountFailed\x12|\n" +
	" FindMonthStatusSuccessByMerchant\x12*.pb.FindMonthlyTransactionStatusByMerchant\x1a,.pb.ApiResponseTransactionMonthAmountSuccess\x12y\n" +
	"\x1fFindYearStatusSuccessByMerchant\x12).pb.FindYearlyTransactionStatusByMerchant\x1a+.pb.ApiResponseTransactionYearAmountSuccess\x12z\n" +
	"\x1fFindMonthStatusFailedByMerchant\x12*.pb.FindMonthlyTransactionStatusByMerchant\x1a+.pb.ApiResponseTransactionMonthAmountFailed\x12w\n" +
	"\x1eFindYearStatusFailedByMerchant\x12).pb.FindYearlyTransactionStatusByMerchant\x1a*.pb.ApiResponseTransactionYearAmountFailed\x12b\n" +
	"\x16FindMonthMethodSuccess\x12\x1a.pb.MonthTransactionMethod\x1a,.pb.ApiResponseTransactionMonthPaymentMethod\x12_\n" +
	"\x15FindYearMethodSuccess\x12\x19.pb.YearTransactionMethod\x1a+.pb.ApiResponseTransactionYearPaymentmethod\x12v\n" +
	" FindMonthMethodByMerchantSuccess\x12$.pb.MonthTransactionMethodByMerchant\x1a,.pb.ApiResponseTransactionMonthPaymentMethod\x12s\n" +
	"\x1fFindYearMethodByMerchantSuccess\x12#.pb.YearTransactionMethodByMerchant\x1a+.pb.ApiResponseTransactionYearPaymentmethod\x12a\n" +
	"\x15FindMonthMethodFailed\x12\x1a.pb.MonthTransactionMethod\x1a,.pb.ApiResponseTransactionMonthPaymentMethod\x12^\n" +
	"\x14FindYearMethodFailed\x12\x19.pb.YearTransactionMethod\x1a+.pb.ApiResponseTransactionYearPaymentmethod\x12u\n" +
	"\x1fFindMonthMethodByMerchantFailed\x12$.pb.MonthTransactionMethodByMerchant\x1a,.pb.ApiResponseTransactionMonthPaymentMethod\x12r\n" +
	"\x1eFindYearMethodByMerchantFailed\x12#.pb.YearTransactionMethodByMerchant\x1a+.pb.ApiResponseTransactionYearPaymentmethod\x12]\n" +
	"\fFindByActive\x12\x1d.pb.FindAllTransactionRequest\x1a,.pb.ApiResponsePaginationTransactionDeleteAt\"\x00\x12^\n" +
	"\rFindByTrashed\x12\x1d.pb.FindAllTransactionRequest\x1a,.pb.ApiResponsePaginationTransactionDeleteAt\"\x00\x12B\n" +
	"\x06Create\x12\x1c.pb.CreateTransactionRequest\x1a\x1a.pb.ApiResponseTransaction\x12B\n" +
	"\x06Update\x12\x1c.pb.UpdateTransactionRequest\x1a\x1a.pb.ApiResponseTransaction\x12X\n" +
	"\x12TrashedTransaction\x12\x1e.pb.FindByIdTransactionRequest\x1a\".pb.ApiResponseTransactionDeleteAt\x12X\n" +
	"\x12RestoreTransaction\x12\x1e.pb.FindByIdTransactionRequest\x1a\".pb.ApiResponseTransactionDeleteAt\x12^\n" +
	"\x1aDeleteTransactionPermanent\x12\x1e.pb.FindByIdTransactionRequest\x1a .pb.ApiResponseTransactionDelete\x12P\n" +
	"\x15RestoreAllTransaction\x12\x16.google.protobuf.Empty\x1a\x1d.pb.ApiResponseTransactionAll\"\x00\x12X\n" +
	"\x1dDeleteAllTransactionPermanent\x12\x16.google.protobuf.Empty\x1a\x1d.pb.ApiResponseTransactionAll\"\x00B<Z:github.com/MamangRust/pointofsale-graphql-grpc/internal/pbb\x06proto3"

var (
	file_transaction_proto_rawDescOnce sync.Once
	file_transaction_proto_rawDescData []byte
)

func file_transaction_proto_rawDescGZIP() []byte {
	file_transaction_proto_rawDescOnce.Do(func() {
		file_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_proto_rawDesc), len(file_transaction_proto_rawDesc)))
	})
	return file_transaction_proto_rawDescData
}

var file_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_transaction_proto_goTypes = []any{
	(*FindAllTransactionRequest)(nil),                // 0: pb.FindAllTransactionRequest
	(*FindAllTransactionMerchantRequest)(nil),        // 1: pb.FindAllTransactionMerchantRequest
	(*FindMonthlyTransactionStatus)(nil),             // 2: pb.FindMonthlyTransactionStatus
	(*FindYearlyTransactionStatus)(nil),              // 3: pb.FindYearlyTransactionStatus
	(*FindMonthlyTransactionStatusByMerchant)(nil),   // 4: pb.FindMonthlyTransactionStatusByMerchant
	(*FindYearlyTransactionStatusByMerchant)(nil),    // 5: pb.FindYearlyTransactionStatusByMerchant
	(*YearTransactionMethod)(nil),                    // 6: pb.YearTransactionMethod
	(*MonthTransactionMethod)(nil),                   // 7: pb.MonthTransactionMethod
	(*MonthTransactionMethodByMerchant)(nil),         // 8: pb.MonthTransactionMethodByMerchant
	(*YearTransactionMethodByMerchant)(nil),          // 9: pb.YearTransactionMethodByMerchant
	(*FindByIdTransactionRequest)(nil),               // 10: pb.FindByIdTransactionRequest
	(*CreateTransactionRequest)(nil),                 // 11: pb.CreateTransactionRequest
	(*UpdateTransactionRequest)(nil),                 // 12: pb.UpdateTransactionRequest
	(*TransactionMonthlyAmountSuccess)(nil),          // 13: pb.TransactionMonthlyAmountSuccess
	(*TransactionMonthlyAmountFailed)(nil),           // 14: pb.TransactionMonthlyAmountFailed
	(*TransactionYearlyAmountSuccess)(nil),           // 15: pb.TransactionYearlyAmountSuccess
	(*TransactionYearlyAmountFailed)(nil),            // 16: pb.TransactionYearlyAmountFailed
	(*TransactionMonthlyMethod)(nil),                 // 17: pb.TransactionMonthlyMethod
	(*TransactionYearlyMethod)(nil),                  // 18: pb.TransactionYearlyMethod
	(*TransactionResponse)(nil),                      // 19: pb.TransactionResponse
	(*TransactionResponseDeleteAt)(nil),              // 20: pb.TransactionResponseDeleteAt
	(*ApiResponseTransaction)(nil),                   // 21: pb.ApiResponseTransaction
	(*ApiResponseTransactionDeleteAt)(nil),           // 22: pb.ApiResponseTransactionDeleteAt
	(*ApiResponseTransactionMonthAmountSuccess)(nil), // 23: pb.ApiResponseTransactionMonthAmountSuccess
	(*ApiResponseTransactionYearAmountSuccess)(nil),  // 24: pb.ApiResponseTransactionYearAmountSuccess
	(*ApiResponseTransactionMonthAmountFailed)(nil),  // 25: pb.ApiResponseTransactionMonthAmountFailed
	(*ApiResponseTransactionYearAmountFailed)(nil),   // 26: pb.ApiResponseTransactionYearAmountFailed
	(*ApiResponseTransactionMonthPaymentMethod)(nil), // 27: pb.ApiResponseTransactionMonthPaymentMethod
	(*ApiResponseTransactionYearPaymentmethod)(nil),  // 28: pb.ApiResponseTransactionYearPaymentmethod
	(*ApiResponsesTransaction)(nil),                  // 29: pb.ApiResponsesTransaction
	(*ApiResponseTransactionDelete)(nil),             // 30: pb.ApiResponseTransactionDelete
	(*ApiResponseTransactionAll)(nil),                // 31: pb.ApiResponseTransactionAll
	(*ApiResponsePaginationTransactionDeleteAt)(nil), // 32: pb.ApiResponsePaginationTransactionDeleteAt
	(*ApiResponsePaginationTransaction)(nil),         // 33: pb.ApiResponsePaginationTransaction
	(*wrapperspb.StringValue)(nil),                   // 34: google.protobuf.StringValue
	(*PaginationMeta)(nil),                           // 35: pb.PaginationMeta
	(*emptypb.Empty)(nil),                            // 36: google.protobuf.Empty
}
var file_transaction_proto_depIdxs = []int32{
	34, // 0: pb.TransactionResponseDeleteAt.deleted_at:type_name -> google.protobuf.StringValue
	19, // 1: pb.ApiResponseTransaction.data:type_name -> pb.TransactionResponse
	20, // 2: pb.ApiResponseTransactionDeleteAt.data:type_name -> pb.TransactionResponseDeleteAt
	13, // 3: pb.ApiResponseTransactionMonthAmountSuccess.data:type_name -> pb.TransactionMonthlyAmountSuccess
	15, // 4: pb.ApiResponseTransactionYearAmountSuccess.data:type_name -> pb.TransactionYearlyAmountSuccess
	14, // 5: pb.ApiResponseTransactionMonthAmountFailed.data:type_name -> pb.TransactionMonthlyAmountFailed
	16, // 6: pb.ApiResponseTransactionYearAmountFailed.data:type_name -> pb.TransactionYearlyAmountFailed
	17, // 7: pb.ApiResponseTransactionMonthPaymentMethod.data:type_name -> pb.TransactionMonthlyMethod
	18, // 8: pb.ApiResponseTransactionYearPaymentmethod.data:type_name -> pb.TransactionYearlyMethod
	19, // 9: pb.ApiResponsesTransaction.data:type_name -> pb.TransactionResponse
	20, // 10: pb.ApiResponsePaginationTransactionDeleteAt.data:type_name -> pb.TransactionResponseDeleteAt
	35, // 11: pb.ApiResponsePaginationTransactionDeleteAt.pagination:type_name -> pb.PaginationMeta
	19, // 12: pb.ApiResponsePaginationTransaction.data:type_name -> pb.TransactionResponse
	35, // 13: pb.ApiResponsePaginationTransaction.pagination:type_name -> pb.PaginationMeta
	0,  // 14: pb.TransactionService.FindAll:input_type -> pb.FindAllTransactionRequest
	1,  // 15: pb.TransactionService.FindByMerchant:input_type -> pb.FindAllTransactionMerchantRequest
	10, // 16: pb.TransactionService.FindById:input_type -> pb.FindByIdTransactionRequest
	2,  // 17: pb.TransactionService.FindMonthStatusSuccess:input_type -> pb.FindMonthlyTransactionStatus
	3,  // 18: pb.TransactionService.FindYearStatusSuccess:input_type -> pb.FindYearlyTransactionStatus
	2,  // 19: pb.TransactionService.FindMonthStatusFailed:input_type -> pb.FindMonthlyTransactionStatus
	3,  // 20: pb.TransactionService.FindYearStatusFailed:input_type -> pb.FindYearlyTransactionStatus
	4,  // 21: pb.TransactionService.FindMonthStatusSuccessByMerchant:input_type -> pb.FindMonthlyTransactionStatusByMerchant
	5,  // 22: pb.TransactionService.FindYearStatusSuccessByMerchant:input_type -> pb.FindYearlyTransactionStatusByMerchant
	4,  // 23: pb.TransactionService.FindMonthStatusFailedByMerchant:input_type -> pb.FindMonthlyTransactionStatusByMerchant
	5,  // 24: pb.TransactionService.FindYearStatusFailedByMerchant:input_type -> pb.FindYearlyTransactionStatusByMerchant
	7,  // 25: pb.TransactionService.FindMonthMethodSuccess:input_type -> pb.MonthTransactionMethod
	6,  // 26: pb.TransactionService.FindYearMethodSuccess:input_type -> pb.YearTransactionMethod
	8,  // 27: pb.TransactionService.FindMonthMethodByMerchantSuccess:input_type -> pb.MonthTransactionMethodByMerchant
	9,  // 28: pb.TransactionService.FindYearMethodByMerchantSuccess:input_type -> pb.YearTransactionMethodByMerchant
	7,  // 29: pb.TransactionService.FindMonthMethodFailed:input_type -> pb.MonthTransactionMethod
	6,  // 30: pb.TransactionService.FindYearMethodFailed:input_type -> pb.YearTransactionMethod
	8,  // 31: pb.TransactionService.FindMonthMethodByMerchantFailed:input_type -> pb.MonthTransactionMethodByMerchant
	9,  // 32: pb.TransactionService.FindYearMethodByMerchantFailed:input_type -> pb.YearTransactionMethodByMerchant
	0,  // 33: pb.TransactionService.FindByActive:input_type -> pb.FindAllTransactionRequest
	0,  // 34: pb.TransactionService.FindByTrashed:input_type -> pb.FindAllTransactionRequest
	11, // 35: pb.TransactionService.Create:input_type -> pb.CreateTransactionRequest
	12, // 36: pb.TransactionService.Update:input_type -> pb.UpdateTransactionRequest
	10, // 37: pb.TransactionService.TrashedTransaction:input_type -> pb.FindByIdTransactionRequest
	10, // 38: pb.TransactionService.RestoreTransaction:input_type -> pb.FindByIdTransactionRequest
	10, // 39: pb.TransactionService.DeleteTransactionPermanent:input_type -> pb.FindByIdTransactionRequest
	36, // 40: pb.TransactionService.RestoreAllTransaction:input_type -> google.protobuf.Empty
	36, // 41: pb.TransactionService.DeleteAllTransactionPermanent:input_type -> google.protobuf.Empty
	33, // 42: pb.TransactionService.FindAll:output_type -> pb.ApiResponsePaginationTransaction
	33, // 43: pb.TransactionService.FindByMerchant:output_type -> pb.ApiResponsePaginationTransaction
	21, // 44: pb.TransactionService.FindById:output_type -> pb.ApiResponseTransaction
	23, // 45: pb.TransactionService.FindMonthStatusSuccess:output_type -> pb.ApiResponseTransactionMonthAmountSuccess
	24, // 46: pb.TransactionService.FindYearStatusSuccess:output_type -> pb.ApiResponseTransactionYearAmountSuccess
	25, // 47: pb.TransactionService.FindMonthStatusFailed:output_type -> pb.ApiResponseTransactionMonthAmountFailed
	26, // 48: pb.TransactionService.FindYearStatusFailed:output_type -> pb.ApiResponseTransactionYearAmountFailed
	23, // 49: pb.TransactionService.FindMonthStatusSuccessByMerchant:output_type -> pb.ApiResponseTransactionMonthAmountSuccess
	24, // 50: pb.TransactionService.FindYearStatusSuccessByMerchant:output_type -> pb.ApiResponseTransactionYearAmountSuccess
	25, // 51: pb.TransactionService.FindMonthStatusFailedByMerchant:output_type -> pb.ApiResponseTransactionMonthAmountFailed
	26, // 52: pb.TransactionService.FindYearStatusFailedByMerchant:output_type -> pb.ApiResponseTransactionYearAmountFailed
	27, // 53: pb.TransactionService.FindMonthMethodSuccess:output_type -> pb.ApiResponseTransactionMonthPaymentMethod
	28, // 54: pb.TransactionService.FindYearMethodSuccess:output_type -> pb.ApiResponseTransactionYearPaymentmethod
	27, // 55: pb.TransactionService.FindMonthMethodByMerchantSuccess:output_type -> pb.ApiResponseTransactionMonthPaymentMethod
	28, // 56: pb.TransactionService.FindYearMethodByMerchantSuccess:output_type -> pb.ApiResponseTransactionYearPaymentmethod
	27, // 57: pb.TransactionService.FindMonthMethodFailed:output_type -> pb.ApiResponseTransactionMonthPaymentMethod
	28, // 58: pb.TransactionService.FindYearMethodFailed:output_type -> pb.ApiResponseTransactionYearPaymentmethod
	27, // 59: pb.TransactionService.FindMonthMethodByMerchantFailed:output_type -> pb.ApiResponseTransactionMonthPaymentMethod
	28, // 60: pb.TransactionService.FindYearMethodByMerchantFailed:output_type -> pb.ApiResponseTransactionYearPaymentmethod
	32, // 61: pb.TransactionService.FindByActive:output_type -> pb.ApiResponsePaginationTransactionDeleteAt
	32, // 62: pb.TransactionService.FindByTrashed:output_type -> pb.ApiResponsePaginationTransactionDeleteAt
	21, // 63: pb.TransactionService.Create:output_type -> pb.ApiResponseTransaction
	21, // 64: pb.TransactionService.Update:output_type -> pb.ApiResponseTransaction
	22, // 65: pb.TransactionService.TrashedTransaction:output_type -> pb.ApiResponseTransactionDeleteAt
	22, // 66: pb.TransactionService.RestoreTransaction:output_type -> pb.ApiResponseTransactionDeleteAt
	30, // 67: pb.TransactionService.DeleteTransactionPermanent:output_type -> pb.ApiResponseTransactionDelete
	31, // 68: pb.TransactionService.RestoreAllTransaction:output_type -> pb.ApiResponseTransactionAll
	31, // 69: pb.TransactionService.DeleteAllTransactionPermanent:output_type -> pb.ApiResponseTransactionAll
	42, // [42:70] is the sub-list for method output_type
	14, // [14:42] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_transaction_proto_init() }
func file_transaction_proto_init() {
	if File_transaction_proto != nil {
		return
	}
	file_api_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_proto_rawDesc), len(file_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_proto_goTypes,
		DependencyIndexes: file_transaction_proto_depIdxs,
		MessageInfos:      file_transaction_proto_msgTypes,
	}.Build()
	File_transaction_proto = out.File
	file_transaction_proto_goTypes = nil
	file_transaction_proto_depIdxs = nil
}
