package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	"github.com/MamangRust/pointofsale-graphql-grpc/internal/model"
)

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input model.CreateOrderInput) (*model.APIResponseOrder, error) {
	panic(fmt.Errorf("not implemented: CreateOrder - createOrder"))
}

// UpdateOrder is the resolver for the updateOrder field.
func (r *mutationResolver) UpdateOrder(ctx context.Context, input model.UpdateOrderInput) (*model.APIResponseOrder, error) {
	panic(fmt.Errorf("not implemented: UpdateOrder - updateOrder"))
}

// TrashedOrder is the resolver for the trashedOrder field.
func (r *mutationResolver) TrashedOrder(ctx context.Context, input model.FindByIDOrderInput) (*model.APIResponseOrderDeleteAt, error) {
	panic(fmt.Errorf("not implemented: TrashedOrder - trashedOrder"))
}

// RestoreOrder is the resolver for the restoreOrder field.
func (r *mutationResolver) RestoreOrder(ctx context.Context, input model.FindByIDOrderInput) (*model.APIResponseOrderDeleteAt, error) {
	panic(fmt.Errorf("not implemented: RestoreOrder - restoreOrder"))
}

// DeleteOrderPermanent is the resolver for the deleteOrderPermanent field.
func (r *mutationResolver) DeleteOrderPermanent(ctx context.Context, input model.FindByIDOrderInput) (*model.APIResponseOrderDelete, error) {
	panic(fmt.Errorf("not implemented: DeleteOrderPermanent - deleteOrderPermanent"))
}

// RestoreAllOrder is the resolver for the restoreAllOrder field.
func (r *mutationResolver) RestoreAllOrder(ctx context.Context) (*model.APIResponseOrderAll, error) {
	panic(fmt.Errorf("not implemented: RestoreAllOrder - restoreAllOrder"))
}

// DeleteAllOrderPermanent is the resolver for the deleteAllOrderPermanent field.
func (r *mutationResolver) DeleteAllOrderPermanent(ctx context.Context) (*model.APIResponseOrderAll, error) {
	panic(fmt.Errorf("not implemented: DeleteAllOrderPermanent - deleteAllOrderPermanent"))
}

// FindMonthlyTotalRevenue is the resolver for the findMonthlyTotalRevenue field.
func (r *queryResolver) FindMonthlyTotalRevenue(ctx context.Context, input model.FindYearMonthTotalRevenueInput) (*model.APIResponseOrderMonthlyTotalRevenue, error) {
	panic(fmt.Errorf("not implemented: FindMonthlyTotalRevenue - findMonthlyTotalRevenue"))
}

// FindYearlyTotalRevenue is the resolver for the findYearlyTotalRevenue field.
func (r *queryResolver) FindYearlyTotalRevenue(ctx context.Context, input model.FindYearTotalRevenueInput) (*model.APIResponseOrderYearlyTotalRevenue, error) {
	panic(fmt.Errorf("not implemented: FindYearlyTotalRevenue - findYearlyTotalRevenue"))
}

// FindMonthlyTotalRevenueByID is the resolver for the findMonthlyTotalRevenueById field.
func (r *queryResolver) FindMonthlyTotalRevenueByID(ctx context.Context, input model.FindYearMonthTotalRevenueByIDInput) (*model.APIResponseOrderMonthlyTotalRevenue, error) {
	panic(fmt.Errorf("not implemented: FindMonthlyTotalRevenueByID - findMonthlyTotalRevenueById"))
}

// FindYearlyTotalRevenueByID is the resolver for the findYearlyTotalRevenueById field.
func (r *queryResolver) FindYearlyTotalRevenueByID(ctx context.Context, input model.FindYearTotalRevenueByIDInput) (*model.APIResponseOrderYearlyTotalRevenue, error) {
	panic(fmt.Errorf("not implemented: FindYearlyTotalRevenueByID - findYearlyTotalRevenueById"))
}

// FindMonthlyTotalRevenueByMerchant is the resolver for the findMonthlyTotalRevenueByMerchant field.
func (r *queryResolver) FindMonthlyTotalRevenueByMerchant(ctx context.Context, input model.FindYearMonthTotalRevenueByMerchantInput) (*model.APIResponseOrderMonthlyTotalRevenue, error) {
	panic(fmt.Errorf("not implemented: FindMonthlyTotalRevenueByMerchant - findMonthlyTotalRevenueByMerchant"))
}

// FindYearlyTotalRevenueByMerchant is the resolver for the findYearlyTotalRevenueByMerchant field.
func (r *queryResolver) FindYearlyTotalRevenueByMerchant(ctx context.Context, input model.FindYearTotalRevenueByMerchantInput) (*model.APIResponseOrderYearlyTotalRevenue, error) {
	panic(fmt.Errorf("not implemented: FindYearlyTotalRevenueByMerchant - findYearlyTotalRevenueByMerchant"))
}

// FindAllOrder is the resolver for the findAllOrder field.
func (r *queryResolver) FindAllOrder(ctx context.Context, input model.FindAllOrderInput) (*model.APIResponsePaginationOrder, error) {
	panic(fmt.Errorf("not implemented: FindAllOrder - findAllOrder"))
}

// FindByMerchantOrder is the resolver for the findByMerchantOrder field.
func (r *queryResolver) FindByMerchantOrder(ctx context.Context, input model.FindAllOrderMerchantInput) (*model.APIResponsePaginationOrder, error) {
	panic(fmt.Errorf("not implemented: FindByMerchantOrder - findByMerchantOrder"))
}

// FindByIDOrder is the resolver for the findByIdOrder field.
func (r *queryResolver) FindByIDOrder(ctx context.Context, input model.FindByIDOrderInput) (*model.APIResponseOrder, error) {
	panic(fmt.Errorf("not implemented: FindByIDOrder - findByIdOrder"))
}

// FindByActiveOrder is the resolver for the findByActiveOrder field.
func (r *queryResolver) FindByActiveOrder(ctx context.Context, input model.FindAllOrderInput) (*model.APIResponsePaginationOrderDeleteAt, error) {
	panic(fmt.Errorf("not implemented: FindByActiveOrder - findByActiveOrder"))
}

// FindByTrashedOrder is the resolver for the findByTrashedOrder field.
func (r *queryResolver) FindByTrashedOrder(ctx context.Context, input model.FindAllOrderInput) (*model.APIResponsePaginationOrderDeleteAt, error) {
	panic(fmt.Errorf("not implemented: FindByTrashedOrder - findByTrashedOrder"))
}

// FindMonthlyRevenue is the resolver for the findMonthlyRevenue field.
func (r *queryResolver) FindMonthlyRevenue(ctx context.Context, input model.FindYearOrderInput) (*model.APIResponseOrderMonthly, error) {
	panic(fmt.Errorf("not implemented: FindMonthlyRevenue - findMonthlyRevenue"))
}

// FindYearlyRevenue is the resolver for the findYearlyRevenue field.
func (r *queryResolver) FindYearlyRevenue(ctx context.Context, input model.FindYearOrderInput) (*model.APIResponseOrderYearly, error) {
	panic(fmt.Errorf("not implemented: FindYearlyRevenue - findYearlyRevenue"))
}

// FindMonthlyRevenueByMerchant is the resolver for the findMonthlyRevenueByMerchant field.
func (r *queryResolver) FindMonthlyRevenueByMerchant(ctx context.Context, input model.FindYearOrderByMerchantInput) (*model.APIResponseOrderMonthly, error) {
	panic(fmt.Errorf("not implemented: FindMonthlyRevenueByMerchant - findMonthlyRevenueByMerchant"))
}

// FindYearlyRevenueByMerchant is the resolver for the findYearlyRevenueByMerchant field.
func (r *queryResolver) FindYearlyRevenueByMerchant(ctx context.Context, input model.FindYearOrderByMerchantInput) (*model.APIResponseOrderYearly, error) {
	panic(fmt.Errorf("not implemented: FindYearlyRevenueByMerchant - findYearlyRevenueByMerchant"))
}
