package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	"github.com/MamangRust/pointofsale-graphql-grpc/internal/model"
)

// FindAllOrderItem is the resolver for the findAllOrderItem field.
func (r *queryResolver) FindAllOrderItem(ctx context.Context, input model.FindAllOrderItemInput) (*model.APIResponsePaginationOrderItem, error) {
	panic(fmt.Errorf("not implemented: FindAllOrderItem - findAllOrderItem"))
}

// FindByActiveOrderItem is the resolver for the findByActiveOrderItem field.
func (r *queryResolver) FindByActiveOrderItem(ctx context.Context, input model.FindAllOrderItemInput) (*model.APIResponsePaginationOrderItemDeleteAt, error) {
	panic(fmt.Errorf("not implemented: FindByActiveOrderItem - findByActiveOrderItem"))
}

// FindByTrashedOrderItem is the resolver for the findByTrashedOrderItem field.
func (r *queryResolver) FindByTrashedOrderItem(ctx context.Context, input model.FindAllOrderItemInput) (*model.APIResponsePaginationOrderItemDeleteAt, error) {
	panic(fmt.Errorf("not implemented: FindByTrashedOrderItem - findByTrashedOrderItem"))
}

// FindOrderItemByOrder is the resolver for the findOrderItemByOrder field.
func (r *queryResolver) FindOrderItemByOrder(ctx context.Context, input model.FindByIDOrderItemInput) (*model.APIResponsesOrderItem, error) {
	panic(fmt.Errorf("not implemented: FindOrderItemByOrder - findOrderItemByOrder"))
}
