package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	"github.com/MamangRust/pointofsale-graphql-grpc/internal/model"
)

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.CreateProductInput) (*model.APIResponseProduct, error) {
	panic(fmt.Errorf("not implemented: CreateProduct - createProduct"))
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, input model.UpdateProductInput) (*model.APIResponseProduct, error) {
	panic(fmt.Errorf("not implemented: UpdateProduct - updateProduct"))
}

// TrashedProduct is the resolver for the trashedProduct field.
func (r *mutationResolver) TrashedProduct(ctx context.Context, input model.FindByIDProductInput) (*model.APIResponseProductDeleteAt, error) {
	panic(fmt.Errorf("not implemented: TrashedProduct - trashedProduct"))
}

// RestoreProduct is the resolver for the restoreProduct field.
func (r *mutationResolver) RestoreProduct(ctx context.Context, input model.FindByIDProductInput) (*model.APIResponseProductDeleteAt, error) {
	panic(fmt.Errorf("not implemented: RestoreProduct - restoreProduct"))
}

// DeleteProductPermanent is the resolver for the deleteProductPermanent field.
func (r *mutationResolver) DeleteProductPermanent(ctx context.Context, input model.FindByIDProductInput) (*model.APIResponseProductDelete, error) {
	panic(fmt.Errorf("not implemented: DeleteProductPermanent - deleteProductPermanent"))
}

// RestoreAllProduct is the resolver for the restoreAllProduct field.
func (r *mutationResolver) RestoreAllProduct(ctx context.Context) (*model.APIResponseProductAll, error) {
	panic(fmt.Errorf("not implemented: RestoreAllProduct - restoreAllProduct"))
}

// DeleteAllProductPermanent is the resolver for the deleteAllProductPermanent field.
func (r *mutationResolver) DeleteAllProductPermanent(ctx context.Context) (*model.APIResponseProductAll, error) {
	panic(fmt.Errorf("not implemented: DeleteAllProductPermanent - deleteAllProductPermanent"))
}

// FindAllProduct is the resolver for the findAllProduct field.
func (r *queryResolver) FindAllProduct(ctx context.Context, input *model.FindAllProductInput) (*model.APIResponsePaginationProduct, error) {
	panic(fmt.Errorf("not implemented: FindAllProduct - findAllProduct"))
}

// FindByMerchantProduct is the resolver for the findByMerchantProduct field.
func (r *queryResolver) FindByMerchantProduct(ctx context.Context, input model.FindAllProductMerchantInput) (*model.APIResponsePaginationProduct, error) {
	panic(fmt.Errorf("not implemented: FindByMerchantProduct - findByMerchantProduct"))
}

// FindByCategoryProduct is the resolver for the findByCategoryProduct field.
func (r *queryResolver) FindByCategoryProduct(ctx context.Context, input model.FindAllProductCategoryInput) (*model.APIResponsePaginationProduct, error) {
	panic(fmt.Errorf("not implemented: FindByCategoryProduct - findByCategoryProduct"))
}

// FindByIDProduct is the resolver for the findByIdProduct field.
func (r *queryResolver) FindByIDProduct(ctx context.Context, input model.FindByIDProductInput) (*model.APIResponseProduct, error) {
	panic(fmt.Errorf("not implemented: FindByIDProduct - findByIdProduct"))
}

// FindByActiveProduct is the resolver for the findByActiveProduct field.
func (r *queryResolver) FindByActiveProduct(ctx context.Context, input *model.FindAllProductInput) (*model.APIResponsePaginationProductDeleteAt, error) {
	panic(fmt.Errorf("not implemented: FindByActiveProduct - findByActiveProduct"))
}

// FindByTrashedProduct is the resolver for the findByTrashedProduct field.
func (r *queryResolver) FindByTrashedProduct(ctx context.Context, input *model.FindAllProductInput) (*model.APIResponsePaginationProductDeleteAt, error) {
	panic(fmt.Errorf("not implemented: FindByTrashedProduct - findByTrashedProduct"))
}
