package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	"github.com/MamangRust/pointofsale-graphql-grpc/internal/model"
)

// CreateTransaction is the resolver for the createTransaction field.
func (r *mutationResolver) CreateTransaction(ctx context.Context, input model.CreateTransactionInput) (*model.APIResponseTransaction, error) {
	panic(fmt.Errorf("not implemented: CreateTransaction - createTransaction"))
}

// UpdateTransaction is the resolver for the updateTransaction field.
func (r *mutationResolver) UpdateTransaction(ctx context.Context, input model.UpdateTransactionInput) (*model.APIResponseTransaction, error) {
	panic(fmt.Errorf("not implemented: UpdateTransaction - updateTransaction"))
}

// TrashedTransaction is the resolver for the trashedTransaction field.
func (r *mutationResolver) TrashedTransaction(ctx context.Context, input model.FindByIDTransactionInput) (*model.APIResponseTransactionDeleteAt, error) {
	panic(fmt.Errorf("not implemented: TrashedTransaction - trashedTransaction"))
}

// RestoreTransaction is the resolver for the restoreTransaction field.
func (r *mutationResolver) RestoreTransaction(ctx context.Context, input model.FindByIDTransactionInput) (*model.APIResponseTransactionDeleteAt, error) {
	panic(fmt.Errorf("not implemented: RestoreTransaction - restoreTransaction"))
}

// DeleteTransactionPermanent is the resolver for the deleteTransactionPermanent field.
func (r *mutationResolver) DeleteTransactionPermanent(ctx context.Context, input model.FindByIDTransactionInput) (*model.APIResponseTransactionDelete, error) {
	panic(fmt.Errorf("not implemented: DeleteTransactionPermanent - deleteTransactionPermanent"))
}

// RestoreAllTransaction is the resolver for the restoreAllTransaction field.
func (r *mutationResolver) RestoreAllTransaction(ctx context.Context) (*model.APIResponseTransactionAll, error) {
	panic(fmt.Errorf("not implemented: RestoreAllTransaction - restoreAllTransaction"))
}

// DeleteAllTransactionPermanent is the resolver for the deleteAllTransactionPermanent field.
func (r *mutationResolver) DeleteAllTransactionPermanent(ctx context.Context) (*model.APIResponseTransactionAll, error) {
	panic(fmt.Errorf("not implemented: DeleteAllTransactionPermanent - deleteAllTransactionPermanent"))
}

// FindAllTransaction is the resolver for the findAllTransaction field.
func (r *queryResolver) FindAllTransaction(ctx context.Context, input *model.FindAllTransactionInput) (*model.APIResponsePaginationTransaction, error) {
	panic(fmt.Errorf("not implemented: FindAllTransaction - findAllTransaction"))
}

// FindByMerchantTransaction is the resolver for the findByMerchantTransaction field.
func (r *queryResolver) FindByMerchantTransaction(ctx context.Context, input model.FindAllTransactionMerchantInput) (*model.APIResponsePaginationTransaction, error) {
	panic(fmt.Errorf("not implemented: FindByMerchantTransaction - findByMerchantTransaction"))
}

// FindByIDTransaction is the resolver for the findByIdTransaction field.
func (r *queryResolver) FindByIDTransaction(ctx context.Context, input model.FindByIDTransactionInput) (*model.APIResponseTransaction, error) {
	panic(fmt.Errorf("not implemented: FindByIDTransaction - findByIdTransaction"))
}

// FindMonthStatusSuccess is the resolver for the findMonthStatusSuccess field.
func (r *queryResolver) FindMonthStatusSuccess(ctx context.Context, input model.FindMonthlyTransactionStatusInput) (*model.APIResponseTransactionMonthAmountSuccess, error) {
	panic(fmt.Errorf("not implemented: FindMonthStatusSuccess - findMonthStatusSuccess"))
}

// FindYearStatusSuccess is the resolver for the findYearStatusSuccess field.
func (r *queryResolver) FindYearStatusSuccess(ctx context.Context, input model.FindYearlyTransactionStatusInput) (*model.APIResponseTransactionYearAmountSuccess, error) {
	panic(fmt.Errorf("not implemented: FindYearStatusSuccess - findYearStatusSuccess"))
}

// FindMonthStatusFailed is the resolver for the findMonthStatusFailed field.
func (r *queryResolver) FindMonthStatusFailed(ctx context.Context, input model.FindMonthlyTransactionStatusInput) (*model.APIResponseTransactionMonthAmountFailed, error) {
	panic(fmt.Errorf("not implemented: FindMonthStatusFailed - findMonthStatusFailed"))
}

// FindYearStatusFailed is the resolver for the findYearStatusFailed field.
func (r *queryResolver) FindYearStatusFailed(ctx context.Context, input model.FindYearlyTransactionStatusInput) (*model.APIResponseTransactionYearAmountFailed, error) {
	panic(fmt.Errorf("not implemented: FindYearStatusFailed - findYearStatusFailed"))
}

// FindMonthStatusSuccessByMerchant is the resolver for the findMonthStatusSuccessByMerchant field.
func (r *queryResolver) FindMonthStatusSuccessByMerchant(ctx context.Context, input model.FindMonthlyTransactionStatusByMerchantInput) (*model.APIResponseTransactionMonthAmountSuccess, error) {
	panic(fmt.Errorf("not implemented: FindMonthStatusSuccessByMerchant - findMonthStatusSuccessByMerchant"))
}

// FindYearStatusSuccessByMerchant is the resolver for the findYearStatusSuccessByMerchant field.
func (r *queryResolver) FindYearStatusSuccessByMerchant(ctx context.Context, input model.FindYearlyTransactionStatusByMerchantInput) (*model.APIResponseTransactionYearAmountSuccess, error) {
	panic(fmt.Errorf("not implemented: FindYearStatusSuccessByMerchant - findYearStatusSuccessByMerchant"))
}

// FindMonthStatusFailedByMerchant is the resolver for the findMonthStatusFailedByMerchant field.
func (r *queryResolver) FindMonthStatusFailedByMerchant(ctx context.Context, input model.FindMonthlyTransactionStatusByMerchantInput) (*model.APIResponseTransactionMonthAmountFailed, error) {
	panic(fmt.Errorf("not implemented: FindMonthStatusFailedByMerchant - findMonthStatusFailedByMerchant"))
}

// FindYearStatusFailedByMerchant is the resolver for the findYearStatusFailedByMerchant field.
func (r *queryResolver) FindYearStatusFailedByMerchant(ctx context.Context, input model.FindYearlyTransactionStatusByMerchantInput) (*model.APIResponseTransactionYearAmountFailed, error) {
	panic(fmt.Errorf("not implemented: FindYearStatusFailedByMerchant - findYearStatusFailedByMerchant"))
}

// FindMonthMethodSuccess is the resolver for the findMonthMethodSuccess field.
func (r *queryResolver) FindMonthMethodSuccess(ctx context.Context, input model.MonthTransactionMethodInput) (*model.APIResponseTransactionMonthPaymentMethod, error) {
	panic(fmt.Errorf("not implemented: FindMonthMethodSuccess - findMonthMethodSuccess"))
}

// FindYearMethodSuccess is the resolver for the findYearMethodSuccess field.
func (r *queryResolver) FindYearMethodSuccess(ctx context.Context, input model.YearTransactionMethodInput) (*model.APIResponseTransactionYearPaymentMethod, error) {
	panic(fmt.Errorf("not implemented: FindYearMethodSuccess - findYearMethodSuccess"))
}

// FindMonthMethodByMerchantSuccess is the resolver for the findMonthMethodByMerchantSuccess field.
func (r *queryResolver) FindMonthMethodByMerchantSuccess(ctx context.Context, input model.MonthTransactionMethodByMerchantInput) (*model.APIResponseTransactionMonthPaymentMethod, error) {
	panic(fmt.Errorf("not implemented: FindMonthMethodByMerchantSuccess - findMonthMethodByMerchantSuccess"))
}

// FindYearMethodByMerchantSuccess is the resolver for the findYearMethodByMerchantSuccess field.
func (r *queryResolver) FindYearMethodByMerchantSuccess(ctx context.Context, input model.YearTransactionMethodByMerchantInput) (*model.APIResponseTransactionYearPaymentMethod, error) {
	panic(fmt.Errorf("not implemented: FindYearMethodByMerchantSuccess - findYearMethodByMerchantSuccess"))
}

// FindMonthMethodFailed is the resolver for the findMonthMethodFailed field.
func (r *queryResolver) FindMonthMethodFailed(ctx context.Context, input model.MonthTransactionMethodInput) (*model.APIResponseTransactionMonthPaymentMethod, error) {
	panic(fmt.Errorf("not implemented: FindMonthMethodFailed - findMonthMethodFailed"))
}

// FindYearMethodFailed is the resolver for the findYearMethodFailed field.
func (r *queryResolver) FindYearMethodFailed(ctx context.Context, input model.YearTransactionMethodInput) (*model.APIResponseTransactionYearPaymentMethod, error) {
	panic(fmt.Errorf("not implemented: FindYearMethodFailed - findYearMethodFailed"))
}

// FindMonthMethodByMerchantFailed is the resolver for the findMonthMethodByMerchantFailed field.
func (r *queryResolver) FindMonthMethodByMerchantFailed(ctx context.Context, input model.MonthTransactionMethodByMerchantInput) (*model.APIResponseTransactionMonthPaymentMethod, error) {
	panic(fmt.Errorf("not implemented: FindMonthMethodByMerchantFailed - findMonthMethodByMerchantFailed"))
}

// FindYearMethodByMerchantFailed is the resolver for the findYearMethodByMerchantFailed field.
func (r *queryResolver) FindYearMethodByMerchantFailed(ctx context.Context, input model.YearTransactionMethodByMerchantInput) (*model.APIResponseTransactionYearPaymentMethod, error) {
	panic(fmt.Errorf("not implemented: FindYearMethodByMerchantFailed - findYearMethodByMerchantFailed"))
}

// FindByActiveTransaction is the resolver for the findByActiveTransaction field.
func (r *queryResolver) FindByActiveTransaction(ctx context.Context, input *model.FindAllTransactionInput) (*model.APIResponsePaginationTransactionDeleteAt, error) {
	panic(fmt.Errorf("not implemented: FindByActiveTransaction - findByActiveTransaction"))
}

// FindByTrashedTransaction is the resolver for the findByTrashedTransaction field.
func (r *queryResolver) FindByTrashedTransaction(ctx context.Context, input *model.FindAllTransactionInput) (*model.APIResponsePaginationTransactionDeleteAt, error) {
	panic(fmt.Errorf("not implemented: FindByTrashedTransaction - findByTrashedTransaction"))
}
